(() => {
  const part = (text, highlight = false, tone = '') => ({ text, highlight, tone });

  const shared = {
    startPoint: { x: 3, y: 2 },
    explorePoint: { x: 1, y: 4 },
    equalPoint: { x: -3, y: 3 },
    secondEqualPoint: { x: 2, y: -2 },
    lineLabel: 'y = -x',
    reflect: (point) => ({ x: -point.y, y: -point.x }),
    graph: { minX: -6, maxX: 6, minY: -4, maxY: 4 },
    isOnReflectionLine: (point) => point.x + point.y === 0,
    dragBounds: (graph) => ({
      minX: Math.max(graph.minX, -graph.maxY),
      maxX: Math.min(graph.maxX, -graph.minY),
      minY: Math.max(graph.minY, -graph.maxX),
      maxY: Math.min(graph.maxY, -graph.minX),
    }),
  };

  const makeSteps = (ui) => [
    {
      id: 'line-intro',
      title: ui.titleLine,
      visual: 'intro',
      panel: [
        [part(ui.definitionA)],
        [part(ui.definitionB, true)],
        [part(ui.definitionC)],
      ],
      lower: ui.tapNext,
    },
    {
      id: 'line-tap-first',
      title: ui.plotLineTitle,
      visual: 'lineBuild',
      requires: 'equalPoint',
      ftuePoints: [{ x: -3, y: 3 }, { x: -2, y: 2 }, { x: -1, y: 1 }, { x: 0, y: 0 }, { x: 1, y: -1 }],
      panel: [[part(ui.tapEqual)]],
      lower: ui.tapEqual,
    },
    {
      id: 'line-tap-second',
      title: ui.plotLineTitle,
      visual: 'lineBuild',
      requires: 'secondEqualPoint',
      ftuePoints: [{ x: -2, y: 2 }, { x: -1, y: 1 }, { x: 1, y: -1 }, { x: 2, y: -2 }, { x: 3, y: -3 }],
      panel: [[part(ui.tapAnotherEqual)]],
      lower: ui.tapAnotherEqual,
    },
    {
      id: 'line-explain',
      title: ui.plotLineTitle,
      visual: 'lineComplete',
      panel: [
        [part(ui.thisLineRepresents)],
        [part(ui.equalCoordinatesRule, true)],
      ],
      lower: ui.tapNext,
    },
    {
      id: 'draw-perp',
      title: ui.foldTitle,
      visual: 'pointOnly',
      button: ui.drawPerpendicular,
      panel: [
        [part(ui.forReflectionGivenA)],
        [part(ui.forReflectionGivenB, true)],
        [part(ui.forReflectionGivenC)],
      ],
      lower: ui.tapDrawPerpendicular,
    },
    {
      id: 'perp-drawn',
      title: ui.imageTitle,
      visual: 'perpendicular',
      button: ui.countDistance,
      panel: [
        [part(ui.notePerpendicularA)],
        [part(ui.notePerpendicularB, true)],
        [part(ui.notePerpendicularC)],
      ],
      lower: ui.tapCountDistance,
    },
    {
      id: 'plot-image-draw',
      title: ui.imageTitle,
      visual: 'plotImageDraw',
      panel: [
        [part(ui.notePerpendicularA)],
        [part(ui.notePerpendicularB, true)],
        [part(ui.notePerpendicularC)],
      ],
      lower: '',
    },
    {
      id: 'same-distance-mark',
      title: ui.imageTitle,
      visual: 'distanceTwo',
      panel: [[part(ui.findSameDistance, true)]],
      lower: '',
      autoNextMs: 1500,
    },
    {
      id: 'image-found',
      title: ui.imageTitle,
      visual: 'find-image',
      panel: [[part(ui.imageCoordinatesPattern)]],
      button: ui.revealPattern,
      lower: ui.tapRevealPattern,
    },
    {
      id: 'pattern-a',
      title: ui.coordinateTitle,
      visual: 'patternA',
      panelKind: 'coordinate',
      lower: '',
      autoNextMs: 900,
    },
    {
      id: 'pattern-y-first',
      title: ui.coordinateTitle,
      visual: 'patternYFirst',
      panelKind: 'coordinate',
      lower: '',
      autoNextMs: 900,
    },
    {
      id: 'pattern-x-second',
      title: ui.coordinateTitle,
      visual: 'patternXSecond',
      panelKind: 'coordinate',
      lower: '',
      autoNextMs: 900,
    },
    {
      id: 'swap-rule',
      title: ui.coordinateTitle,
      visual: 'patternComplete',
      panelKind: 'rule',
      lower: ui.tapMovePoint,
    },
    {
      id: 'drag-explore',
      title: ui.coordinateTitle,
      visual: 'dragExplore',
      requires: 'dragPoint',
      panelKind: 'rule',
      lower: ui.dragPoint,
    },
    {
      id: 'summary',
      title: ui.titleLine,
      visual: 'summary',
      button: ui.generalize,
      panel: [[part(ui.summaryA)], [part(ui.summaryB, true)]],
      lower: ui.tapGeneralize,
    },
    {
      id: 'general-x',
      title: ui.titleLine,
      visual: 'generalXOnly',
      panelKind: 'algebra',
      lower: '',
      autoNextMs: 900,
    },
    {
      id: 'general-y',
      title: ui.titleLine,
      visual: 'generalComplete',
      panelKind: 'algebra',
      lower: ui.completeTitle,
    },
  ];

  const appData = {
    en: {
      html_title: 'Reflection across y = -x',
      shared,
      ui: {
        welcomeTitle: 'Reflection of a Point about the line y = -x',
        welcomeLines: [
          [part('Reflection of a point means finding an image at the '), part('same perpendicular distance', true), part(' from the line of reflection.')],
          [part("Let's visualise reflection about "), part('y = -x', true), part(' and discover the coordinate rule.')],
        ],
        welcomePrompt: [part('Tap '), part('START', true), part(' to begin!')],
        startButton: 'START',
        startOverButton: 'START OVER',
        completeTitle: 'Activity Completed!',
        completeLines: [
          [part('When a point is reflected about the line '), part('y = -x', true), part(', the coordinates '), part('negate and swap', true), part(' to give the image.')],
          [part('(x, y) becomes '), part('(-y, -x)', true), part('.')],
        ],
        backLabel: 'Back',
        nextLabel: 'Next',
        titleLine: 'Reflection of a Point about the line y = -x',
        plotLineTitle: 'Plot the LINE of REFLECTION y = -x',
        foldTitle: 'Fold across the LINE of REFLECTION y = -x',
        imageTitle: 'Image across the LINE of REFLECTION y = -x',
        coordinateTitle: 'Coordinates of image on reflection across line y = -x',
        definitionA: 'Reflection of a point is simply finding an image',
        definitionB: 'at the same perpendicular distance',
        definitionC: 'from the line of reflection.',
        tapEqual: 'Tap a point on the grid where x and y are opposites (y = -x).',
        tapAnotherEqual: 'Tap another point on the grid where x and y are opposites (y = -x).',
        wrongEqual: 'Oops! The x and y coordinates are not opposites here!',
        thisLineRepresents: 'This line represents',
        equalCoordinatesRule: 'y = -x, all points on the line have opposite x and y coordinates!',
        tapAnyPoint: 'Tap any point on the grid.',
        forReflectionA: 'For reflection, we need to find',
        perpendicularDistance: 'perpendicular distance',
        forReflectionB: 'from the point to the line of reflection.',
        forReflectionGivenA: "To Reflect given point A(3, 2), let's find",
        forReflectionGivenB: 'perpendicular distance',
        forReflectionGivenC: 'from point A(3, 2) to the line of reflection.',
        drawPerpendicular: 'Draw perpendicular',
        tapDrawPerpendicular: 'Tap the button to draw perpendicular',
        notePerpendicularA: 'Note that the perpendicular',
        notePerpendicularB: 'to the line y = -x',
        notePerpendicularC: 'is simply the other diagonal on the grid!',
        imageCoordinatesInterchanged: 'The x and y coordinates of the image are negated and swapped!',
        countDistance: 'Plot Image',
        tapCountDistance: 'Tap the button to plot image',
        countingDistance: 'Count the diagonal distance from the point to the line of reflection.',
        findSameDistance: 'Now, find a point on the other side at the same distance from the line of reflection...',
        findImage: 'Find image',
        findImageOtherSide: 'Tap the button to find image on the other side.',
        tapFindImage: 'Tap the button to find image on the other side',
        imageCoordinatesPattern: 'Note the coordinates of the image thus formed. Do you see a pattern?',
        revealPattern: 'Reveal Pattern',
        noteCoordinates: 'Note the coordinates of the image thus formed.',
        seePattern: 'Do you see a pattern?',
        ruleA: 'On reflection about line y = -x,',
        ruleB: 'negating and swapping coordinates of the point gives us',
        ruleC: 'the image!',
        summaryA: 'When a point is reflected about the line y = -x on a coordinate plane,',
        summaryB: 'the coordinates negate and swap to give us the image.',
        generalize: 'Generalize',
        tapRevealPattern: "Tap 'Reveal Pattern'",
        tapMovePoint: 'Tap next to move the point and note the image position',
        dragPoint: 'Drag the pre-image point around and notice the image.',
        tapSummarize: 'Tap next to summarize the rule for reflection about the line y = -x',
        tapGeneralize: "Tap 'Generalize' to make an algebraic rule",
        tapNext: 'Tap next to continue.',
        pointLabel: '({x}, {y})',
        preImage: 'pre-image',
        image: 'image',
        unit: 'unit',
        units: 'units',
      },
    },
    id: {
      html_title: 'Refleksi terhadap y = -x',
      shared,
      ui: {
        welcomeTitle: 'Refleksi Titik terhadap garis y = -x',
        welcomeLines: [
          [part('Refleksi titik berarti menentukan bayangan pada '), part('jarak tegak lurus yang sama', true), part(' dari garis refleksi.')],
          [part('Mari visualisasikan refleksi terhadap '), part('y = -x', true), part(' dan temukan aturan koordinatnya.')],
        ],
        welcomePrompt: [part('Ketuk '), part('MULAI', true), part(' untuk memulai!')],
        startButton: 'MULAI',
        startOverButton: 'MULAI LAGI',
        completeTitle: 'Aktivitas Selesai!',
        completeLines: [
          [part('Ketika titik direfleksikan terhadap garis '), part('y = -x', true), part(', koordinatnya '), part('dinegasikan dan ditukar', true), part(' untuk membentuk bayangan.')],
          [part('(x, y) menjadi '), part('(-y, -x)', true), part('.')],
        ],
        backLabel: 'Kembali',
        nextLabel: 'Berikutnya',
        titleLine: 'Refleksi Titik terhadap garis y = -x',
        plotLineTitle: 'Plot GARIS REFLEKSI y = -x',
        foldTitle: 'Tegak Lurus terhadap GARIS REFLEKSI y = -x',
        imageTitle: 'Bayangan terhadap GARIS REFLEKSI y = -x',
        coordinateTitle: 'Koordinat bayangan pada refleksi terhadap garis y = -x',
        definitionA: 'Refleksi titik berarti menentukan bayangan',
        definitionB: 'pada jarak tegak lurus yang sama',
        definitionC: 'dari garis refleksi.',
        tapEqual: 'Ketuk titik pada bidang yang koordinat x dan y-nya berlawanan (y = -x).',
        tapAnotherEqual: 'Ketuk titik lain pada bidang yang koordinat x dan y-nya berlawanan (y = -x).',
        wrongEqual: 'Oops! Koordinat x dan y tidak berlawanan di sini!',
        thisLineRepresents: 'Garis ini menunjukkan',
        equalCoordinatesRule: 'y = -x, semua titik pada garis memiliki koordinat x dan y yang berlawanan!',
        tapAnyPoint: 'Ketuk titik mana pun pada grid.',
        forReflectionA: 'Untuk refleksi, kita perlu menentukan',
        perpendicularDistance: 'jarak tegak lurus',
        forReflectionB: 'dari titik ke garis refleksi.',
        forReflectionGivenA: 'Untuk merefleksikan titik A(3, 2), mari kita tentukan',
        forReflectionGivenB: 'jarak tegak lurus',
        forReflectionGivenC: 'dari titik A(3, 2) ke garis refleksi.',
        drawPerpendicular: 'Gambar tegak lurus',
        tapDrawPerpendicular: 'Ketuk tombol untuk menggambar garis tegak lurus',
        notePerpendicularA: 'Perhatikan bahwa garis tegak lurus',
        notePerpendicularB: 'terhadap garis y = -x',
        notePerpendicularC: 'adalah diagonal lain pada bidang!',
        imageCoordinatesInterchanged: 'Koordinat x dan y pada bayangan dinegasikan dan ditukar!',
        countDistance: 'Plot Bayangan',
        tapCountDistance: 'Ketuk tombol untuk memplot bayangan',
        countingDistance: 'Hitung jarak diagonal dari titik ke garis refleksi.',
        findSameDistance: 'Sekarang, cari titik di sisi lain pada jarak yang sama dari garis refleksi...',
        findImage: 'Cari bayangan',
        findImageOtherSide: 'Ketuk tombol untuk mencari bayangan di sisi lain.',
        tapFindImage: 'Ketuk tombol untuk mencari bayangan di sisi lain',
        imageCoordinatesPattern: 'Perhatikan koordinat bayangan yang terbentuk. Apakah kamu melihat polanya?',
        revealPattern: 'Tampilkan Pola',
        noteCoordinates: 'Perhatikan koordinat bayangan yang terbentuk.',
        seePattern: 'Apakah kamu melihat polanya?',
        ruleA: 'Pada refleksi terhadap garis y = -x,',
        ruleB: 'menegasikan dan menukar koordinat titik menghasilkan',
        ruleC: 'bayangannya!',
        summaryA: 'Ketika titik direfleksikan terhadap garis y = -x pada bidang koordinat,',
        summaryB: 'koordinatnya dinegasikan dan ditukar untuk menghasilkan bayangan.',
        generalize: 'Rumuskan',
        tapRevealPattern: "Ketuk 'Tampilkan Pola'",
        tapMovePoint: 'Ketuk berikutnya untuk memindahkan titik dan mengamati bayangan',
        dragPoint: 'Geser titik objek dan amati bayangannya.',
        tapSummarize: 'Ketuk berikutnya untuk merangkum aturan refleksi terhadap garis y = -x',
        tapGeneralize: "Ketuk 'Rumuskan' untuk membuat aturan aljabar",
        tapNext: 'Ketuk berikutnya untuk melanjutkan.',
        pointLabel: '({x}, {y})',
        preImage: 'objek',
        image: 'bayangan',
        unit: 'satuan',
        units: 'satuan',
      },
    },
  };

  Object.values(appData).forEach((lang) => {
    lang.steps = makeSteps(lang.ui);
  });

  window.setLanguage = (language) => {
    window.T = appData[language] || appData.en;
    document.title = window.T.html_title;
  };
  window.setLanguage('en');
})();
