
const decimal = {
  en: ".",
  id: ",",
};

const DATA = {
  en: {
    app: {
      common: {
        tapNextToContinue: "Tap » to continue.",
        tapNumpadToFill: "Tap using numpad to fill in the highlighted box and Check.",
        tapNextToAddWeights: "Tap » to add the lengths.",
        tapNextToAddKg: "Tap » to add length in metres.",
        tapNextForAnother: "Tap » for another challenge.",
        tapNextToSummarise: "Tap » to summarise.",
        tapNextToSubtract: "Tap » to subtract the lengths.",
        tapNextToSubtractKg: "Tap » to subtract length in metres.",
      },
      start: {
        heading: "Word problems on length",
        text: "Let's explore solving word problems on length.<br><br>Tap \"Start\" to begin!",
        buttonText: "Start",
      },
      summary: {
        heading: "Length word problems",
        text: "Awesome! Now you know how to solve word problems on length.",
        buttonText: "Start Over",
      },
      steps: {
        1: {
          characterText: "Hi!\nI am Jammal.\nLet's explore solving some word problems related to length.",
          characterImage: "normal.png",
        },
        2: {
          characterText: "Let's read the word problem.",
        },
        3: {
          characterText: "Step 1: Write the lengths given in the word problem.",
        },
        4: {
          characterText: "Step 2: Choose the math action needed to solve the word problem.",
        },
      },
      mcqOptions: {
        add: "ADD",
        subtract: "SUBTRACT",
      },
      operatorQuestion: "Should we <y>add</y> or <y>subtract</y> the lengths?\nCheck for words in the word problem that indicate addition or subtraction.",
      oops: "Oops!",
      tryAgain: "Try again.",
      wellDone: "Well done!",
      questions: [
        {
          statement: "A rope is 5 m 40 cm long and another rope is 3 m 25 cm long. What is their total length?",
          itemName1: "Length of the first rope",
          itemName2: "Length of the other rope",
          kgLabel: "m",
          gmLabel: "cm",
          kgAns1: 5,
          gmAns1: 40,
          kgAns2: 3,
          gmAns2: 25,
          kgResult: 8,
          gmResult: 65,
          operation: "add",
          hintWord: "total",
          step3WrongFeedbackRow1: "Oops!\nTry again.\nThe first rope is 5 m 40 cm long.",
          step3WrongFeedbackRow2: "Oops!\nTry again.\nThe other rope is 3 m 25 cm long.",
          step3CorrectFeedback: "Well done!\nYou have correctly identified the lengths given in the question.",
          step4WrongFeedback: "Oops!\nRead the question again. Check for words that indicate the math action.",
          step4CorrectFeedback: "Well done!\nThe word 'total' in the word problem indicated that the lengths should be added.",
          step5CharacterText: "Step 3: Add the lengths.\n\nLet's add the centimetres first.",
          step5WrongFeedback: "Oops!\nTry again.\n\nAdd 40 and 25 to get the total length in centimetres.",
          step5CorrectFeedback: "Well done!\n40 cm + 25 cm\n= 65 cm.",
          step5CtAfterGm: "Step 3: Add the lengths.\n40 cm + 25 cm\n= 65 cm.\n\nLet's add the lengths in metres.",
          step6WrongFeedback: "Oops!\nTry again.\n\nAdd 5 m and 3 m to get the total length in metres.",
          step6CorrectFeedback: "Well done!\nThe total length is\n8 m 65 cm.",
          step6FinalCt: "Well Done!\nThe total length of the two ropes is 8 m 65 cm.\n\nLet's try another question.",
          step6FinalCtLast: "Well Done!\nThe total length of the two ropes is 8 m 65 cm.",
          resultLabel: "Total",
        },
        {
          statement: "A ribbon measures 2 m 25 cm and another ribbon measures 4 m 50 cm. Find the total length.",
          itemName1: "Length of the first ribbon",
          itemName2: "Length of the other ribbon",
          kgLabel: "m",
          gmLabel: "cm",
          kgAns1: 2,
          gmAns1: 25,
          kgAns2: 4,
          gmAns2: 50,
          kgResult: 6,
          gmResult: 75,
          operation: "add",
          hintWord: "total",
          step3WrongFeedbackRow1: "Oops!\nTry again.\nThe first ribbon measures 2 m 25 cm.",
          step3WrongFeedbackRow2: "Oops!\nTry again.\nThe other ribbon measures 4 m 50 cm.",
          step3CorrectFeedback: "Well done!\nYou have correctly identified the lengths given in the question.",
          step4WrongFeedback: "Oops!\nRead the question again. Check for words that indicate the math action.",
          step4CorrectFeedback: "Well done!\nThe word 'total' in the word problem indicated that the lengths should be added.",
          step5CharacterText: "Step 3: Add the lengths.\n\nLet's add the centimetres first.",
          step5WrongFeedback: "Oops!\nTry again.\n\nAdd 25 and 50 to get the total length in centimetres.",
          step5CorrectFeedback: "Well done!\n25 cm + 50 cm\n= 75 cm.",
          step5CtAfterGm: "Step 3: Add the lengths.\n25 cm + 50 cm\n= 75 cm.\n\nLet's add the lengths in metres.",
          step6WrongFeedback: "Oops!\nTry again.\n\nAdd 2 m and 4 m to get the total length in metres.",
          step6CorrectFeedback: "Well done!\nThe total length is\n6 m 75 cm.",
          step6FinalCt: "Well Done!\nThe total length of the two ribbons is 6 m 75 cm.\n\nLet's try another question.",
          step6FinalCtLast: "Well Done!\nThe total length of the two ribbons is 6 m 75 cm.",
          resultLabel: "Total",
        },
        {
          statement: "A road is 12 m 60 cm long and another stretch is 8 m 5 cm long. What is the total length?",
          itemName1: "Length of the first stretch",
          itemName2: "Length of the other stretch",
          kgLabel: "m",
          gmLabel: "cm",
          kgAns1: 12,
          gmAns1: 60,
          kgAns2: 8,
          gmAns2: 5,
          kgResult: 20,
          gmResult: 65,
          operation: "add",
          hintWord: "total",
          step3WrongFeedbackRow1: "Oops!\nTry again.\nThe first road stretch is 12 m 60 cm long.",
          step3WrongFeedbackRow2: "Oops!\nTry again.\nThe other stretch is 8 m 5 cm long.",
          step3CorrectFeedback: "Well done!\nYou have correctly identified the lengths given in the question.",
          step4WrongFeedback: "Oops!\nRead the question again. Check for words that indicate the math action.",
          step4CorrectFeedback: "Well done!\nThe word 'total' in the word problem indicated that the lengths should be added.",
          step5CharacterText: "Step 3: Add the lengths.\n\nLet's add the centimetres first.",
          step5WrongFeedback: "Oops!\nTry again.\n\nAdd 60 and 5 to get the total length in centimetres.",
          step5CorrectFeedback: "Well done!\n60 cm + 5 cm\n= 65 cm.",
          step5CtAfterGm: "Step 3: Add the lengths.\n60 cm + 5 cm\n= 65 cm.\n\nLet's add the lengths in metres.",
          step6WrongFeedback: "Oops!\nTry again.\n\nAdd 12 m and 8 m to get the total length in metres.",
          step6CorrectFeedback: "Well done!\nThe total length is\n20 m 65 cm.",
          step6FinalCt: "Well Done!\nThe total length of the road is 20 m 65 cm.\n\nLet's try another question.",
          step6FinalCtLast: "Well Done!\nThe total length of the road is 20 m 65 cm.",
          resultLabel: "Total",
        },
        {
          statement: "A cloth piece is 6 m 35 cm long and another piece is 3 m long. What is the combined length?",
          itemName1: "Length of the first cloth piece",
          itemName2: "Length of the other cloth piece",
          kgLabel: "m",
          gmLabel: "cm",
          kgAns1: 6,
          gmAns1: 35,
          kgAns2: 3,
          gmAns2: 0,
          kgResult: 9,
          gmResult: 35,
          operation: "add",
          hintWord: "combined",
          step3WrongFeedbackRow1: "Oops!\nTry again.\nThe first cloth piece is 6 m 35 cm long.",
          step3WrongFeedbackRow2: "Oops!\nTry again.\nThe other cloth piece is 3 m long.",
          step3CorrectFeedback: "Well done!\nYou have correctly identified the lengths given in the question.",
          step4WrongFeedback: "Oops!\nRead the question again. Check for words that indicate the math action.",
          step4CorrectFeedback: "Well done!\nThe word 'combined' in the word problem indicated that the lengths should be added.",
          step5CharacterText: "Step 3: Add the lengths.\n\nLet's add the centimetres first.",
          step5WrongFeedback: "Oops!\nTry again.\n\nAdd 35 and 0 to get the total length in centimetres.",
          step5CorrectFeedback: "Well done!\n35 cm + 0 cm\n= 35 cm.",
          step5CtAfterGm: "Step 3: Add the lengths.\n35 cm + 0 cm\n= 35 cm.\n\nLet's add the lengths in metres.",
          step6WrongFeedback: "Oops!\nTry again.\n\nAdd 6 m and 3 m to get the total length in metres.",
          step6CorrectFeedback: "Well done!\nThe combined length is\n9 m 35 cm.",
          step6FinalCt: "Well Done!\nThe combined length of the cloth pieces is 9 m 35 cm.\n\nLet's try another question.",
          step6FinalCtLast: "Well Done!\nThe combined length of the cloth pieces is 9 m 35 cm.",
          resultLabel: "Total",
        },
        {
          statement: "A wire is 9 m 20 cm long and another wire is 7 m 75 cm long. Find the total length.",
          itemName1: "Length of the first wire",
          itemName2: "Length of the other wire",
          kgLabel: "m",
          gmLabel: "cm",
          kgAns1: 9,
          gmAns1: 20,
          kgAns2: 7,
          gmAns2: 75,
          kgResult: 16,
          gmResult: 95,
          operation: "add",
          hintWord: "total",
          step3WrongFeedbackRow1: "Oops!\nTry again.\nThe first wire is 9 m 20 cm long.",
          step3WrongFeedbackRow2: "Oops!\nTry again.\nThe other wire is 7 m 75 cm long.",
          step3CorrectFeedback: "Well done!\nYou have correctly identified the lengths given in the question.",
          step4WrongFeedback: "Oops!\nRead the question again. Check for words that indicate the math action.",
          step4CorrectFeedback: "Well done!\nThe word 'total' in the word problem indicated that the lengths should be added.",
          step5CharacterText: "Step 3: Add the lengths.\n\nLet's add the centimetres first.",
          step5WrongFeedback: "Oops!\nTry again.\n\nAdd 20 and 75 to get the total length in centimetres.",
          step5CorrectFeedback: "Well done!\n20 cm + 75 cm\n= 95 cm.",
          step5CtAfterGm: "Step 3: Add the lengths.\n20 cm + 75 cm\n= 95 cm.\n\nLet's add the lengths in metres.",
          step6WrongFeedback: "Oops!\nTry again.\n\nAdd 9 m and 7 m to get the total length in metres.",
          step6CorrectFeedback: "Well done!\nThe total length is\n16 m 95 cm.",
          step6FinalCt: "Well Done!\nThe total length of the two wires is 16 m 95 cm.\n\nLet's try another question.",
          step6FinalCtLast: "Well Done!\nThe total length of the two wires is 16 m 95 cm.",
          resultLabel: "Total",
        },
        {
          statement: "A ladder is 20 m 50 cm long. 8 m 36 cm is damaged. What is the usable length?",
          itemName1: "Full length of the ladder",
          itemName2: "Damaged length",
          kgLabel: "m",
          gmLabel: "cm",
          kgAns1: 20,
          gmAns1: 50,
          kgAns2: 8,
          gmAns2: 36,
          kgResult: 12,
          gmResult: 14,
          operation: "subtract",
          hintWord: "usable",
          step3WrongFeedbackRow1: "Oops!\nTry again.\nThe ladder is 20 m 50 cm long.",
          step3WrongFeedbackRow2: "Oops!\nTry again.\n8 m 36 cm of the ladder is damaged.",
          step3CorrectFeedback: "Well done!\nYou have correctly identified the lengths given in the question.",
          step4WrongFeedback: "Oops!\nRead the question again. Check for words that indicate the math action.",
          step4CorrectFeedback: "Well done!\nFinding the 'usable' length means we should subtract the damaged part from the whole.",
          step5CharacterText: "Step 3: Subtract the lengths.\n\nLet's subtract the centimetres first.",
          step5WrongFeedback: "Oops!\nTry again.\n\nSubtract 36 from 50 to get the usable length in centimetres.",
          step5CorrectFeedback: "Well done!\n50 cm - 36 cm\n= 14 cm.",
          step5CtAfterGm: "Step 3: Subtract the lengths.\n50 cm - 36 cm\n= 14 cm.\n\nLet's subtract the lengths in metres.",
          step6WrongFeedback: "Oops!\nTry again.\n\nSubtract 8 m from 20 m to get the usable length in metres.",
          step6CorrectFeedback: "Well done!\nThe usable length is\n12 m 14 cm.",
          step6FinalCt: "Well Done!\nThe usable length of the ladder is 12 m 14 cm.\n\nLet's try another question.",
          step6FinalCtLast: "Well Done!\nThe usable length of the ladder is 12 m 14 cm.",
          resultLabel: "Usable",
        },
        {
          statement: "A tape is 13 m 90 cm long. 7 m 45 cm is used. How much tape remains?",
          itemName1: "Full length of the tape",
          itemName2: "Length used",
          kgLabel: "m",
          gmLabel: "cm",
          kgAns1: 13,
          gmAns1: 90,
          kgAns2: 7,
          gmAns2: 45,
          kgResult: 6,
          gmResult: 45,
          operation: "subtract",
          hintWord: "remains",
          step3WrongFeedbackRow1: "Oops!\nTry again.\nThe tape is 13 m 90 cm long.",
          step3WrongFeedbackRow2: "Oops!\nTry again.\n7 m 45 cm of the tape is used.",
          step3CorrectFeedback: "Well done!\nYou have correctly identified the lengths given in the question.",
          step4WrongFeedback: "Oops!\nRead the question again. Check for words that indicate the math action.",
          step4CorrectFeedback: "Well done!\nThe word 'remains' in the word problem indicated that the lengths should be subtracted.",
          step5CharacterText: "Step 3: Subtract the lengths.\n\nLet's subtract the centimetres first.",
          step5WrongFeedback: "Oops!\nTry again.\n\nSubtract 45 from 90 to get the remaining length in centimetres.",
          step5CorrectFeedback: "Well done!\n90 cm - 45 cm\n= 45 cm.",
          step5CtAfterGm: "Step 3: Subtract the lengths.\n90 cm - 45 cm\n= 45 cm.\n\nLet's subtract the lengths in metres.",
          step6WrongFeedback: "Oops!\nTry again.\n\nSubtract 7 m from 13 m to get the remaining length in metres.",
          step6CorrectFeedback: "Well done!\nThe remaining tape is\n6 m 45 cm.",
          step6FinalCt: "Well Done!\nThe tape that remains is 6 m 45 cm.\n\nLet's try another question.",
          step6FinalCtLast: "Well Done!\nThe tape that remains is 6 m 45 cm.",
          resultLabel: "Remaining",
        },
        {
          statement: "A bridge is 40 m 60 cm long. 15 m 52 cm is constructed. How much is yet to be built?",
          itemName1: "Planned length of the bridge",
          itemName2: "Length already built",
          kgLabel: "m",
          gmLabel: "cm",
          kgAns1: 40,
          gmAns1: 60,
          kgAns2: 15,
          gmAns2: 52,
          kgResult: 25,
          gmResult: 8,
          operation: "subtract",
          hintWord: "yet",
          step3WrongFeedbackRow1: "Oops!\nTry again.\nThe bridge is planned to be 40 m 60 cm long.",
          step3WrongFeedbackRow2: "Oops!\nTry again.\n15 m 52 cm has been constructed.",
          step3CorrectFeedback: "Well done!\nYou have correctly identified the lengths given in the question.",
          step4WrongFeedback: "Oops!\nRead the question again. Check for words that indicate the math action.",
          step4CorrectFeedback: "Well done!\nThe phrase 'yet to be built' in the word problem indicated that the lengths should be subtracted.",
          step5CharacterText: "Step 3: Subtract the lengths.\n\nLet's subtract the centimetres first.",
          step5WrongFeedback: "Oops!\nTry again.\n\nSubtract 52 from 60 to get the length left in centimetres.",
          step5CorrectFeedback: "Well done!\n60 cm - 52 cm\n= 8 cm.",
          step5CtAfterGm: "Step 3: Subtract the lengths.\n60 cm - 52 cm\n= 8 cm.\n\nLet's subtract the lengths in metres.",
          step6WrongFeedback: "Oops!\nTry again.\n\nSubtract 15 m from 40 m to get the length left in metres.",
          step6CorrectFeedback: "Well done!\nThe length yet to be built is\n25 m 8 cm.",
          step6FinalCt: "Well Done!\nThe length yet to be built is 25 m 8 cm.\n\nLet's try another question.",
          step6FinalCtLast: "Well Done!\nThe length yet to be built is 25 m 8 cm.",
          resultLabel: "Remaining",
        },
        {
          statement: "A pipe is 22 m 35 cm long. 11 m 34 cm is removed. What is the remaining length?",
          itemName1: "Original length of the pipe",
          itemName2: "Length removed",
          kgLabel: "m",
          gmLabel: "cm",
          kgAns1: 22,
          gmAns1: 35,
          kgAns2: 11,
          gmAns2: 34,
          kgResult: 11,
          gmResult: 1,
          operation: "subtract",
          hintWord: "remaining",
          step3WrongFeedbackRow1: "Oops!\nTry again.\nThe pipe is 22 m 35 cm long.",
          step3WrongFeedbackRow2: "Oops!\nTry again.\n11 m 34 cm is removed from the pipe.",
          step3CorrectFeedback: "Well done!\nYou have correctly identified the lengths given in the question.",
          step4WrongFeedback: "Oops!\nRead the question again. Check for words that indicate the math action.",
          step4CorrectFeedback: "Well done!\nThe word 'remaining' in the word problem indicated that the lengths should be subtracted.",
          step5CharacterText: "Step 3: Subtract the lengths.\n\nLet's subtract the centimetres first.",
          step5WrongFeedback: "Oops!\nTry again.\n\nSubtract 34 from 35 to get the remaining length in centimetres.",
          step5CorrectFeedback: "Well done!\n35 cm - 34 cm\n= 1 cm.",
          step5CtAfterGm: "Step 3: Subtract the lengths.\n35 cm - 34 cm\n= 1 cm.\n\nLet's subtract the lengths in metres.",
          step6WrongFeedback: "Oops!\nTry again.\n\nSubtract 11 m from 22 m to get the remaining length in metres.",
          step6CorrectFeedback: "Well done!\nThe remaining length is\n11 m 1 cm.",
          step6FinalCt: "Well Done!\nThe remaining length of the pipe is 11 m 1 cm.\n\nLet's try another question.",
          step6FinalCtLast: "Well Done!\nThe remaining length of the pipe is 11 m 1 cm.",
          resultLabel: "Remaining",
        },
        {
          statement: "A scarf is 10 m 50 cm long. 4 m 5 cm is cut. What is the length now?",
          itemName1: "Original length of the scarf",
          itemName2: "Length cut off",
          kgLabel: "m",
          gmLabel: "cm",
          kgAns1: 10,
          gmAns1: 50,
          kgAns2: 4,
          gmAns2: 5,
          kgResult: 6,
          gmResult: 45,
          operation: "subtract",
          hintWord: "now",
          step3WrongFeedbackRow1: "Oops!\nTry again.\nThe scarf is 10 m 50 cm long.",
          step3WrongFeedbackRow2: "Oops!\nTry again.\n4 m 5 cm is cut off.",
          step3CorrectFeedback: "Well done!\nYou have correctly identified the lengths given in the question.",
          step4WrongFeedback: "Oops!\nRead the question again. Check for words that indicate the math action.",
          step4CorrectFeedback: "Well done!\nThe word 'now' in the word problem indicated that the lengths should be subtracted.",
          step5CharacterText: "Step 3: Subtract the lengths.\n\nLet's subtract the centimetres first.",
          step5WrongFeedback: "Oops!\nTry again.\n\nSubtract 5 from 50 to get the new length in centimetres.",
          step5CorrectFeedback: "Well done!\n50 cm - 5 cm\n= 45 cm.",
          step5CtAfterGm: "Step 3: Subtract the lengths.\n50 cm - 5 cm\n= 45 cm.\n\nLet's subtract the lengths in metres.",
          step6WrongFeedback: "Oops!\nTry again.\n\nSubtract 4 m from 10 m to get the new length in metres.",
          step6CorrectFeedback: "Well done!\nThe length now is\n6 m 45 cm.",
          step6FinalCt: "Well Done!\nThe length of the scarf now is 6 m 45 cm.\n\nLet's try another question.",
          step6FinalCtLast: "Well Done!\nThe length of the scarf now is 6 m 45 cm.",
          resultLabel: "Remaining",
        },
      ],
    },
  },
  id: {
    app: {
      common: {
        tapNextToContinue: "Ketuk » untuk melanjutkan.",
        tapNumpadToFill: "Ketuk numpad untuk mengisi kotak yang disorot dan Periksa.",
        tapNextToAddWeights: "Ketuk » untuk menambahkan panjang.",
        tapNextToAddKg: "Ketuk » untuk menambahkan panjang dalam meter.",
        tapNextForAnother: "Ketuk » untuk tantangan lain.",
        tapNextToSummarise: "Ketuk » untuk merangkum.",
        tapNextToSubtract: "Ketuk » untuk mengurangi panjang.",
        tapNextToSubtractKg: "Ketuk » untuk mengurangi panjang dalam meter.",
      },
      start: {
        heading: "Soal cerita tentang panjang",
        text: "Mari kita jelajahi cara menyelesaikan soal cerita tentang panjang.<br><br>Ketuk \"Mulai\" untuk memulai!",
        buttonText: "Mulai",
      },
      summary: {
        heading: "Soal cerita panjang",
        text: "Luar biasa! Sekarang kamu tahu cara menyelesaikan soal cerita tentang panjang.",
        buttonText: "Ulangi",
      },
      steps: {
        1: {
          characterText: "Hai!\nSaya Jammal.\nMari kita jelajahi cara menyelesaikan beberapa soal cerita tentang panjang.",
          characterImage: "normal.png",
        },
        2: {
          characterText: "Mari kita baca soal ceritanya.",
        },
        3: {
          characterText: "Langkah 1: Tuliskan panjang yang diberikan dalam soal cerita.",
        },
        4: {
          characterText: "Langkah 2: Pilih operasi matematika yang diperlukan untuk menyelesaikan soal cerita.",
        },
      },
      mcqOptions: {
        add: "TAMBAH",
        subtract: "KURANG",
      },
      operatorQuestion: "Haruskah kita <y>menambah</y> atau <y>mengurangi</y> panjang?\nPeriksa kata-kata dalam soal cerita yang menunjukkan penjumlahan atau pengurangan.",
      oops: "Ups!",
      tryAgain: "Coba lagi.",
      wellDone: "Bagus!",
      questions: [
        {
          statement: "Seutas tali panjangnya 5 m 40 cm dan tali lain panjangnya 3 m 25 cm. Berapa total panjang keduanya?",
          itemName1: "Panjang tali pertama",
          itemName2: "Panjang tali lainnya",
          kgLabel: "m",
          gmLabel: "cm",
          kgAns1: 5,
          gmAns1: 40,
          kgAns2: 3,
          gmAns2: 25,
          kgResult: 8,
          gmResult: 65,
          operation: "add",
          hintWord: "total",
          step3WrongFeedbackRow1: "Ups!\nCoba lagi.\nTali pertama panjangnya 5 m 40 cm.",
          step3WrongFeedbackRow2: "Ups!\nCoba lagi.\nTali lain panjangnya 3 m 25 cm.",
          step3CorrectFeedback: "Bagus!\nKamu telah mengidentifikasi panjang dalam soal dengan benar.",
          step4WrongFeedback: "Ups!\nBaca soalnya lagi. Periksa kata-kata yang menunjukkan operasi matematika.",
          step4CorrectFeedback: "Bagus!\nKata 'total' dalam soal cerita menunjukkan bahwa panjang harus ditambahkan.",
          step5CharacterText: "Langkah 3: Tambahkan panjang.\n\nMari tambahkan sentimeter terlebih dahulu.",
          step5WrongFeedback: "Ups!\nCoba lagi.\n\nTambahkan 40 dan 25 untuk mendapatkan total panjang dalam sentimeter.",
          step5CorrectFeedback: "Bagus!\n40 cm + 25 cm\n= 65 cm.",
          step5CtAfterGm: "Langkah 3: Tambahkan panjang.\n40 cm + 25 cm\n= 65 cm.\n\nMari tambahkan panjang dalam meter.",
          step6WrongFeedback: "Ups!\nCoba lagi.\n\nTambahkan 5 m dan 3 m untuk mendapatkan total panjang dalam meter.",
          step6CorrectFeedback: "Bagus!\nTotal panjangnya adalah\n8 m 65 cm.",
          step6FinalCt: "Bagus Sekali!\nTotal panjang kedua tali adalah 8 m 65 cm.\n\nMari coba soal lain.",
          step6FinalCtLast: "Bagus Sekali!\nTotal panjang kedua tali adalah 8 m 65 cm.",
          resultLabel: "Total",
        },
        {
          statement: "Sebuah pita berukuran 2 m 25 cm dan pita lain berukuran 4 m 50 cm. Tentukan total panjangnya.",
          itemName1: "Panjang pita pertama",
          itemName2: "Panjang pita lainnya",
          kgLabel: "m",
          gmLabel: "cm",
          kgAns1: 2,
          gmAns1: 25,
          kgAns2: 4,
          gmAns2: 50,
          kgResult: 6,
          gmResult: 75,
          operation: "add",
          hintWord: "total",
          step3WrongFeedbackRow1: "Ups!\nCoba lagi.\nPita pertama berukuran 2 m 25 cm.",
          step3WrongFeedbackRow2: "Ups!\nCoba lagi.\nPita lain berukuran 4 m 50 cm.",
          step3CorrectFeedback: "Bagus!\nKamu telah mengidentifikasi panjang dalam soal dengan benar.",
          step4WrongFeedback: "Ups!\nBaca soalnya lagi. Periksa kata-kata yang menunjukkan operasi matematika.",
          step4CorrectFeedback: "Bagus!\nKata 'total' dalam soal cerita menunjukkan bahwa panjang harus ditambahkan.",
          step5CharacterText: "Langkah 3: Tambahkan panjang.\n\nMari tambahkan sentimeter terlebih dahulu.",
          step5WrongFeedback: "Ups!\nCoba lagi.\n\nTambahkan 25 dan 50 untuk mendapatkan total panjang dalam sentimeter.",
          step5CorrectFeedback: "Bagus!\n25 cm + 50 cm\n= 75 cm.",
          step5CtAfterGm: "Langkah 3: Tambahkan panjang.\n25 cm + 50 cm\n= 75 cm.\n\nMari tambahkan panjang dalam meter.",
          step6WrongFeedback: "Ups!\nCoba lagi.\n\nTambahkan 2 m dan 4 m untuk mendapatkan total panjang dalam meter.",
          step6CorrectFeedback: "Bagus!\nTotal panjangnya adalah\n6 m 75 cm.",
          step6FinalCt: "Bagus Sekali!\nTotal panjang kedua pita adalah 6 m 75 cm.\n\nMari coba soal lain.",
          step6FinalCtLast: "Bagus Sekali!\nTotal panjang kedua pita adalah 6 m 75 cm.",
          resultLabel: "Total",
        },
        {
          statement: "Sebuah jalan panjangnya 12 m 60 cm dan bagian lain panjangnya 8 m 5 cm. Berapa total panjangnya?",
          itemName1: "Panjang bagian jalan pertama",
          itemName2: "Panjang bagian lainnya",
          kgLabel: "m",
          gmLabel: "cm",
          kgAns1: 12,
          gmAns1: 60,
          kgAns2: 8,
          gmAns2: 5,
          kgResult: 20,
          gmResult: 65,
          operation: "add",
          hintWord: "total",
          step3WrongFeedbackRow1: "Ups!\nCoba lagi.\nBagian jalan pertama panjangnya 12 m 60 cm.",
          step3WrongFeedbackRow2: "Ups!\nCoba lagi.\nBagian lain panjangnya 8 m 5 cm.",
          step3CorrectFeedback: "Bagus!\nKamu telah mengidentifikasi panjang dalam soal dengan benar.",
          step4WrongFeedback: "Ups!\nBaca soalnya lagi. Periksa kata-kata yang menunjukkan operasi matematika.",
          step4CorrectFeedback: "Bagus!\nKata 'total' dalam soal cerita menunjukkan bahwa panjang harus ditambahkan.",
          step5CharacterText: "Langkah 3: Tambahkan panjang.\n\nMari tambahkan sentimeter terlebih dahulu.",
          step5WrongFeedback: "Ups!\nCoba lagi.\n\nTambahkan 60 dan 5 untuk mendapatkan total panjang dalam sentimeter.",
          step5CorrectFeedback: "Bagus!\n60 cm + 5 cm\n= 65 cm.",
          step5CtAfterGm: "Langkah 3: Tambahkan panjang.\n60 cm + 5 cm\n= 65 cm.\n\nMari tambahkan panjang dalam meter.",
          step6WrongFeedback: "Ups!\nCoba lagi.\n\nTambahkan 12 m dan 8 m untuk mendapatkan total panjang dalam meter.",
          step6CorrectFeedback: "Bagus!\nTotal panjangnya adalah\n20 m 65 cm.",
          step6FinalCt: "Bagus Sekali!\nTotal panjang jalan adalah 20 m 65 cm.\n\nMari coba soal lain.",
          step6FinalCtLast: "Bagus Sekali!\nTotal panjang jalan adalah 20 m 65 cm.",
          resultLabel: "Total",
        },
        {
          statement: "Sepotong kain panjangnya 6 m 35 cm dan potongan lain panjangnya 3 m. Berapa gabungan panjangnya?",
          itemName1: "Panjang potongan kain pertama",
          itemName2: "Panjang potongan kain lainnya",
          kgLabel: "m",
          gmLabel: "cm",
          kgAns1: 6,
          gmAns1: 35,
          kgAns2: 3,
          gmAns2: 0,
          kgResult: 9,
          gmResult: 35,
          operation: "add",
          hintWord: "gabungan",
          step3WrongFeedbackRow1: "Ups!\nCoba lagi.\nPotongan pertama panjangnya 6 m 35 cm.",
          step3WrongFeedbackRow2: "Ups!\nCoba lagi.\nPotongan lain panjangnya 3 m.",
          step3CorrectFeedback: "Bagus!\nKamu telah mengidentifikasi panjang dalam soal dengan benar.",
          step4WrongFeedback: "Ups!\nBaca soalnya lagi. Periksa kata-kata yang menunjukkan operasi matematika.",
          step4CorrectFeedback: "Bagus!\nKata 'gabungan' dalam soal cerita menunjukkan bahwa panjang harus ditambahkan.",
          step5CharacterText: "Langkah 3: Tambahkan panjang.\n\nMari tambahkan sentimeter terlebih dahulu.",
          step5WrongFeedback: "Ups!\nCoba lagi.\n\nTambahkan 35 dan 0 untuk mendapatkan total panjang dalam sentimeter.",
          step5CorrectFeedback: "Bagus!\n35 cm + 0 cm\n= 35 cm.",
          step5CtAfterGm: "Langkah 3: Tambahkan panjang.\n35 cm + 0 cm\n= 35 cm.\n\nMari tambahkan panjang dalam meter.",
          step6WrongFeedback: "Ups!\nCoba lagi.\n\nTambahkan 6 m dan 3 m untuk mendapatkan total panjang dalam meter.",
          step6CorrectFeedback: "Bagus!\nGabungan panjangnya adalah\n9 m 35 cm.",
          step6FinalCt: "Bagus Sekali!\nGabungan panjang potongan kain adalah 9 m 35 cm.\n\nMari coba soal lain.",
          step6FinalCtLast: "Bagus Sekali!\nGabungan panjang potongan kain adalah 9 m 35 cm.",
          resultLabel: "Total",
        },
        {
          statement: "Seutas kawat panjangnya 9 m 20 cm dan kawat lain panjangnya 7 m 75 cm. Tentukan total panjangnya.",
          itemName1: "Panjang kawat pertama",
          itemName2: "Panjang kawat lainnya",
          kgLabel: "m",
          gmLabel: "cm",
          kgAns1: 9,
          gmAns1: 20,
          kgAns2: 7,
          gmAns2: 75,
          kgResult: 16,
          gmResult: 95,
          operation: "add",
          hintWord: "total",
          step3WrongFeedbackRow1: "Ups!\nCoba lagi.\nKawat pertama panjangnya 9 m 20 cm.",
          step3WrongFeedbackRow2: "Ups!\nCoba lagi.\nKawat lain panjangnya 7 m 75 cm.",
          step3CorrectFeedback: "Bagus!\nKamu telah mengidentifikasi panjang dalam soal dengan benar.",
          step4WrongFeedback: "Ups!\nBaca soalnya lagi. Periksa kata-kata yang menunjukkan operasi matematika.",
          step4CorrectFeedback: "Bagus!\nKata 'total' dalam soal cerita menunjukkan bahwa panjang harus ditambahkan.",
          step5CharacterText: "Langkah 3: Tambahkan panjang.\n\nMari tambahkan sentimeter terlebih dahulu.",
          step5WrongFeedback: "Ups!\nCoba lagi.\n\nTambahkan 20 dan 75 untuk mendapatkan total panjang dalam sentimeter.",
          step5CorrectFeedback: "Bagus!\n20 cm + 75 cm\n= 95 cm.",
          step5CtAfterGm: "Langkah 3: Tambahkan panjang.\n20 cm + 75 cm\n= 95 cm.\n\nMari tambahkan panjang dalam meter.",
          step6WrongFeedback: "Ups!\nCoba lagi.\n\nTambahkan 9 m dan 7 m untuk mendapatkan total panjang dalam meter.",
          step6CorrectFeedback: "Bagus!\nTotal panjangnya adalah\n16 m 95 cm.",
          step6FinalCt: "Bagus Sekali!\nTotal panjang kedua kawat adalah 16 m 95 cm.\n\nMari coba soal lain.",
          step6FinalCtLast: "Bagus Sekali!\nTotal panjang kedua kawat adalah 16 m 95 cm.",
          resultLabel: "Total",
        },
        {
          statement: "Sebuah tangga panjangnya 20 m 50 cm. 8 m 36 cm rusak. Berapa panjang tangga yang masih layak dipakai?",
          itemName1: "Panjang penuh tangga",
          itemName2: "Panjang bagian yang rusak",
          kgLabel: "m",
          gmLabel: "cm",
          kgAns1: 20,
          gmAns1: 50,
          kgAns2: 8,
          gmAns2: 36,
          kgResult: 12,
          gmResult: 14,
          operation: "subtract",
          hintWord: "layak",
          step3WrongFeedbackRow1: "Ups!\nCoba lagi.\nTangga panjangnya 20 m 50 cm.",
          step3WrongFeedbackRow2: "Ups!\nCoba lagi.\n8 m 36 cm tangga rusak.",
          step3CorrectFeedback: "Bagus!\nKamu telah mengidentifikasi panjang dalam soal dengan benar.",
          step4WrongFeedback: "Ups!\nBaca soalnya lagi. Periksa kata-kata yang menunjukkan operasi matematika.",
          step4CorrectFeedback: "Bagus!\nMencari panjang yang 'layak dipakai' berarti mengurangi bagian rusak dari keseluruhan.",
          step5CharacterText: "Langkah 3: Kurangi panjang.\n\nMari kurangi sentimeter terlebih dahulu.",
          step5WrongFeedback: "Ups!\nCoba lagi.\n\nKurangi 36 dari 50 untuk mendapatkan panjang dalam sentimeter.",
          step5CorrectFeedback: "Bagus!\n50 cm - 36 cm\n= 14 cm.",
          step5CtAfterGm: "Langkah 3: Kurangi panjang.\n50 cm - 36 cm\n= 14 cm.\n\nMari kurangi panjang dalam meter.",
          step6WrongFeedback: "Ups!\nCoba lagi.\n\nKurangi 8 m dari 20 m untuk mendapatkan panjang dalam meter.",
          step6CorrectFeedback: "Bagus!\nPanjang yang layak dipakai adalah\n12 m 14 cm.",
          step6FinalCt: "Bagus Sekali!\nPanjang tangga yang layak dipakai adalah 12 m 14 cm.\n\nMari coba soal lain.",
          step6FinalCtLast: "Bagus Sekali!\nPanjang tangga yang layak dipakai adalah 12 m 14 cm.",
          resultLabel: "Layak pakai",
        },
        {
          statement: "Sebuah pita panjangnya 13 m 90 cm. 7 m 45 cm telah terpakai. Berapa sisa pita?",
          itemName1: "Panjang penuh pita",
          itemName2: "Panjang yang terpakai",
          kgLabel: "m",
          gmLabel: "cm",
          kgAns1: 13,
          gmAns1: 90,
          kgAns2: 7,
          gmAns2: 45,
          kgResult: 6,
          gmResult: 45,
          operation: "subtract",
          hintWord: "sisa",
          step3WrongFeedbackRow1: "Ups!\nCoba lagi.\nPita panjangnya 13 m 90 cm.",
          step3WrongFeedbackRow2: "Ups!\nCoba lagi.\n7 m 45 cm pita telah terpakai.",
          step3CorrectFeedback: "Bagus!\nKamu telah mengidentifikasi panjang dalam soal dengan benar.",
          step4WrongFeedback: "Ups!\nBaca soalnya lagi. Periksa kata-kata yang menunjukkan operasi matematika.",
          step4CorrectFeedback: "Bagus!\nKata 'sisa' dalam soal cerita menunjukkan bahwa panjang harus dikurangkan.",
          step5CharacterText: "Langkah 3: Kurangi panjang.\n\nMari kurangi sentimeter terlebih dahulu.",
          step5WrongFeedback: "Ups!\nCoba lagi.\n\nKurangi 45 dari 90 untuk mendapatkan sisa panjang dalam sentimeter.",
          step5CorrectFeedback: "Bagus!\n90 cm - 45 cm\n= 45 cm.",
          step5CtAfterGm: "Langkah 3: Kurangi panjang.\n90 cm - 45 cm\n= 45 cm.\n\nMari kurangi panjang dalam meter.",
          step6WrongFeedback: "Ups!\nCoba lagi.\n\nKurangi 7 m dari 13 m untuk mendapatkan sisa panjang dalam meter.",
          step6CorrectFeedback: "Bagus!\nSisa pita adalah\n6 m 45 cm.",
          step6FinalCt: "Bagus Sekali!\nSisa pita adalah 6 m 45 cm.\n\nMari coba soal lain.",
          step6FinalCtLast: "Bagus Sekali!\nSisa pita adalah 6 m 45 cm.",
          resultLabel: "Sisa",
        },
        {
          statement: "Sebuah jembatan direncanakan 40 m 60 cm. 15 m 52 cm sudah dibangun. Berapa panjang yang belum dibangun?",
          itemName1: "Panjang rencana jembatan",
          itemName2: "Panjang yang sudah dibangun",
          kgLabel: "m",
          gmLabel: "cm",
          kgAns1: 40,
          gmAns1: 60,
          kgAns2: 15,
          gmAns2: 52,
          kgResult: 25,
          gmResult: 8,
          operation: "subtract",
          hintWord: "belum",
          step3WrongFeedbackRow1: "Ups!\nCoba lagi.\nJembatan direncanakan sepanjang 40 m 60 cm.",
          step3WrongFeedbackRow2: "Ups!\nCoba lagi.\n15 m 52 cm sudah dibangun.",
          step3CorrectFeedback: "Bagus!\nKamu telah mengidentifikasi panjang dalam soal dengan benar.",
          step4WrongFeedback: "Ups!\nBaca soalnya lagi. Periksa kata-kata yang menunjukkan operasi matematika.",
          step4CorrectFeedback: "Bagus!\nFrasa 'belum dibangun' dalam soal cerita menunjukkan bahwa panjang harus dikurangkan.",
          step5CharacterText: "Langkah 3: Kurangi panjang.\n\nMari kurangi sentimeter terlebih dahulu.",
          step5WrongFeedback: "Ups!\nCoba lagi.\n\nKurangi 52 dari 60 untuk mendapatkan sisa panjang dalam sentimeter.",
          step5CorrectFeedback: "Bagus!\n60 cm - 52 cm\n= 8 cm.",
          step5CtAfterGm: "Langkah 3: Kurangi panjang.\n60 cm - 52 cm\n= 8 cm.\n\nMari kurangi panjang dalam meter.",
          step6WrongFeedback: "Ups!\nCoba lagi.\n\nKurangi 15 m dari 40 m untuk mendapatkan sisa panjang dalam meter.",
          step6CorrectFeedback: "Bagus!\nPanjang yang belum dibangun adalah\n25 m 8 cm.",
          step6FinalCt: "Bagus Sekali!\nPanjang yang belum dibangun adalah 25 m 8 cm.\n\nMari coba soal lain.",
          step6FinalCtLast: "Bagus Sekali!\nPanjang yang belum dibangun adalah 25 m 8 cm.",
          resultLabel: "Sisa",
        },
        {
          statement: "Sebuah pipa panjangnya 22 m 35 cm. 11 m 34 cm dipotong. Berapa sisa panjang pipa?",
          itemName1: "Panjang awal pipa",
          itemName2: "Panjang yang dipotong",
          kgLabel: "m",
          gmLabel: "cm",
          kgAns1: 22,
          gmAns1: 35,
          kgAns2: 11,
          gmAns2: 34,
          kgResult: 11,
          gmResult: 1,
          operation: "subtract",
          hintWord: "sisa",
          step3WrongFeedbackRow1: "Ups!\nCoba lagi.\nPipa panjangnya 22 m 35 cm.",
          step3WrongFeedbackRow2: "Ups!\nCoba lagi.\n11 m 34 cm dipotong dari pipa.",
          step3CorrectFeedback: "Bagus!\nKamu telah mengidentifikasi panjang dalam soal dengan benar.",
          step4WrongFeedback: "Ups!\nBaca soalnya lagi. Periksa kata-kata yang menunjukkan operasi matematika.",
          step4CorrectFeedback: "Bagus!\nKata 'sisa' dalam soal cerita menunjukkan bahwa panjang harus dikurangkan.",
          step5CharacterText: "Langkah 3: Kurangi panjang.\n\nMari kurangi sentimeter terlebih dahulu.",
          step5WrongFeedback: "Ups!\nCoba lagi.\n\nKurangi 34 dari 35 untuk mendapatkan sisa panjang dalam sentimeter.",
          step5CorrectFeedback: "Bagus!\n35 cm - 34 cm\n= 1 cm.",
          step5CtAfterGm: "Langkah 3: Kurangi panjang.\n35 cm - 34 cm\n= 1 cm.\n\nMari kurangi panjang dalam meter.",
          step6WrongFeedback: "Ups!\nCoba lagi.\n\nKurangi 11 m dari 22 m untuk mendapatkan sisa panjang dalam meter.",
          step6CorrectFeedback: "Bagus!\nSisa panjang pipa adalah\n11 m 1 cm.",
          step6FinalCt: "Bagus Sekali!\nSisa panjang pipa adalah 11 m 1 cm.\n\nMari coba soal lain.",
          step6FinalCtLast: "Bagus Sekali!\nSisa panjang pipa adalah 11 m 1 cm.",
          resultLabel: "Sisa",
        },
        {
          statement: "Sebuah syal panjangnya 10 m 50 cm. 4 m 5 cm dipotong. Berapa panjangnya sekarang?",
          itemName1: "Panjang awal syal",
          itemName2: "Panjang yang dipotong",
          kgLabel: "m",
          gmLabel: "cm",
          kgAns1: 10,
          gmAns1: 50,
          kgAns2: 4,
          gmAns2: 5,
          kgResult: 6,
          gmResult: 45,
          operation: "subtract",
          hintWord: "sekarang",
          step3WrongFeedbackRow1: "Ups!\nCoba lagi.\nSyal panjangnya 10 m 50 cm.",
          step3WrongFeedbackRow2: "Ups!\nCoba lagi.\n4 m 5 cm dipotong.",
          step3CorrectFeedback: "Bagus!\nKamu telah mengidentifikasi panjang dalam soal dengan benar.",
          step4WrongFeedback: "Ups!\nBaca soalnya lagi. Periksa kata-kata yang menunjukkan operasi matematika.",
          step4CorrectFeedback: "Bagus!\nKata 'sekarang' dalam soal cerita menunjukkan bahwa panjang harus dikurangkan.",
          step5CharacterText: "Langkah 3: Kurangi panjang.\n\nMari kurangi sentimeter terlebih dahulu.",
          step5WrongFeedback: "Ups!\nCoba lagi.\n\nKurangi 5 dari 50 untuk mendapatkan panjang baru dalam sentimeter.",
          step5CorrectFeedback: "Bagus!\n50 cm - 5 cm\n= 45 cm.",
          step5CtAfterGm: "Langkah 3: Kurangi panjang.\n50 cm - 5 cm\n= 45 cm.\n\nMari kurangi panjang dalam meter.",
          step6WrongFeedback: "Ups!\nCoba lagi.\n\nKurangi 4 m dari 10 m untuk mendapatkan panjang baru dalam meter.",
          step6CorrectFeedback: "Bagus!\nPanjang syal sekarang adalah\n6 m 45 cm.",
          step6FinalCt: "Bagus Sekali!\nPanjang syal sekarang adalah 6 m 45 cm.\n\nMari coba soal lain.",
          step6FinalCtLast: "Bagus Sekali!\nPanjang syal sekarang adalah 6 m 45 cm.",
          resultLabel: "Sisa",
        },
      ],
    },
  },
};

const APP_DATA = DATA[current_language].app;
const decimalSymbol = decimal[current_language];
