const LOOK_ALIKE_OBJECTS = [
  {
    id: "doll1",
    type: "doll",
    src: "assets/doll1.png",
    left: "20%",
    top: "23%",
    width: "12vw",
    scale: 0.6,
    rotateY: 180,
    dockLeft: "20%",
    dockTop: "49%",
    rowLeft: "24%",
    rowTop: "51%",
    stackLeft: "70%",
    stackTop: "59%",
  },
  {
    id: "doll2",
    type: "doll",
    src: "assets/doll2.png",
    left: "10%",
    top: "68%",
    width: "12vw",
    scale: 1,
    rotateY: 0,
    dockLeft: "34%",
    dockTop: "49%",
    rowLeft: "39%",
    rowTop: "51%",
    stackLeft: "70%",
    stackTop: "59%",
  },
  {
    id: "doll3",
    type: "doll",
    src: "assets/doll3.png",
    left: "59%",
    top: "60%",
    width: "12vw",
    scale: 1.4,
    rotateY: 180,
    dockLeft: "48%",
    dockTop: "49%",
    rowLeft: "56%",
    rowTop: "51%",
    stackLeft: "70%",
    stackTop: "59%",
  },
  {
    id: "doll4",
    type: "doll",
    src: "assets/doll4.png",
    left: "91%",
    top: "69%",
    width: "12vw",
    scale: 0.6,
    rotateY: 0,
    dockLeft: "62%",
    dockTop: "49%",
    rowLeft: "73%",
    rowTop: "51%",
    stackLeft: "70%",
    stackTop: "59%",
  },
  {
    id: "robo",
    type: "other",
    src: "assets/robo.png",
    left: "38%",
    top: "20%",
    width: "12vw",
    scale: 0.9,
    rotateY: 0,
    dockLeft: "17%",
    dockTop: "78%",
    gridLeft: "15%",
    gridTop: "41%",
    stackLeft: "28%",
    stackTop: "59%",
  },
  {
    id: "car",
    type: "other",
    src: "assets/car.png",
    left: "83%",
    top: "21%",
    width: "12vw",
    scale: 1,
    rotateY: 0,
    dockLeft: "36%",
    dockTop: "78%",
    gridLeft: "39%",
    gridTop: "41%",
    stackLeft: "28%",
    stackTop: "59%",
  },
  {
    id: "dino",
    type: "other",
    src: "assets/dino.png",
    left: "35%",
    top: "70%",
    width: "12vw",
    scale: 1,
    rotateY: 0,
    dockLeft: "26%",
    dockTop: "84%",
    gridLeft: "15%",
    gridTop: "76%",
    stackLeft: "28%",
    stackTop: "59%",
  },
  {
    id: "teddy",
    type: "other",
    src: "assets/teddy.png",
    left: "79%",
    top: "66%",
    width: "12vw",
    scale: 1,
    rotateY: 0,
    dockLeft: "45%",
    dockTop: "84%",
    gridLeft: "39%",
    gridTop: "76%",
    stackLeft: "28%",
    stackTop: "59%",
  },
];

const VEHICLE_OBJECTS = [
  {
    id: "car1",
    type: "car",
    src: "assets/car1.png",
    left: "17%",
    top: "33%",
    width: "24vw",
    scale: 1.2,
    rotateY: 0,
    rotateZ: 0,
    rowLeft: "20%",
    rowTop: "55%",
    stackLeft: "50%",
    stackTop: "56%",
  },
  {
    id: "car2",
    type: "car",
    src: "assets/car2.png",
    left: "66%",
    top: "35%",
    width: "24vw",
    scale: 1,
    rotateY: 180,
    rotateZ: 0,
    rowLeft: "40%",
    rowTop: "55%",
    stackLeft: "50%",
    stackTop: "56%",
  },
  {
    id: "car3",
    type: "car",
    src: "assets/car3.png",
    left: "40%",
    top: "70%",
    width: "24vw",
    scale: 0.8,
    rotateY: 0,
    rotateZ: -90,
    rowLeft: "60%",
    rowTop: "55%",
    stackLeft: "50%",
    stackTop: "56%",
  },
  {
    id: "car4",
    type: "car",
    src: "assets/car4.png",
    left: "90%",
    top: "66%",
    width: "24vw",
    scale: 0.8,
    rotateY: 180,
    rotateZ: -20,
    rowLeft: "80%",
    rowTop: "55%",
    stackLeft: "50%",
    stackTop: "56%",
  },
  {
    id: "train",
    type: "other",
    src: "assets/train.png",
    left: "43%",
    top: "15%",
    width: "24vw",
    scale: 1,
    rotateY: 0,
    rotateZ: 0,
    exitLeft: "-15%",
    exitTop: "26%",
  },
  {
    id: "heli",
    type: "other",
    src: "assets/heli.png",
    left: "85%",
    top: "24%",
    width: "24vw",
    scale: 1,
    rotateY: 0,
    rotateZ: 0,
    exitLeft: "115%",
    exitTop: "24%",
  },
  {
    id: "bus",
    type: "other",
    src: "assets/bus.png",
    left: "17%",
    top: "72%",
    width: "24vw",
    scale: 1,
    rotateY: 0,
    rotateZ: 0,
    exitLeft: "-15%",
    exitTop: "76%",
  },
  {
    id: "bike",
    type: "other",
    src: "assets/bike.png",
    left: "64%",
    top: "72%",
    width: "24vw",
    scale: 1,
    rotateY: 0,
    rotateZ: 0,
    exitLeft: "115%",
    exitTop: "76%",
  },
];

const CIRCLE_OBJECTS = [
  {
    id: "circle1",
    type: "circle",
    src: "assets/circle1.png",
    left: "17%",
    top: "33%",
    width: "18vw",
    scale: 1.3,
    rotateY: 0,
    rotateZ: 0,
    rowLeft: "20%",
    rowTop: "55%",
    stackLeft: "50%",
    stackTop: "56%",
  },
  {
    id: "circle2",
    type: "circle",
    src: "assets/circle2.png",
    left: "62%",
    top: "35%",
    width: "18vw",
    scale: 1,
    rotateY: 0,
    rotateZ: 0,
    rowLeft: "40%",
    rowTop: "55%",
    stackLeft: "50%",
    stackTop: "56%",
  },
  {
    id: "circle3",
    type: "circle",
    src: "assets/circle3.png",
    left: "10%",
    top: "80%",
    width: "18vw",
    scale: 0.9,
    rotateY: 0,
    rotateZ: 0,
    rowLeft: "60%",
    rowTop: "55%",
    stackLeft: "50%",
    stackTop: "56%",
  },
  {
    id: "circle4",
    type: "circle",
    src: "assets/circle4.png",
    left: "88%",
    top: "66%",
    width: "18vw",
    scale: 0.8,
    rotateY: 0,
    rotateZ: 0,
    rowLeft: "80%",
    rowTop: "55%",
    stackLeft: "50%",
    stackTop: "56%",
  },
  {
    id: "balloon",
    type: "other",
    src: "assets/balloon.png",
    left: "40%",
    top: "32%",
    width: "18vw",
    scale: 1,
    rotateY: 0,
    rotateZ: 0,
    exitLeft: "-15%",
    exitTop: "26%",
  },
  {
    id: "racquet",
    type: "other",
    src: "assets/racquet.png",
    left: "82%",
    top: "24%",
    width: "22vw",
    scale: 1,
    rotateY: 0,
    rotateZ: 0,
    exitLeft: "115%",
    exitTop: "24%",
  },
  {
    id: "umbrella",
    type: "other",
    src: "assets/umbrella.png",
    left: "33%",
    top: "72%",
    width: "12vw",
    scale: 1,
    rotateY: 0,
    rotateZ: 0,
    exitLeft: "-15%",
    exitTop: "76%",
  },
  {
    id: "tv",
    type: "other",
    src: "assets/tv.png",
    left: "54%",
    top: "82%",
    width: "18vw",
    scale: 1,
    rotateY: 0,
    rotateZ: 0,
    exitLeft: "115%",
    exitTop: "76%",
  },
];

const DATA = {
  en: {
    app: {
      start: {
        heading: "Look-alikes",
        text: "Let's see if you can spot things that look alike<br>from this group of objects, and then<br>explore what makes them feel this way...",
        buttonText: "START",
      },
      final: {
        heading: "Similar Objects",
        text: "",
        buttonText: "Start Over",
        table: {
          headers: ["Objects", "Why", "Fit<br><span>(When enlarged)</span>", "What we call"],
          rows: [
            ["Look alike", "Same shape", "Fit perfectly", "Similar objects"],
            ["Look different", "Different shape", "Don't fit", "Not similar objects"],
          ],
        },
      },
      labels: {},
      steps: {
        1: {
          questionText: "Yay! Keen eye! What makes all these look alike?",
          questionTextCompare: "What makes all these look alike?",
          navText: "Tap the look alike objects",
          navTextCompare: "Tap 'Compare'",
          navTextLineUp: "Tap any object to line them up",
          navTextOtherCompare: "Tap the other objects to compare them",
          navTextLookAlikeShapes:
            "Tap the look alike shapes to see what we call them.",
          navTextOtherShapes: "Tap the other shapes to see what we call them.",
          navTextSummarise: "Tap \u00bb to summarise.",
          compareButton: "Compare",
          sameShapeLine1: "They all have the same shape!!!",
          sameShapeLine2: "They fit perfectly into one another!",
          differentShapeLine1: "These have different shapes",
          differentShapeLine2: "These didn't fit into one another",
          similarObjectsTitle: "SIMILAR OBJECTS",
          similarBoxLine1: "In Math, such shapes",
          similarBoxLine2: "or objects are called",
          similarBoxWord: "SIMILAR",
          nonSimilarBoxWord: "NOT SIMILAR",
          objects: LOOK_ALIKE_OBJECTS,
        },
        2: {
          questionText:
            "<span class='question-similar'>Similar</span> and <span class='question-not-similar'>Not Similar</span> Objects",
          navText: "",
          navTextExplore: "Tap \u00bb to explore with a few more examples.",
          notSimilarObjectsTitle: "NOT SIMILAR OBJECTS",
          similarObjectsTitle: "SIMILAR OBJECTS",
          nonSimilarBoxWord: "NOT SIMILAR",
        },
        3: {
          questionText: "Spot <y>similar objects</y>",
          navText: "Tap the correct object",
          navTextCompare: "Tap the highlighted button",
          navTextDone: "Tap \u00bb to explore with one more example.",
          compareButton: "Do they fit perfectly?",
          fitText: "They fit perfectly into one another!",
          objects: VEHICLE_OBJECTS,
        },
        4: {
          questionText: "Spot <y>similar objects</y>",
          navText: "Tap the correct object",
          navTextCompare: "Tap the highlighted button",
          navTextDone: "Tap \u00bb to conclude.",
          compareButton: "Do they fit perfectly?",
          fitText: "They fit perfectly into one another!",
          targetType: "circle",
          objects: CIRCLE_OBJECTS,
        },
      },
    },
  },
  id: {
    app: {
      start: {
        heading: "Benda Mirip",
        text: "Mari lihat apakah kamu bisa menemukan benda yang mirip<br>dari kelompok benda ini, lalu<br>menjelajahi apa yang membuatnya terasa begitu...",
        buttonText: "MULAI",
      },
      final: {
        heading: "Objek Serupa",
        text: "",
        buttonText: "Ulangi",
        table: {
          headers: ["Objek", "Mengapa", "Pas<br><span>(Saat diperbesar)</span>", "Sebutan"],
          rows: [
            ["Terlihat mirip", "Bentuk sama", "Pas sempurna", "Objek serupa"],
            ["Terlihat berbeda", "Bentuk berbeda", "Tidak pas", "Objek tidak serupa"],
          ],
        },
      },
      labels: {},
      steps: {
        1: {
          questionText:
            "Hore! Mata yang jeli! Apa yang membuat semua ini terlihat mirip?",
          questionTextCompare: "Apa yang membuat semua ini terlihat mirip?",
          navText: "Ketuk benda-benda yang mirip",
          navTextCompare: "Ketuk 'Bandingkan'",
          navTextLineUp: "Ketuk objek apa saja untuk menyusunnya sejajar",
          navTextOtherCompare: "Ketuk objek lainnya untuk membandingkannya",
          navTextLookAlikeShapes:
            "Ketuk bentuk yang mirip untuk melihat sebutannya.",
          navTextOtherShapes: "Ketuk bentuk lainnya untuk melihat sebutannya.",
          navTextSummarise: "Ketuk \u00bb untuk merangkum.",
          compareButton: "Bandingkan",
          sameShapeLine1: "Semuanya memiliki bentuk yang sama!!!",
          sameShapeLine2: "Semuanya pas dengan sempurna satu sama lain!",
          differentShapeLine1: "Ini memiliki bentuk yang berbeda",
          differentShapeLine2: "Ini tidak pas satu sama lain",
          similarObjectsTitle: "OBJEK SERUPA",
          similarBoxLine1: "Dalam Matematika, bentuk",
          similarBoxLine2: "atau objek seperti ini disebut",
          similarBoxWord: "SERUPA",
          nonSimilarBoxWord: "TIDAK SERUPA",
          objects: LOOK_ALIKE_OBJECTS,
        },
        2: {
          questionText:
            "<span class='question-similar'>Objek Serupa</span> dan <span class='question-not-similar'>Tidak Serupa</span>",
          navText: "",
          navTextExplore:
            "Ketuk \u00bb untuk menjelajah dengan beberapa contoh lagi.",
          notSimilarObjectsTitle: "OBJEK TIDAK SERUPA",
          similarObjectsTitle: "OBJEK SERUPA",
          nonSimilarBoxWord: "TIDAK SERUPA",
        },
        3: {
          questionText: "Temukan <y>objek serupa</y>",
          navText: "Ketuk objek yang benar",
          navTextCompare: "Ketuk tombol yang disorot",
          navTextDone: "Ketuk \u00bb untuk menjelajah satu contoh lagi.",
          compareButton: "Apakah semuanya pas sempurna?",
          fitText: "Semuanya pas dengan sempurna satu sama lain!",
          objects: VEHICLE_OBJECTS,
        },
        4: {
          questionText: "Temukan <y>objek serupa</y>",
          navText: "Ketuk objek yang benar",
          navTextCompare: "Ketuk tombol yang disorot",
          navTextDone: "Ketuk \u00bb untuk menyimpulkan.",
          compareButton: "Apakah semuanya pas sempurna?",
          fitText: "Semuanya pas dengan sempurna satu sama lain!",
          targetType: "circle",
          objects: CIRCLE_OBJECTS,
        },
      },
    },
  },
};

const APP_DATA = DATA[current_language].app;
