const LOOK_ALIKE_OBJECTS = [
  {
    id: "doll1",
    type: "doll",
    src: "assets/doll1.png",
    left: "20%",
    top: "23%",
    width: "12vw",
    scale: 0.8,
    rotateY: 180,
    dockLeft: "20%",
    dockTop: "49%",
    rowLeft: "24%",
    rowTop: "51%",
    stackLeft: "70%",
    stackTop: "59%",
  },
  {
    id: "doll2",
    type: "doll",
    src: "assets/doll2.png",
    left: "10%",
    top: "68%",
    width: "12vw",
    scale: 1,
    rotateY: 0,
    dockLeft: "34%",
    dockTop: "49%",
    rowLeft: "39%",
    rowTop: "51%",
    stackLeft: "70%",
    stackTop: "59%",
  },
  {
    id: "doll3",
    type: "doll",
    src: "assets/doll3.png",
    left: "59%",
    top: "60%",
    width: "12vw",
    scale: 1.4,
    rotateY: 180,
    dockLeft: "48%",
    dockTop: "49%",
    rowLeft: "56%",
    rowTop: "51%",
    stackLeft: "70%",
    stackTop: "59%",
  },
  {
    id: "doll4",
    type: "doll",
    src: "assets/doll4.png",
    left: "91%",
    top: "69%",
    width: "12vw",
    scale: 0.6,
    rotateY: 0,
    dockLeft: "62%",
    dockTop: "49%",
    rowLeft: "73%",
    rowTop: "51%",
    stackLeft: "70%",
    stackTop: "59%",
  },
  {
    id: "robo",
    type: "other",
    src: "assets/robo.png",
    left: "38%",
    top: "20%",
    width: "12vw",
    scale: 0.9,
    rotateY: 0,
    dockLeft: "17%",
    dockTop: "78%",
    gridLeft: "15%",
    gridTop: "41%",
    stackLeft: "28%",
    stackTop: "59%",
  },
  {
    id: "car",
    type: "other",
    src: "assets/car.png",
    left: "83%",
    top: "21%",
    width: "12vw",
    scale: 1,
    rotateY: 0,
    dockLeft: "36%",
    dockTop: "78%",
    gridLeft: "39%",
    gridTop: "41%",
    stackLeft: "28%",
    stackTop: "59%",
  },
  {
    id: "dino",
    type: "other",
    src: "assets/dino.png",
    left: "35%",
    top: "70%",
    width: "12vw",
    scale: 1,
    rotateY: 0,
    dockLeft: "26%",
    dockTop: "84%",
    gridLeft: "15%",
    gridTop: "76%",
    stackLeft: "28%",
    stackTop: "59%",
  },
  {
    id: "teddy",
    type: "other",
    src: "assets/teddy.png",
    left: "79%",
    top: "66%",
    width: "12vw",
    scale: 1,
    rotateY: 0,
    dockLeft: "45%",
    dockTop: "84%",
    gridLeft: "39%",
    gridTop: "76%",
    stackLeft: "28%",
    stackTop: "59%",
  },
];

const DATA = {
  en: {
    app: {
      start: {
        heading: "Look-alikes",
        text: "Let's see if you can spot things that look alike<br>from this group of objects, and then<br>explore what makes them feel this way...",
        buttonText: "START",
      },
      final: {
        heading: "Look-alikes",
        text: "Great exploring!",
        buttonText: "START OVER",
      },
      labels: {},
      steps: {
        1: {
          questionText: "Yay! Keen eye! What makes all these look alike?",
          questionTextCompare: "What makes all these look alike?",
          navText: "Tap the look alike objects",
          navTextCompare: "Tap 'Compare'",
          navTextLineUp: "Tap any object to line them up",
          navTextOtherCompare: "Tap the other objects to compare them",
          navTextLookAlikeShapes:
            "Tap the look alike shapes to see what we call them.",
          navTextOtherShapes: "Tap the other shapes to see what we call them.",
          navTextSummarise: "Tap » to summarise.",
          compareButton: "Compare",
          sameShapeLine1: "They all have the same shape!!!",
          sameShapeLine2: "They fit perfectly into one another!",
          differentShapeLine1: "These have different shapes",
          differentShapeLine2: "These didn't fit into one another",
          similarObjectsTitle: "SIMILAR OBJECTS",
          similarBoxLine1: "In Math, such shapes",
          similarBoxLine2: "or objects are called",
          similarBoxWord: "SIMILAR",
          nonSimilarBoxWord: "NOT SIMILAR",
          objects: LOOK_ALIKE_OBJECTS,
        },
        2: {
          questionText:
            "<span class='question-similar'>Similar</span> and <span class='question-not-similar'>Not Similar</span> Objects",
          navText: "",
          navTextExplore: "Tap » to explore with a few more examples.",
          notSimilarObjectsTitle: "NOT SIMILAR OBJECTS",
          similarObjectsTitle: "SIMILAR OBJECTS",
          nonSimilarBoxWord: "NOT SIMILAR",
        },
      },
    },
  },
  id: {
    app: {
      start: {
        heading: "Benda Mirip",
        text: "Mari lihat apakah kamu bisa menemukan benda yang mirip<br>dari kelompok benda ini, lalu<br>menjelajahi apa yang membuatnya terasa begitu...",
        buttonText: "MULAI",
      },
      final: {
        heading: "Benda Mirip",
        text: "Hebat sekali menjelajahinya!",
        buttonText: "ULANGI",
      },
      labels: {},
      steps: {
        1: {
          questionText:
            "Hore! Mata yang jeli! Apa yang membuat semua ini terlihat mirip?",
          questionTextCompare: "Apa yang membuat semua ini terlihat mirip?",
          navText: "Ketuk benda-benda yang mirip",
          navTextCompare: "Ketuk 'Bandingkan'",
          navTextLineUp: "Ketuk objek apa saja untuk menyusunnya sejajar",
          navTextOtherCompare: "Ketuk objek lainnya untuk membandingkannya",
          navTextLookAlikeShapes:
            "Ketuk bentuk yang mirip untuk melihat sebutannya.",
          navTextOtherShapes: "Ketuk bentuk lainnya untuk melihat sebutannya.",
          navTextSummarise: "Ketuk » untuk merangkum.",
          compareButton: "Bandingkan",
          sameShapeLine1: "Semuanya memiliki bentuk yang sama!!!",
          sameShapeLine2: "Semuanya pas dengan sempurna satu sama lain!",
          differentShapeLine1: "Ini memiliki bentuk yang berbeda",
          differentShapeLine2: "Ini tidak pas satu sama lain",
          similarObjectsTitle: "OBJEK SERUPA",
          similarBoxLine1: "Dalam Matematika, bentuk",
          similarBoxLine2: "atau objek seperti ini disebut",
          similarBoxWord: "SERUPA",
          nonSimilarBoxWord: "TIDAK SERUPA",
          objects: LOOK_ALIKE_OBJECTS,
        },
        2: {
          questionText:
            "<span class='question-similar'>Objek Serupa</span> dan <span class='question-not-similar'>Tidak Serupa</span>",
          navText: "",
          navTextExplore:
            "Ketuk » untuk menjelajah dengan beberapa contoh lagi.",
          notSimilarObjectsTitle: "OBJEK TIDAK SERUPA",
          similarObjectsTitle: "OBJEK SERUPA",
          nonSimilarBoxWord: "TIDAK SERUPA",
        },
      },
    },
  },
};

const APP_DATA = DATA[current_language].app;
