const DATA = {
  en: {
    app: {
      dataset: [5, 3, 7, 6, 6, 9, 8, 6, 9, 8],
      sortedDataset: [3, 5, 6, 6, 6, 7, 8, 8, 9, 9],
      sortMapping: [1, 0, 5, 2, 3, 8, 6, 4, 9, 7],
      challenges: [
        {
          dataset: [5, 3, 7, 6, 6, 9, 8, 6, 9, 8],
          sortedDataset: [3, 5, 6, 6, 6, 7, 8, 8, 9, 9],
          sortMapping: [1, 0, 5, 2, 3, 8, 6, 4, 9, 7],
          middleCorrectOption: 1,
          middlePositions: [5, 6],
          medianAnswer: "6.5",
          texts: {},
        },
        {
          dataset: [7, 2, 1, 4, 5, 7, 7, 4, 3],
          sortedDataset: [1, 2, 3, 4, 4, 5, 7, 7, 7],
          sortMapping: [6, 1, 0, 3, 5, 7, 8, 4, 2],
          middleCorrectOption: 0,
          middlePositions: [5],
          medianAnswer: "4",
          texts: {
            questionText: "To find the median, first sort the new data set.",
            sortReadyNav: "Tap Step 1 to start sorting the data.",
            sortedQuestion: "Data set is sorted. Let's move ahead with the next step.",
            sortedNav: "Tap Step 2.",
            countQuestion: "Next step is to count the number of data values (<mi>n</mi>).",
            countNav: "Tap on each data value to count it.",
            countCompleteQuestion: "The data set has 9 values. Let's move ahead with the next step.",
            countCompleteNav: "Tap Step 3.",
            middleQuestion: "How to find the middle position for a data set having 9 values?",
            wrongMiddleQuestion: "Here <mi>n</mi> = 9, an odd number.<br>For an odd-sized data set, there is one middle value.",
            correctMiddleQuestion: "So, for <mi>n</mi> = 9, the middle position is:",
            simplifiedMiddleQuestion: "So, for <mi>n</mi> = 9, the middle position is: 5<sup>th</sup>",
            selectMiddleNav: "Tap on the value which is at position 5<sup>th</sup>.",
            foundBothQuestion: "You found the middle value at 5<sup>th</sup>. Let us move with the final step.",
            foundBothNav: "Tap on Step 4.",
            medianQuestion: "Find the median now.<br>What will be the median when there is one middle value?",
            medianNav: "Enter the correct median.",
            medianWrongQuestion: "That's wrong!<br>The median is the middle value itself.",
            medianWrongNav: "Try again! Enter the correct median.",
            medianCorrectQuestion: "That's right! The median is 4.",
            medianCorrectNav: "Tap \u00BB to finish.",
            medianAnswer: "4",
            simplifiedExpressions: [
              "((9+1)/2)<sup>th</sup> value",
              "(10/2)<sup>th</sup> value",
              "5<sup>th</sup> value",
            ],
          },
        },
      ],
      finalScreen: {
        heading: "Well Done!",
        text: "You successfully found the median of the given data sets<br>step-by-step.<br><br>Tap 'Start Over' to repeat again.",
        buttonText: "Start Over",
      },
      start: {
        heading: "Practice: Finding Median",
        text: "We practiced finding median of the data set by<br>eliminating pairs and reaching the middle<br>value.<br>Let us now practice finding median directly by<br>using the middle position formula.<br>Tap 'Start' to begin.",
        buttonText: "Start",
      },
      steps: {
        1: {
          questionText: "Put the steps of finding median in correct order.",
          navText: "Move the options at correct steps.",
          completeQuestion: "All the steps are in correct order.",
          completeNav: "Tap \u00BB to begin finding median of a data set.",
          stepLabels: ["Step 1", "Step 2", "Step 3", "Step 4"],
          initialOrder: ["middle", "median", "count", "sort"],
          correctOrder: ["sort", "count", "middle", "median"],
          options: {
            sort: "Sort the data",
            count: "Count&nbsp;<mi>n</mi>",
            middle: "Find middle position(s)",
            median: "Find Median",
          },
        },
        2: {
          questionText: "To find the median, the first most step is to sort the data.",
          navText: "",
          sortReadyNav: "Tap Step 1 to start sorting the data.",
          sortingQuestion: "",
          sortingNav: "",
          sortedQuestion: "Data set is sorted. Let's move ahead with the next step.",
          sortedNav: "Tap Step 2.",
          countQuestion: "Next step is to count the number of data values (<mi>n</mi>).",
          countNav: "Tap on each data value to count it.",
          countCompleteQuestion: "The data set have 10 values. Let's move ahead with the next step.",
          countCompleteNav: "Tap Step 3.",
          middleQuestion: "How to find the middle position for a data set having 10 values?",
          middleInitialNav: "",
          middleChoiceNav: "Tap the correct option.",
          wrongMiddleQuestion: "Here <mi>n</mi> = 10, an even number.<br>How do we find the middle value of even-sized data set?",
          correctMiddleQuestion: "So, for <mi>n</mi> = 10, the two middle positions are:",
          simplifiedMiddleQuestion: "So, for <mi>n</mi> = 10, the two middle positions are: 5<sup>th</sup> and 6<sup>th</sup>",
          selectMiddleNav: "Tap on the values which are at position 5<sup>th</sup> and 6<sup>th</sup>.",
          foundFirstQuestion: "You found the {position} position. Find the {nextPosition} position now.",
          foundFirstNav: "Tap on the value which at position {nextPosition}",
          foundBothQuestion: "You found the middle values at 5<sup>th</sup> and 6<sup>th</sup>. Let us move with the final step.",
          foundBothNav: "Tap on Step 4.",
          medianQuestion: "Find the median now.<br>What will be the median for when we have two middle values?",
          medianNav: "Enter the correct median.",
          medianWrongQuestion: "That's wrong!<br>We need to find the mean of the two middle values to find the median.",
          medianWrongNav: "Try again! Enter the correct median.",
          medianCorrectQuestion: "That's right! The median is 6.5.",
          medianCorrectNav: "Tap \u00BB for another challenge.",
          medianLabel: "Median:",
          medianAnswer: "6.5",
          clearLabel: "clear",
          smallest: "Smallest",
          largest: "Largest",
          countSymbol: "n",
          middlePositionTitle: "Middle position:",
          valueText: "value",
          nextValueText: "and the next value",
          middleOptions: [
            "((<mi>n</mi>+1)/2)<sup>th</sup> value",
            "(<mi>n</mi>/2)<sup>th</sup> and the next value",
          ],
          simplifiedExpressions: [
            "(10/2)<sup>th</sup> and the next value",
            "5<sup>th</sup> and the next value",
            "5<sup>th</sup> and 6<sup>th</sup> value",
          ],
          actionButtons: [
            "Step 1:<br>Sort the data",
            "Step 2:<br>Count&nbsp;<mi>n</mi>",
            "Step 3:<br>Find Middle Position(s)",
            "Step 4:<br>Find Median",
          ],
        },
      },
    },
  },
  id: {
    app: {
      dataset: [5, 3, 7, 6, 6, 9, 8, 6, 9, 8],
      sortedDataset: [3, 5, 6, 6, 6, 7, 8, 8, 9, 9],
      sortMapping: [1, 0, 5, 2, 3, 8, 6, 4, 9, 7],
      challenges: [
        {
          dataset: [5, 3, 7, 6, 6, 9, 8, 6, 9, 8],
          sortedDataset: [3, 5, 6, 6, 6, 7, 8, 8, 9, 9],
          sortMapping: [1, 0, 5, 2, 3, 8, 6, 4, 9, 7],
          middleCorrectOption: 1,
          middlePositions: [5, 6],
          medianAnswer: "6.5",
          texts: {},
        },
        {
          dataset: [7, 2, 1, 4, 5, 7, 7, 4, 3],
          sortedDataset: [1, 2, 3, 4, 4, 5, 7, 7, 7],
          sortMapping: [6, 1, 0, 3, 5, 7, 8, 4, 2],
          middleCorrectOption: 0,
          middlePositions: [5],
          medianAnswer: "4",
          texts: {
            questionText: "Untuk menemukan median, urutkan kumpulan data baru terlebih dahulu.",
            sortReadyNav: "Ketuk Langkah 1 untuk mulai mengurutkan data.",
            sortedQuestion: "Kumpulan data sudah terurut. Mari lanjut ke langkah berikutnya.",
            sortedNav: "Ketuk Langkah 2.",
            countQuestion: "Langkah berikutnya adalah menghitung banyaknya nilai data (<mi>n</mi>).",
            countNav: "Ketuk setiap nilai data untuk menghitungnya.",
            countCompleteQuestion: "Kumpulan data memiliki 9 nilai. Mari lanjut ke langkah berikutnya.",
            countCompleteNav: "Ketuk Langkah 3.",
            middleQuestion: "Bagaimana menemukan posisi tengah untuk kumpulan data yang memiliki 9 nilai?",
            wrongMiddleQuestion: "Di sini <mi>n</mi> = 9, sebuah bilangan ganjil.<br>Untuk kumpulan data berukuran ganjil, hanya ada satu nilai tengah.",
            correctMiddleQuestion: "Jadi, untuk <mi>n</mi> = 9, posisi tengahnya adalah:",
            simplifiedMiddleQuestion: "Jadi, untuk <mi>n</mi> = 9, posisi tengahnya adalah: 5<sup>th</sup>",
            selectMiddleNav: "Ketuk nilai yang berada pada posisi 5<sup>th</sup>.",
            foundBothQuestion: "Kamu menemukan nilai tengah pada posisi 5<sup>th</sup>. Mari lanjut ke langkah terakhir.",
            foundBothNav: "Ketuk Langkah 4.",
            medianQuestion: "Temukan mediannya sekarang.<br>Apa median ketika hanya ada satu nilai tengah?",
            medianNav: "Masukkan median yang benar.",
            medianWrongQuestion: "Itu salah!<br>Median adalah nilai tengah itu sendiri.",
            medianWrongNav: "Coba lagi! Masukkan median yang benar.",
            medianCorrectQuestion: "Benar! Mediannya adalah 4.",
            medianCorrectNav: "Ketuk \u00BB untuk selesai.",
            medianAnswer: "4",
            simplifiedExpressions: [
              "((9+1)/2)<sup>th</sup> nilai",
              "(10/2)<sup>th</sup> nilai",
              "5<sup>th</sup> nilai",
            ],
          },
        },
      ],
      finalScreen: {
        heading: "Bagus Sekali!",
        text: "Kamu berhasil menemukan median dari kumpulan data yang diberikan<br>langkah demi langkah.<br><br>Ketuk 'Mulai Lagi' untuk mengulang.",
        buttonText: "Mulai Lagi",
      },
      start: {
        heading: "Latihan: Menemukan Median",
        text: "Kita telah berlatih menemukan median dari kumpulan data<br>dengan menghilangkan pasangan dan mencapai nilai<br>tengah.<br>Sekarang mari berlatih menemukan median secara langsung<br>dengan menggunakan rumus posisi tengah.<br>Ketuk 'Mulai' untuk memulai.",
        buttonText: "Mulai",
      },
      steps: {
        1: {
          questionText: "Susun langkah-langkah menemukan median dalam urutan yang benar.",
          navText: "Pindahkan pilihan ke langkah yang benar.",
          completeQuestion: "Semua langkah sudah dalam urutan yang benar.",
          completeNav: "Ketuk \u00BB untuk mulai menemukan median dari kumpulan data.",
          stepLabels: ["Langkah 1", "Langkah 2", "Langkah 3", "Langkah 4"],
          initialOrder: ["middle", "median", "count", "sort"],
          correctOrder: ["sort", "count", "middle", "median"],
          options: {
            sort: "Urutkan data",
            count: "Hitung&nbsp;<mi>n</mi>",
            middle: "Temukan posisi tengah",
            median: "Temukan Median",
          },
        },
        2: {
          questionText: "Untuk menemukan median, langkah pertama adalah mengurutkan data.",
          navText: "",
          sortReadyNav: "Ketuk Langkah 1 untuk mulai mengurutkan data.",
          sortingQuestion: "",
          sortingNav: "",
          sortedQuestion: "Kumpulan data sudah terurut. Mari lanjut ke langkah berikutnya.",
          sortedNav: "Ketuk Langkah 2.",
          countQuestion: "Langkah berikutnya adalah menghitung banyaknya nilai data (<mi>n</mi>).",
          countNav: "Ketuk setiap nilai data untuk menghitungnya.",
          countCompleteQuestion: "Kumpulan data memiliki 10 nilai. Mari lanjut ke langkah berikutnya.",
          countCompleteNav: "Ketuk Langkah 3.",
          middleQuestion: "Bagaimana menemukan posisi tengah untuk kumpulan data yang memiliki 10 nilai?",
          middleInitialNav: "",
          middleChoiceNav: "Ketuk pilihan yang benar.",
          wrongMiddleQuestion: "Di sini <mi>n</mi> = 10, sebuah bilangan genap.<br>Bagaimana kita menemukan nilai tengah dari kumpulan data berukuran genap?",
          correctMiddleQuestion: "Jadi, untuk <mi>n</mi> = 10, dua posisi tengahnya adalah:",
          simplifiedMiddleQuestion: "Jadi, untuk <mi>n</mi> = 10, dua posisi tengahnya adalah: 5<sup>th</sup> dan 6<sup>th</sup>",
          selectMiddleNav: "Ketuk nilai yang berada pada posisi 5<sup>th</sup> dan 6<sup>th</sup>.",
          foundFirstQuestion: "Kamu menemukan posisi {position}. Sekarang temukan posisi {nextPosition}.",
          foundFirstNav: "Ketuk nilai yang berada pada posisi {nextPosition}",
          foundBothQuestion: "Kamu menemukan nilai tengah pada posisi 5<sup>th</sup> dan 6<sup>th</sup>. Mari lanjut ke langkah terakhir.",
          foundBothNav: "Ketuk Langkah 4.",
          medianQuestion: "Temukan mediannya sekarang.<br>Apa median ketika kita memiliki dua nilai tengah?",
          medianNav: "Masukkan median yang benar.",
          medianWrongQuestion: "Itu salah!<br>Kita perlu menemukan mean dari dua nilai tengah untuk menemukan median.",
          medianWrongNav: "Coba lagi! Masukkan median yang benar.",
          medianCorrectQuestion: "Benar! Mediannya adalah 6.5.",
          medianCorrectNav: "Ketuk \u00BB untuk tantangan lain.",
          medianLabel: "Median:",
          medianAnswer: "6.5",
          clearLabel: "hapus",
          smallest: "Terkecil",
          largest: "Terbesar",
          countSymbol: "n",
          middlePositionTitle: "Posisi tengah:",
          valueText: "nilai",
          nextValueText: "dan nilai berikutnya",
          middleOptions: [
            "((<mi>n</mi>+1)/2)<sup>th</sup> nilai",
            "(<mi>n</mi>/2)<sup>th</sup> dan nilai berikutnya",
          ],
          simplifiedExpressions: [
            "(10/2)<sup>th</sup> dan nilai berikutnya",
            "5<sup>th</sup> dan nilai berikutnya",
            "5<sup>th</sup> dan nilai 6<sup>th</sup>",
          ],
          actionButtons: [
            "Langkah 1:<br>Urutkan data",
            "Langkah 2:<br>Hitung&nbsp;<mi>n</mi>",
            "Langkah 3:<br>Temukan Posisi Tengah",
            "Langkah 4:<br>Temukan Median",
          ],
        },
      },
    },
  },
};

const APP_DATA = DATA[current_language].app;
