var scaleColumnsForBg = [
  { dotColor: "#e53935", labelHtml: "<span style=\"color:#e53935;font-weight:700\">No<br>chance</span>" },
  { dotColor: "#fb8c00", labelHtml: "<span style=\"color:#fb8c00;font-weight:700\">Low<br>chance</span>" },
  { dotColor: "#fdd835", labelHtml: "<span style=\"color:#fdd835;font-weight:700\">Equal<br>chance</span>" },
  { dotColor: "#29b6f6", labelHtml: "<span style=\"color:#29b6f6;font-weight:700\">High<br>chance</span>" },
  { dotColor: "#66bb6a", labelHtml: "<span style=\"color:#66bb6a;font-weight:700\">Sure<br>chance</span>" },
];

var scaleColumnsForBgId = [
  { dotColor: "#e53935", labelHtml: "<span style=\"color:#e53935;font-weight:700\">Tiada<br>peluang</span>" },
  { dotColor: "#fb8c00", labelHtml: "<span style=\"color:#fb8c00;font-weight:700\">Peluang<br>rendah</span>" },
  { dotColor: "#fdd835", labelHtml: "<span style=\"color:#fdd835;font-weight:700\">Peluang<br>sama</span>" },
  { dotColor: "#29b6f6", labelHtml: "<span style=\"color:#29b6f6;font-weight:700\">Peluang<br>tinggi</span>" },
  { dotColor: "#66bb6a", labelHtml: "<span style=\"color:#66bb6a;font-weight:700\">Peluang<br>pasti</span>" },
];

const DATA = {
  en: {
    scalePositions: [
      { label: "No\nchance", dotColor: "#e53935" },
      { label: "Low\nchance", dotColor: "#fb8c00" },
      { label: "Equal\nchance", dotColor: "#fdd835" },
      { label: "High\nchance", dotColor: "#29b6f6" },
      { label: "Sure\nchance", dotColor: "#66bb6a" },
    ],

    intro: {
      heading: "Filling the Chance Line",
      text: "We will see 5 different capsule machines.<br>Each machine has 4 tubes -<br>but different amounts of <red>RED</red> and <blue>BLUE</blue>.<br><br>Where on the chance line would you place each one?<br>Let\u2019s find out together.<br><br>Tap \u2018Start\u2019 to begin.",
      buttonText: "Start",
    },

    introStep1: {
      navText: "Tap \u00BB to see chance line.",
      image: "assets/machine.png",
      text: "This is the<br><y>capsule machine</y>.<br>It has 4 tubes with<br>capsules.",
    },
    introStep2: {
      navText: "Tap \u00BB to read how to fill the chance line.",
      text: "This is the <y>chance line</y>. It has 5 positions.",
    },
    introStep3: {
      navText: "Tap \u00BB to read how to fill the chance line.",
      headingText: "Event: Getting a <red>RED</red> capsule at random",
      text: "On top, we have defined our event.<br><br>For all machines, the event will remain the same.<br><br>We will find the chance of getting a <red>RED</red> capsule<br>from the machines.",
    },
    introStep4: {
      navText: "Tap \u00BB to see Machine 1.",
      text: "We will fill each position with a capsule machine!<br><br>For each machine, we\u2019ll try <b>10 serves</b>,<br>count how many come out <red>RED</red>,<br>then decide where the machine sits on the chance line.",
    },

    eventHeading: "Event: Getting a <red>RED</red> capsule at random",
    serveButtonText: "10 Serves",

    machines: [
      {
        image: "assets/machine.png",
        correctPosition: 1,
        initialText: "<b>Machine 1</b><br>4 <blue>BLUE</blue> and 0 <red>RED</red> tubes.<br><br>Let\u2019s try 10 serves and see<br>how many <red>RED</red> capsules we get!",
        afterServeText: "0 out of 10 serves are <red>RED</red>.<br><br>Every tube has <blue>BLUE</blue>. Every serve is <blue>BLUE</blue>!<br><br>This means that there is<br><sc1>no chance</sc1> of getting a RED capsule.",
        finalText: "<greenBox>The leftmost position represents<br><sc1>no chance</sc1> on the chance line.</greenBox>",
        serves: ["b","b","b","b","b","b","b","b","b","b"],
        navInitial: "Tap \u201810 Serves\u2019 to try this machine.",
        navAfterServe: "Tap the box to place Machine 1 on the line.",
        navAfterPlace: "Tap \u00BB to see Machine 2.",
      },
      {
        image: "assets/machine.png",
        correctPosition: 2,
        initialText: "<b>Machine 2</b><br>1 <red>RED</red> and 3 <blue>BLUE</blue> tubes.<br><br>Let\u2019s try 10 serves and see<br>how many <red>RED</red> capsules we get!",
        afterServeText: "2 out of 10 serves are <red>RED</red>.<br>Fewer <red>RED</red> tubes than <blue>BLUE</blue>. Only a few serves are <red>RED</red>.<br><br>This means there is <sc2>low chance</sc2> of getting a RED capsule.",
        finalText: "<greenBox>This position closer to <sc1>no chance</sc1> represents<br><sc2>low chance</sc2> on the chance line.</greenBox>",
        serves: ["b","r","b","b","b","b","r","b","b","b"],
        navInitial: "Tap \u201810 Serves\u2019 to try this machine.",
        navAfterServe: "Tap the box to place Machine 2 on the line.",
        navAfterPlace: "Tap \u00BB to see Machine 3.",
      },
      {
        image: "assets/machine.png",
        correctPosition: 3,
        initialText: "<b>Machine 3</b><br>2 <red>RED</red> and 2 <blue>BLUE</blue> tubes.<br><br>Let\u2019s try 10 serves and see<br>how many <red>RED</red> capsules we get!",
        afterServeText: "5 out of 10 serves are <red>RED</red>.<br>Equal <red>RED</red> and <blue>BLUE</blue>. Half the serves are <red>RED</red>. Half <blue>BLUE</blue>.<br><br>This means that there is <sc3>equal chance</sc3> of getting a <red>RED</red> or<br><blue>BLUE</blue> capsule.",
        finalText: "<greenBox>This position between <sc2>low chance</sc2> and <sc4>high chance</sc4><br>represents <sc3>equal chance</sc3> on the chance line.</greenBox>",
        serves: ["b","r","r","b","r","b","r","b","b","r"],
        navInitial: "Tap \u201810 Serves\u2019 to try this machine.",
        navAfterServe: "Tap the box to place Machine 3 on the line.",
        navAfterPlace: "Tap \u00BB to see Machine 4.",
      },
      {
        image: "assets/machine.png",
        correctPosition: 4,
        initialText: "<b>Machine 4</b><br>3 <red>RED</red> and 1 <blue>BLUE</blue> tubes.<br><br>Let\u2019s try 10 serves and see<br>how many <red>RED</red> capsules we get!",
        afterServeText: "8 out of 10 serves are <red>RED</red>.<br>More <red>RED</red> tubes than <blue>BLUE</blue>. Most serves are <red>RED</red>.<br><br>This means that there is a <sc4>high chance</sc4> of getting a RED capsule.",
        finalText: "<greenBox>This position closer to <sc5>sure chance</sc5> represents<br><sc4>high chance</sc4> on the chance line.</greenBox>",
        serves: ["r","r","r","b","r","r","r","r","b","r"],
        navInitial: "Tap \u201810 Serves\u2019 to try this machine.",
        navAfterServe: "Tap the box to place Machine 4 on the line.",
        navAfterPlace: "Tap \u00BB to see Machine 5.",
      },
      {
        image: "assets/machine.png",
        correctPosition: 5,
        initialText: "<b>Machine 5</b><br>4 <red>RED</red> and 0 <blue>BLUE</blue> tubes.<br><br>Let\u2019s try 10 serves and see<br>how many <red>RED</red> capsules we get!",
        afterServeText: "10 out of 10 serves are <red>RED</red>.<br>All <red>RED</red> tubes. All <red>RED</red> serves!<br><br>This means there is a <sc5>sure chance</sc5> of getting a RED capsule.",
        finalText: "<greenBox>The rightmost position represents<br><sc5>sure chance</sc5> on the chance line.</greenBox>",
        serves: ["r","r","r","r","r","r","r","r","r","r"],
        navInitial: "Tap \u201810 Serves\u2019 to try this machine.",
        navAfterServe: "Tap the box to place Machine 5 on the line.",
        navAfterPlace: "Tap \u00BB to see the complete chance line.",
      },
    ],

    machineWrongText: "Not here,\nTry again!",

    splash2: {
      heading: "The Chance Line \u2014 Filled!",
      scaleColumns: scaleColumnsForBg,
      visualImages: [
        "assets/machine.png",
        "assets/machine.png",
        "assets/machine.png",
        "assets/machine.png",
        "assets/machine.png",
      ],
      summaryHtml: "By changing what\u2019s inside the machine, we filled the entire <y>chance line</y>.<br>The more <red>RED</red> tubes inside, the <y>further right</y> the event sits on the line.",
      navText: "Tap \u00BB to see the key idea.",
    },

    fullscreen2: {
      heading: "Filling the Chance Line \u2013 Complete!",
      scaleColumns: scaleColumnsForBg,
      scaleText: "<y>Chance increases from left to right.</y>",
      boxedHtml: "<y>What Did We Discover?</y><br><y>Count</y> determines <y>chance</y>.<br><br>More <red>RED</red> \u2192 <y>higher chance</y> of getting <red>RED</red><br>Equal <red>RED</red> and <blue>BLUE</blue> \u2192 Equal chance of getting <red>RED</red><br>Fewer <red>RED</red> \u2192 <y>lower chance</y> of getting <red>RED</red><br><br>Now, it\u2019s your turn. Same rules, different machines.<br>The colors change \u2013 the chance line doesn\u2019t.",
      instructionText: "Tap \u2018Continue\u2019 to solve a few chance based challenges.",
      buttonText: "Continue",
    },

    challengeNavInitial: "Tap the correct place on the line.",
    challengeWrongFeedback: "Not quite!<br>Look at the count of tubes again.",
    challengeWrongText: "Not here,\nTry again!",

    problems: [
      {
        image: "assets/machine.png",
        correctPosition: 2,
        eventText: "<y>CHALLENGE 1</y>: Event is Getting an <or>ORANGE</or> capsule at random",
        extraText: "Based on chance of getting a <or>ORANGE</or> capsule,<br>where does this machine sit on the chance line?",
        correctExtraText: "<greenBox>Fewer <or>ORANGE</or> tubes than <gr>GREEN</gr>.<br>This means <sc2>low chance</sc2> of getting an <or>ORANGE</or> capsule.</greenBox>",
        correctNavText: "Tap \u201810 SERVES\u2019 to validate the answer.",
        serves: ["g","g","o","o","g","g","g","g","g","o"],
        extraTextFinal: "<greenBox>Look, with <sc2>low chance</sc2>, we still got<br>some <or>ORANGE</or> capsules.<br><br>Remember \u2013 <sc2>low chance</sc2> does not mean <y>never</y>.</greenBox>",
        afterServeNav: "Tap \u00BB to see Challenge 2.",
      },
      {
        image: "assets/machine.png",
        correctPosition: 3,
        eventText: "<y>CHALLENGE 2</y>: Event is Getting a <yl>YELLOW</yl> capsule at random",
        extraText: "Based on chance of getting a <yl>YELLOW</yl> capsule,<br>where does this machine sit on the chance line?",
        correctExtraText: "<greenBox>Equal number of <yl>YELLOW</yl> tubes and <pr>PURPLE</pr> tubes.<br>This means <sc3>equal chance</sc3> of getting a <yl>YELLOW</yl> capsule.</greenBox>",
        correctNavText: "Tap \u201810 SERVES\u2019 to validate the answer.",
        serves: ["y","pr","y","pr","y","y","y","pr","y","pr"],
        extraTextFinal: "<greenBox>Look, even with <sc3>equal chance</sc3>, we did not get equal numbers<br>of <yl>YELLOW</yl> and <pr>PURPLE</pr> capsules.<br><br>Remember \u2013 <sc3>equal chance</sc3> does not mean <y>equal results every time</y>.</greenBox>",
        afterServeNav: "Tap \u00BB to see Challenge 3.",
      },
      {
        image: "assets/machine.png",
        correctPosition: 5,
        eventText: "<y>CHALLENGE 3</y>: Event is Getting a <pn>PINK</pn> capsule at random",
        extraText: "Based on chance of getting a <pn>PINK</pn> capsule,<br>where does this machine sit on the chance line?",
        correctExtraText: "<greenBox>All tubes have <pn>PINK</pn> capsules.<br>This means <sc5>sure chance</sc5> of getting a <pn>PINK</pn> capsule.</greenBox>",
        correctNavText: "Tap \u201810 SERVES\u2019 to validate the answer.",
        serves: ["pn","pn","pn","pn","pn","pn","pn","pn","pn","pn"],
        extraTextFinal: "<greenBox>With <sc5>sure chance</sc5>, every single serve gave us a<br><pn>PINK</pn> capsule.<br><br>That makes sense \u2013 there is nothing else in the machine.</greenBox>",
        afterServeNav: "Tap \u00BB to see Challenge 4.",
      },
      {
        image: "assets/machine.png",
        correctPosition: 1,
        eventText: "<y>CHALLENGE 4</y>: Event is Getting an <or>ORANGE</or> capsule at random",
        extraText: "Based on chance of getting an <or>ORANGE</or> capsule,<br>where does this machine sit on the chance line?",
        correctExtraText: "<greenBox>No <or>ORANGE</or> tubes at all.<br>This means <sc1>no chance</sc1> of getting an <or>ORANGE</or> capsule.</greenBox>",
        correctNavText: "Tap \u201810 SERVES\u2019 to validate the answer.",
        serves: ["pn","pn","pn","pn","pn","pn","pn","pn","pn","pn"],
        extraTextFinal: "<greenBox>With <sc1>no chance</sc1>, we got zero <or>ORANGE</or><br>capsules.<br><br>That makes sense \u2013 there are no <or>ORANGE</or><br>tubes in the machine at all!</greenBox>",
        afterServeNav: "Tap \u00BB to see Challenge 5.",
      },
      {
        image: "assets/machine.png",
        correctPosition: 4,
        eventText: "<y>CHALLENGE 5</y>: Event is Getting an <or>ORANGE</or> capsule at random",
        extraText: "Based on chance of getting an <or>ORANGE</or> capsule,<br>where does this machine sit on the chance line?",
        correctExtraText: "<greenBox>More <or>ORANGE</or> tubes than <gr>GREEN</gr>.<br>This means <sc4>high chance</sc4> of getting<br>an <or>ORANGE</or> capsule.</greenBox>",
        correctNavText: "Tap \u201810 SERVES\u2019 to validate the answer.",
        serves: ["o","o","o","g","g","o","o","g","o","o"],
        extraTextFinal: "<greenBox>Look, with <sc4>high chance</sc4>, not every serve gave us<br><or>ORANGE</or>. We still got some <gr>GREEN</gr> capsules.<br><br>Remember \u2013 <sc4>high chance</sc4> does not mean <y>always</y>.</greenBox>",
        afterServeNav: "Tap \u00BB to see the key learning.",
      },
    ],

    finalScreen: {
      heading: "The Chance Line",
      scaleColumns: scaleColumnsForBg,
      scaleText: null,
      boxedHtml: "<y>Count</y> determines <y>chance</y>.<br><br>More <red>RED</red> \u2192 <y>higher chance</y> of getting <red>RED</red><br>Equal <red>RED</red> and <blue>BLUE</blue> \u2192 Equal chance of getting <red>RED</red><br>Fewer <red>RED</red> \u2192 <y>lower chance</y> of getting <red>RED</red><br><br>But chance is NOT a guarantee \u2013 high chance events might not occur,<br>and low chance event might occur!",
      instructionText: "Tap \u2018Start Over\u2019 to repeat this activity.",
      buttonText: "Start Over",
    },
  },

  id: {
    scalePositions: [
      { label: "Tiada\npeluang", dotColor: "#e53935" },
      { label: "Peluang\nrendah", dotColor: "#fb8c00" },
      { label: "Peluang\nsama", dotColor: "#fdd835" },
      { label: "Peluang\ntinggi", dotColor: "#29b6f6" },
      { label: "Peluang\npasti", dotColor: "#66bb6a" },
    ],

    intro: {
      heading: "Mengisi Garis Peluang",
      text: "Kita akan melihat 5 mesin kapsul berbeda.<br>Setiap mesin punya 4 tabung -<br>tapi jumlah <red>MERAH</red> dan <blue>BIRU</blue> yang berbeda.<br><br>Di mana pada garis peluang kamu akan menempatkannya?<br>Mari kita cari tahu bersama.<br><br>Ketuk \u2018Mulai\u2019 untuk memulai.",
      buttonText: "Mulai",
    },

    introStep1: {
      navText: "Ketuk \u00BB untuk melihat garis peluang.",
      image: "assets/machine.png",
      text: "Ini adalah<br><y>mesin kapsul</y>.<br>Ini memiliki 4 tabung<br>berisi kapsul.",
    },
    introStep2: {
      navText: "Ketuk \u00BB untuk membaca cara mengisi garis peluang.",
      text: "Ini adalah <y>garis peluang</y>. Ada 5 posisi.",
    },
    introStep3: {
      navText: "Ketuk \u00BB untuk membaca cara mengisi garis peluang.",
      headingText: "Kejadian: Mendapat kapsul <red>MERAH</red> secara acak",
      text: "Di atas, kita telah mendefinisikan kejadian kita.<br><br>Untuk semua mesin, kejadiannya akan tetap sama.<br><br>Kita akan mencari peluang mendapat kapsul <red>MERAH</red><br>dari mesin-mesin tersebut.",
    },
    introStep4: {
      navText: "Ketuk \u00BB untuk melihat Mesin 1.",
      text: "Kita akan mengisi setiap posisi dengan mesin kapsul!<br><br>Untuk setiap mesin, kita akan mencoba <b>10 sajian</b>,<br>hitung berapa yang keluar <red>MERAH</red>,<br>lalu tentukan di mana mesin itu berada pada garis peluang.",
    },

    eventHeading: "Kejadian: Mendapat kapsul <red>MERAH</red> secara acak",
    serveButtonText: "10 Sajian",

    machines: [
      {
        image: "assets/machine.png",
        correctPosition: 1,
        initialText: "<b>Mesin 1</b><br>4 <blue>BIRU</blue> dan 0 <red>MERAH</red> tabung.<br><br>Mari coba 10 sajian dan lihat<br>berapa kapsul <red>MERAH</red> yang kita dapat!",
        afterServeText: "0 dari 10 sajian adalah <red>MERAH</red>.<br><br>Setiap tabung berisi <blue>BIRU</blue>. Setiap sajian adalah <blue>BIRU</blue>!<br><br>Ini berarti<br><sc1>tiada peluang</sc1> mendapat kapsul MERAH.",
        finalText: "<greenBox>Posisi paling kiri mewakili<br><sc1>tiada peluang</sc1> pada garis peluang.</greenBox>",
        serves: ["b","b","b","b","b","b","b","b","b","b"],
        navInitial: "Ketuk \u201810 Sajian\u2019 untuk mencoba mesin ini.",
        navAfterServe: "Ketuk kotak untuk menempatkan Mesin 1 pada garis.",
        navAfterPlace: "Ketuk \u00BB untuk melihat Mesin 2.",
      },
      {
        image: "assets/machine.png",
        correctPosition: 2,
        initialText: "<b>Mesin 2</b><br>1 <red>MERAH</red> dan 3 <blue>BIRU</blue> tabung.<br><br>Mari coba 10 sajian dan lihat<br>berapa kapsul <red>MERAH</red> yang kita dapat!",
        afterServeText: "2 dari 10 sajian adalah <red>MERAH</red>.<br>Lebih sedikit tabung <red>MERAH</red> dari <blue>BIRU</blue>. Hanya sedikit sajian yang <red>MERAH</red>.<br><br>Ini berarti <sc2>peluang rendah</sc2> mendapat kapsul MERAH.",
        finalText: "<greenBox>Posisi ini lebih dekat ke <sc1>tiada peluang</sc1> mewakili<br><sc2>peluang rendah</sc2> pada garis peluang.</greenBox>",
        serves: ["b","r","b","b","b","b","r","b","b","b"],
        navInitial: "Ketuk \u201810 Sajian\u2019 untuk mencoba mesin ini.",
        navAfterServe: "Ketuk kotak untuk menempatkan Mesin 2 pada garis.",
        navAfterPlace: "Ketuk \u00BB untuk melihat Mesin 3.",
      },
      {
        image: "assets/machine.png",
        correctPosition: 3,
        initialText: "<b>Mesin 3</b><br>2 <red>MERAH</red> dan 2 <blue>BIRU</blue> tabung.<br><br>Mari coba 10 sajian dan lihat<br>berapa kapsul <red>MERAH</red> yang kita dapat!",
        afterServeText: "5 dari 10 sajian adalah <red>MERAH</red>.<br>Tabung <red>MERAH</red> dan <blue>BIRU</blue> sama banyak. Setengah sajian <red>MERAH</red>. Setengah <blue>BIRU</blue>.<br><br>Ini berarti <sc3>peluang sama</sc3> mendapat kapsul <red>MERAH</red> atau<br><blue>BIRU</blue>.",
        finalText: "<greenBox>Posisi ini antara <sc2>peluang rendah</sc2> dan <sc4>peluang tinggi</sc4><br>mewakili <sc3>peluang sama</sc3> pada garis peluang.</greenBox>",
        serves: ["b","r","r","b","r","b","r","b","b","r"],
        navInitial: "Ketuk \u201810 Sajian\u2019 untuk mencoba mesin ini.",
        navAfterServe: "Ketuk kotak untuk menempatkan Mesin 3 pada garis.",
        navAfterPlace: "Ketuk \u00BB untuk melihat Mesin 4.",
      },
      {
        image: "assets/machine.png",
        correctPosition: 4,
        initialText: "<b>Mesin 4</b><br>3 <red>MERAH</red> dan 1 <blue>BIRU</blue> tabung.<br><br>Mari coba 10 sajian dan lihat<br>berapa kapsul <red>MERAH</red> yang kita dapat!",
        afterServeText: "8 dari 10 sajian adalah <red>MERAH</red>.<br>Lebih banyak tabung <red>MERAH</red> dari <blue>BIRU</blue>. Sebagian besar sajian adalah <red>MERAH</red>.<br><br>Ini berarti <sc4>peluang tinggi</sc4> mendapat kapsul MERAH.",
        finalText: "<greenBox>Posisi ini lebih dekat ke <sc5>peluang pasti</sc5> mewakili<br><sc4>peluang tinggi</sc4> pada garis peluang.</greenBox>",
        serves: ["r","r","r","b","r","r","r","r","b","r"],
        navInitial: "Ketuk \u201810 Sajian\u2019 untuk mencoba mesin ini.",
        navAfterServe: "Ketuk kotak untuk menempatkan Mesin 4 pada garis.",
        navAfterPlace: "Ketuk \u00BB untuk melihat Mesin 5.",
      },
      {
        image: "assets/machine.png",
        correctPosition: 5,
        initialText: "<b>Mesin 5</b><br>4 <red>MERAH</red> dan 0 <blue>BIRU</blue> tabung.<br><br>Mari coba 10 sajian dan lihat<br>berapa kapsul <red>MERAH</red> yang kita dapat!",
        afterServeText: "10 dari 10 sajian adalah <red>MERAH</red>.<br>Semua tabung <red>MERAH</red>. Semua sajian <red>MERAH</red>!<br><br>Ini berarti <sc5>peluang pasti</sc5> mendapat kapsul MERAH.",
        finalText: "<greenBox>Posisi paling kanan mewakili<br><sc5>peluang pasti</sc5> pada garis peluang.</greenBox>",
        serves: ["r","r","r","r","r","r","r","r","r","r"],
        navInitial: "Ketuk \u201810 Sajian\u2019 untuk mencoba mesin ini.",
        navAfterServe: "Ketuk kotak untuk menempatkan Mesin 5 pada garis.",
        navAfterPlace: "Ketuk \u00BB untuk melihat garis peluang lengkap.",
      },
    ],

    machineWrongText: "Bukan di sini,\nCoba lagi!",

    splash2: {
      heading: "Garis Peluang \u2014 Terisi!",
      scaleColumns: scaleColumnsForBgId,
      visualImages: [
        "assets/machine.png",
        "assets/machine.png",
        "assets/machine.png",
        "assets/machine.png",
        "assets/machine.png",
      ],
      summaryHtml: "Dengan mengubah isi mesin, kita mengisi seluruh <y>garis peluang</y>.<br>Semakin banyak tabung <red>MERAH</red> di dalam, semakin <y>ke kanan</y> kejadian berada pada garis.",
      navText: "Ketuk \u00BB untuk melihat ide utama.",
    },

    fullscreen2: {
      heading: "Mengisi Garis Peluang \u2013 Selesai!",
      scaleColumns: scaleColumnsForBgId,
      scaleText: "<y>Peluang meningkat dari kiri ke kanan.</y>",
      boxedHtml: "<y>Apa yang Kita Temukan?</y><br><y>Jumlah</y> menentukan <y>peluang</y>.<br><br>Lebih banyak <red>MERAH</red> \u2192 <y>peluang lebih tinggi</y> mendapat <red>MERAH</red><br>Sama <red>MERAH</red> dan <blue>BIRU</blue> \u2192 Peluang sama mendapat <red>MERAH</red><br>Lebih sedikit <red>MERAH</red> \u2192 <y>peluang lebih rendah</y> mendapat <red>MERAH</red><br><br>Sekarang, giliranmu. Aturan sama, mesin berbeda.<br>Warna berubah \u2013 garis peluang tidak.",
      instructionText: "Ketuk \u2018Lanjut\u2019 untuk menyelesaikan beberapa tantangan berbasis peluang.",
      buttonText: "Lanjut",
    },

    challengeNavInitial: "Ketuk tempat yang benar pada garis.",
    challengeWrongFeedback: "Belum tepat!<br>Lihat kembali jumlah tabung.",
    challengeWrongText: "Bukan di sini,\nCoba lagi!",

    problems: [
      {
        image: "assets/machine.png",
        correctPosition: 2,
        eventText: "<y>TANTANGAN 1</y>: Kejadian adalah Mendapat kapsul <or>ORANYE</or> secara acak",
        extraText: "Berdasarkan peluang mendapat kapsul <or>ORANYE</or>,<br>di mana mesin ini berada pada garis peluang?",
        correctExtraText: "<greenBox>Lebih sedikit tabung <or>ORANYE</or> dari <gr>HIJAU</gr>.<br>Ini berarti <sc2>peluang rendah</sc2> mendapat kapsul <or>ORANYE</or>.</greenBox>",
        correctNavText: "Ketuk \u201810 SAJIAN\u2019 untuk memvalidasi jawaban.",
        serves: ["g","g","o","o","g","g","g","g","g","o"],
        extraTextFinal: "<greenBox>Lihat, dengan <sc2>peluang rendah</sc2>, kita masih mendapat<br>beberapa kapsul <or>ORANYE</or>.<br><br>Ingat \u2013 <sc2>peluang rendah</sc2> tidak berarti <y>tidak pernah</y>.</greenBox>",
        afterServeNav: "Ketuk \u00BB untuk melihat Tantangan 2.",
      },
      {
        image: "assets/machine.png",
        correctPosition: 3,
        eventText: "<y>TANTANGAN 2</y>: Kejadian adalah Mendapat kapsul <yl>KUNING</yl> secara acak",
        extraText: "Berdasarkan peluang mendapat kapsul <yl>KUNING</yl>,<br>di mana mesin ini berada pada garis peluang?",
        correctExtraText: "<greenBox>Jumlah tabung <yl>KUNING</yl> dan <pr>UNGU</pr> sama.<br>Ini berarti <sc3>peluang sama</sc3> mendapat kapsul <yl>KUNING</yl>.</greenBox>",
        correctNavText: "Ketuk \u201810 SAJIAN\u2019 untuk memvalidasi jawaban.",
        serves: ["y","pr","y","pr","y","y","y","pr","y","pr"],
        extraTextFinal: "<greenBox>Lihat, meskipun <sc3>peluang sama</sc3>, kita tidak mendapat jumlah yang sama<br>antara <yl>KUNING</yl> dan <pr>UNGU</pr>.<br><br>Ingat \u2013 <sc3>peluang sama</sc3> tidak berarti <y>hasil selalu sama</y>.</greenBox>",
        afterServeNav: "Ketuk \u00BB untuk melihat Tantangan 3.",
      },
      {
        image: "assets/machine.png",
        correctPosition: 5,
        eventText: "<y>TANTANGAN 3</y>: Kejadian adalah Mendapat kapsul <pn>MERAH MUDA</pn> secara acak",
        extraText: "Berdasarkan peluang mendapat kapsul <pn>MERAH MUDA</pn>,<br>di mana mesin ini berada pada garis peluang?",
        correctExtraText: "<greenBox>Semua tabung berisi kapsul <pn>MERAH MUDA</pn>.<br>Ini berarti <sc5>peluang pasti</sc5> mendapat kapsul <pn>MERAH MUDA</pn>.</greenBox>",
        correctNavText: "Ketuk \u201810 SAJIAN\u2019 untuk memvalidasi jawaban.",
        serves: ["pn","pn","pn","pn","pn","pn","pn","pn","pn","pn"],
        extraTextFinal: "<greenBox>Dengan <sc5>peluang pasti</sc5>, setiap sajian memberikan kita<br>kapsul <pn>MERAH MUDA</pn>.<br><br>Masuk akal \u2013 tidak ada yang lain di dalam mesin.</greenBox>",
        afterServeNav: "Ketuk \u00BB untuk melihat Tantangan 4.",
      },
      {
        image: "assets/machine.png",
        correctPosition: 1,
        eventText: "<y>TANTANGAN 4</y>: Kejadian adalah Mendapat kapsul <or>ORANYE</or> secara acak",
        extraText: "Berdasarkan peluang mendapat kapsul <or>ORANYE</or>,<br>di mana mesin ini berada pada garis peluang?",
        correctExtraText: "<greenBox>Tidak ada tabung <or>ORANYE</or> sama sekali.<br>Ini berarti <sc1>tiada peluang</sc1> mendapat kapsul <or>ORANYE</or>.</greenBox>",
        correctNavText: "Ketuk \u201810 SAJIAN\u2019 untuk memvalidasi jawaban.",
        serves: ["pn","pn","pn","pn","pn","pn","pn","pn","pn","pn"],
        extraTextFinal: "<greenBox>Dengan <sc1>tiada peluang</sc1>, kita mendapat nol kapsul <or>ORANYE</or>.<br><br>Masuk akal \u2013 tidak ada tabung <or>ORANYE</or><br>di dalam mesin sama sekali!</greenBox>",
        afterServeNav: "Ketuk \u00BB untuk melihat Tantangan 5.",
      },
      {
        image: "assets/machine.png",
        correctPosition: 4,
        eventText: "<y>TANTANGAN 5</y>: Kejadian adalah Mendapat kapsul <or>ORANYE</or> secara acak",
        extraText: "Berdasarkan peluang mendapat kapsul <or>ORANYE</or>,<br>di mana mesin ini berada pada garis peluang?",
        correctExtraText: "<greenBox>Lebih banyak tabung <or>ORANYE</or> dari <gr>HIJAU</gr>.<br>Ini berarti <sc4>peluang tinggi</sc4> mendapat<br>kapsul <or>ORANYE</or>.</greenBox>",
        correctNavText: "Ketuk \u201810 SAJIAN\u2019 untuk memvalidasi jawaban.",
        serves: ["o","o","o","g","g","o","o","g","o","o"],
        extraTextFinal: "<greenBox>Lihat, dengan <sc4>peluang tinggi</sc4>, tidak setiap sajian memberikan<br><or>ORANYE</or>. Kita masih mendapat beberapa kapsul <gr>HIJAU</gr>.<br><br>Ingat \u2013 <sc4>peluang tinggi</sc4> tidak berarti <y>selalu</y>.</greenBox>",
        afterServeNav: "Ketuk \u00BB untuk melihat pembelajaran utama.",
      },
    ],

    finalScreen: {
      heading: "Garis Peluang",
      scaleColumns: scaleColumnsForBgId,
      scaleText: null,
      boxedHtml: "<y>Jumlah</y> menentukan <y>peluang</y>.<br><br>Lebih banyak <red>MERAH</red> \u2192 <y>peluang lebih tinggi</y> mendapat <red>MERAH</red><br>Sama <red>MERAH</red> dan <blue>BIRU</blue> \u2192 Peluang sama mendapat <red>MERAH</red><br>Lebih sedikit <red>MERAH</red> \u2192 <y>peluang lebih rendah</y> mendapat <red>MERAH</red><br><br>Tapi peluang BUKAN jaminan \u2013 kejadian peluang tinggi mungkin tidak terjadi,<br>dan kejadian peluang rendah mungkin terjadi!",
      instructionText: "Ketuk \u2018Mulai Ulang\u2019 untuk mengulangi aktivitas ini.",
      buttonText: "Mulai Ulang",
    },
  },
};

const APP_DATA = DATA[current_language];
