const DATA = {
  en: {
    app: {
      start: {
        heading: "Faces, Vertices and Edges",
        text: "Today we will identify the number of faces,<br>vertices and edges in some objects.<br><br>Tap 'Start' to begin the lesson.",
        buttonText: "Start",
      },
      step1Question: "Is the given shape a cube or cuboid?",
      step1NavText: "Tap the correct option",
      step1Options: ["Cube", "Cuboid"],
      checkText: "Check",
      startOver: "Start Over",
      navStartOver: "Tap 'Start Over' to begin again",
      sliderMax: 12,
      questions: [
        {
          dims: [2, 2, 2],
          step1Answer: "Cube",
          questionText: "What are the number of faces in the given object?",
          answer: 6,
          navText: "Move the slider to find the number of faces and check",
          navCorrect: "Tap '»' to see the next question.",
        },
        {
          dims: [2, 5, 2],
          step1Answer: "Cuboid",
          questionText: "What are the number of vertices in the given object?",
          answer: 8,
          navText: "Move the slider to find the number of vertices and check",
          navCorrect: "Tap '»' to see the next question.",
        },
        {
          dims: [6, 2, 2],
          step1Answer: "Cuboid",
          questionText: "What are the number of edges in the given object?",
          answer: 12,
          navText: "Move the slider to find the number of edges and check",
          navCorrect: "Tap '»' to see the next question.",
        },
        {
          dims: [3, 6, 3],
          step1Answer: "Cuboid",
          questionText: "What are the number of vertices in the given object?",
          answer: 8,
          navText: "Move the slider to find the number of vertices and check",
          navCorrect: "Tap '»' to see the next question.",
        },
        {
          dims: [5, 3, 3],
          step1Answer: "Cuboid",
          questionText: "What are the number of faces in the given object?",
          answer: 6,
          navText: "Move the slider to find the number of faces and check",
          navCorrect: "Tap '»' to see the next question.",
        },
      ],
    },
  },
  id: {
    app: {
      start: {
        heading: "Sisi, Titik Sudut dan Rusuk",
        text: "Hari ini kita akan mengidentifikasi jumlah sisi,<br>titik sudut dan rusuk pada beberapa benda.<br><br>Ketuk 'Mulai' untuk memulai pelajaran.",
        buttonText: "Mulai",
      },
      step1Question: "Apakah bentuk yang diberikan kubus atau balok?",
      step1NavText: "Ketuk pilihan yang benar",
      step1Options: ["Kubus", "Balok"],
      checkText: "Periksa",
      startOver: "Mulai Lagi",
      navStartOver: "Ketuk 'Mulai Lagi' untuk memulai lagi",
      sliderMax: 12,
      questions: [
        {
          dims: [2, 2, 2],
          step1Answer: "Kubus",
          questionText: "Berapa jumlah sisi pada benda yang diberikan?",
          answer: 6,
          navText: "Gerakkan slider untuk menemukan jumlah sisi dan periksa",
          navCorrect: "Ketuk '»' untuk melihat pertanyaan berikutnya.",
        },
        {
          dims: [1, 3, 1],
          step1Answer: "Balok",
          questionText: "Berapa jumlah titik sudut pada benda yang diberikan?",
          answer: 8,
          navText: "Gerakkan slider untuk menemukan jumlah titik sudut dan periksa",
          navCorrect: "Ketuk '»' untuk melihat pertanyaan berikutnya.",
        },
        {
          dims: [3, 1, 1],
          step1Answer: "Balok",
          questionText: "Berapa jumlah rusuk pada benda yang diberikan?",
          answer: 12,
          navText: "Gerakkan slider untuk menemukan jumlah rusuk dan periksa",
          navCorrect: "Ketuk '»' untuk melihat pertanyaan berikutnya.",
        },
        {
          dims: [2, 3, 2],
          step1Answer: "Balok",
          questionText: "Berapa jumlah titik sudut pada benda yang diberikan?",
          answer: 8,
          navText: "Gerakkan slider untuk menemukan jumlah titik sudut dan periksa",
          navCorrect: "Ketuk '»' untuk melihat pertanyaan berikutnya.",
        },
        {
          dims: [3, 2, 2],
          step1Answer: "Balok",
          questionText: "Berapa jumlah sisi pada benda yang diberikan?",
          answer: 6,
          navText: "Gerakkan slider untuk menemukan jumlah sisi dan periksa",
          navCorrect: "Ketuk '»' untuk melihat pertanyaan berikutnya.",
        },
      ],
    },
  },
};

const APP_DATA = DATA[current_language].app;
