const decimal = {
  en: ".",
  id: ",",
};

const DATA = {
  en: {
    app: {
      start: {
        heading: "Pairs of Angles Formed by a Transversal",
        text: "A transversal and two lines form 8 angles.<br>Now, let's see the different angle pairs formed by them.",
        buttonText: "Start",
      },
      steps: {
        1: {
          navText: "Tap the highlighted text.",
          navNext:
            "Tap » to learn the different angle pairs formed by these 8 angles.",
        },
        2: {
          heading: "Linear Pair of Angles",
          navText: "Tap the highlighted text.",
          navNext: "Tap » to see the next type of pair of angles.",
          paginationDot: 1,
          totalDots: 7,
        },
        3: {
          heading: "Vertical Angles",
          navText: "Tap the highlighted text.",
          navNext: "Tap » to see the next type of pair of angles.",
          paginationDot: 2,
          totalDots: 7,
        },
        4: {
          heading: "Corresponding Angles",
          navText: "Tap the highlighted text.",
          navNext: "Tap » to identify all alternate exterior angles.",
          paginationDot: 3,
          totalDots: 7,
        },
        5: {
          heading: "Corresponding Angles",
          navText: "Tap one of the angles to see the corresponding angles.",
          navNext: "Tap » to see the next type of pair of angles.",
          paginationDot: 3,
          totalDots: 7,
        },
        6: {
          heading: "Alternate Exterior Angles",
          navText: "Tap the highlighted text.",
          navNext: "Tap » to identify all alternate exterior angles.",
          paginationDot: 4,
          totalDots: 7,
        },
        7: {
          heading: "Alternate Exterior Angles",
          navText: "Tap one of the highlighted angles to see the alternate exterior angles.",
          navNext: "Tap » to see the next type of pair of angles.",
          paginationDot: 4,
          totalDots: 7,
        },
        8: {
          heading: "Alternate Interior Angles",
          navText: "Tap the highlighted text.",
          navNext: "Tap » to identify all alternate interior angles.",
          paginationDot: 5,
          totalDots: 7,
        },
        9: {
          heading: "Alternate Interior Angles",
          navText: "Tap one of the highlighted angles to see the alternate interior angles.",
          navNext: "Tap » to see the next type of pair of angles.",
          paginationDot: 5,
          totalDots: 7,
        },
        10: {
          heading: "Co-exterior Angles",
          navText: "Tap the highlighted text.",
          navNext: "Tap » to identify all co-exterior angles.",
          paginationDot: 6,
          totalDots: 7,
        },
        11: {
          heading: "Co-exterior Angles",
          navText: "Tap one of the highlighted angles to see the co-exterior angles.",
          navNext: "Tap » to see the next type of pair of angles.",
          paginationDot: 6,
          totalDots: 7,
        },
        12: {
          heading: "Co-interior Angles",
          navText: "Tap the highlighted text.",
          navNext: "Tap » to identify all co-interior angles.",
          paginationDot: 7,
          totalDots: 7,
        },
        13: {
          heading: "Co-interior Angles",
          navText: "Tap one of the highlighted angles to see the co-interior angles.",
          navNext: "Tap » to review all types of angle pairs.",
          paginationDot: 7,
          totalDots: 7,
        },
        14: {
          navText: "Activity completed! You can tap each button to review.",
          nextButtonText: "Start Over",
        },
      },
      step14: {
        title:
          "Different types of pairs of angles formed by a transversal and 2 lines.",
        buttons: [
          "Linear Pair of Angles",
          "Vertical Angles",
          "Corresponding Angles",
          "Alternate Exterior Angles",
          "Alternate Interior Angles",
          "Co-exterior Angles",
          "Co-interior Angles",
        ],
        definitions: [
          "A pair of adjacent angles that form a straight line.",
          "A pair of opposite angles.",
          "Angles that occupy the same relative position.",
          "Angles that lie outside the two lines and<br>on opposite sides of the transversal.",
          "Angles that lie inside the two lines and<br>on opposite sides of the transversal.",
          "Angles that lie outside the two lines and<br>on the same side of the transversal.",
          "Angles that lie inside the two lines and<br>on the same side of the transversal.",
        ],
      },
      step1Parts: {
        part1: "When a ",
        transversal: "transversal",
        part2: "<br>intersects ",
        twoLines: "two lines",
        part3: "<br>at ",
        differentPoints: "different points",
        part4: ",<br>it creates ",
        eightAngles: "8 angles",
        part5: ".",
      },
      step2Parts: {
        part1: "A pair of<br>",
        adjacentAngles: "adjacent angles",
        part2: "<br>that form a<br>",
        straightLine: "straight line",
        part3: ".",
      },
      step3Parts: {
        part1: "A pair of<br>",
        oppositeAngles: "opposite angles",
        part2: ".",
      },
      step4Parts: {
        part1: "Angles that<br>occupy the<br>",
        sameRelativePosition: "same relative position",
        part2: ".",
      },
      step6Parts: {
        part1: "Angles that lie<br>",
        outsideTwoLines: "outside the two lines",
        part2: "<br>and on ",
        oppositeSides: "opposite sides",
        part3: "<br>of the transversal.",
      },
      step8Parts: {
        part1: "Angles that lie<br>",
        insideTwoLines: "inside the two lines",
        part2: "<br>and on ",
        oppositeSides: "opposite sides",
        part3: "<br>of the transversal.",
      },
      step10Parts: {
        part1: "Angles that lie<br>",
        outsideTwoLines: "outside the two lines",
        part2: "<br>and on the ",
        sameSide: "same side",
        part3: "<br>of the transversal.",
      },
      step12Parts: {
        part1: "Angles that lie<br>",
        insideTwoLines: "inside the two lines",
        part2: "<br>and on the ",
        sameSide: "same side",
        part3: "<br>of the transversal.",
      },
      labels: {
        transversal: "Transversal",
        straightLine: "Straight line",
        correspondingDefinition:
          "Angles that are in the same corner at each intersection",
      },
    },
  },
  id: {
    app: {
      start: {
        heading: "Pasangan Sudut yang Dibentuk oleh Transversal",
        text: "Sebuah transversal dan dua garis membentuk 8 sudut.<br>Sekarang, mari kita lihat berbagai pasangan sudut yang terbentuk.",
        buttonText: "Mulai",
      },
      steps: {
        1: {
          navText: "Ketuk teks yang disorot.",
          navNext:
            "Ketuk » untuk mempelajari berbagai pasangan sudut yang terbentuk dari 8 sudut ini.",
        },
        2: {
          heading: "Pasangan Sudut Linear",
          navText: "Ketuk teks yang disorot.",
          navNext: "Ketuk » untuk melihat jenis pasangan sudut berikutnya.",
          paginationDot: 1,
          totalDots: 7,
        },
        3: {
          heading: "Sudut Vertikal",
          navText: "Ketuk teks yang disorot.",
          navNext: "Ketuk » untuk melihat jenis pasangan sudut berikutnya.",
          paginationDot: 2,
          totalDots: 7,
        },
        4: {
          heading: "Sudut Sepasang",
          navText: "Ketuk teks yang disorot.",
          navNext: "Ketuk salah satu sudut untuk melihat sudut sepasangnya.",
          paginationDot: 3,
          totalDots: 7,
        },
        5: {
          heading: "Sudut Sepasang",
          navText: "Ketuk salah satu sudut untuk melihat sudut sepasangnya.",
          navNext: "Ketuk » untuk melihat jenis pasangan sudut berikutnya.",
          paginationDot: 3,
          totalDots: 7,
        },
        6: {
          heading: "Sudut Luar Berseberangan",
          navText: "Ketuk teks yang disorot.",
          navNext: "Ketuk » untuk mengidentifikasi semua sudut luar berseberangan.",
          paginationDot: 4,
          totalDots: 7,
        },
        7: {
          heading: "Sudut Luar Berseberangan",
          navText: "Ketuk salah satu sudut yang disorot untuk melihat sudut luar berseberangannya.",
          navNext: "Ketuk » untuk melihat jenis pasangan sudut berikutnya.",
          paginationDot: 4,
          totalDots: 7,
        },
        8: {
          heading: "Sudut Dalam Berseberangan",
          navText: "Ketuk teks yang disorot.",
          navNext: "Ketuk » untuk mengidentifikasi semua sudut dalam berseberangan.",
          paginationDot: 5,
          totalDots: 7,
        },
        9: {
          heading: "Sudut Dalam Berseberangan",
          navText: "Ketuk salah satu sudut yang disorot untuk melihat sudut dalam berseberangannya.",
          navNext: "Ketuk » untuk melihat jenis pasangan sudut berikutnya.",
          paginationDot: 5,
          totalDots: 7,
        },
        10: {
          heading: "Sudut Luar Sepasang",
          navText: "Ketuk teks yang disorot.",
          navNext: "Ketuk » untuk mengidentifikasi semua sudut luar sepasang.",
          paginationDot: 6,
          totalDots: 7,
        },
        11: {
          heading: "Sudut Luar Sepasang",
          navText: "Ketuk salah satu sudut yang disorot untuk melihat sudut luar sepasangnya.",
          navNext: "Ketuk » untuk melihat jenis pasangan sudut berikutnya.",
          paginationDot: 6,
          totalDots: 7,
        },
        12: {
          heading: "Sudut Dalam Sepasang",
          navText: "Ketuk teks yang disorot.",
          navNext: "Ketuk » untuk mengidentifikasi semua sudut dalam sepasang.",
          paginationDot: 7,
          totalDots: 7,
        },
        13: {
          heading: "Sudut Dalam Sepasang",
          navText: "Ketuk salah satu sudut yang disorot untuk melihat sudut dalam sepasangnya.",
          navNext: "Ketuk » untuk meninjau semua jenis pasangan sudut.",
          paginationDot: 7,
          totalDots: 7,
        },
        14: {
          navText: "Aktivitas selesai! Anda dapat mengetuk setiap tombol untuk meninjau.",
          nextButtonText: "Mulai Lagi",
        },
      },
      step14: {
        title:
          "Berbagai jenis pasangan sudut yang dibentuk oleh transversal dan 2 garis.",
        buttons: [
          "Pasangan Sudut Linear",
          "Sudut Vertikal",
          "Sudut Sejajar",
          "Sudut Luar Berseberangan",
          "Sudut Dalam Berseberangan",
          "Sudut Luar Sepasang",
          "Sudut Dalam Sepasang",
        ],
        definitions: [
          "Sepasang sudut bersebelahan yang membentuk garis lurus.",
          "Sepasang sudut berhadapan.",
          "Sudut yang menempati posisi relatif yang sama.",
          "Sudut yang berada di luar kedua garis dan<br>pada sisi berlawanan transversal.",
          "Sudut yang berada di dalam kedua garis dan<br>pada sisi berlawanan transversal.",
          "Sudut yang berada di luar kedua garis dan<br>pada sisi yang sama transversal.",
          "Sudut yang berada di dalam kedua garis dan<br>pada sisi yang sama transversal.",
        ],
      },
      step1Parts: {
        part1: "Ketika sebuah ",
        transversal: "transversal",
        part2: "<br>memotong ",
        twoLines: "dua garis",
        part3: "<br>pada ",
        differentPoints: "titik yang berbeda",
        part4: ",<br>ia membentuk ",
        eightAngles: "8 sudut",
        part5: ".",
      },
      step2Parts: {
        part1: "Sepasang<br>",
        adjacentAngles: "sudut bersebelahan",
        part2: "<br>yang membentuk<br>",
        straightLine: "garis lurus",
        part3: ".",
      },
      step3Parts: {
        part1: "Sepasang<br>",
        oppositeAngles: "sudut berhadapan",
        part2: ".",
      },
      step4Parts: {
        part1: "Sudut yang<br>menempati<br>",
        sameRelativePosition: "posisi relatif yang sama",
        part2: ".",
      },
      step6Parts: {
        part1: "Sudut yang berada<br>",
        outsideTwoLines: "di luar kedua garis",
        part2: "<br>dan pada ",
        oppositeSides: "sisi berlawanan",
        part3: "<br>dari transversal.",
      },
      step8Parts: {
        part1: "Sudut yang berada<br>",
        insideTwoLines: "di dalam kedua garis",
        part2: "<br>dan pada ",
        oppositeSides: "sisi berlawanan",
        part3: "<br>dari transversal.",
      },
      step10Parts: {
        part1: "Sudut yang berada<br>",
        outsideTwoLines: "di luar kedua garis",
        part2: "<br>dan pada ",
        sameSide: "sisi yang sama",
        part3: "<br>dari transversal.",
      },
      step12Parts: {
        part1: "Sudut yang berada<br>",
        insideTwoLines: "di dalam kedua garis",
        part2: "<br>dan pada ",
        sameSide: "sisi yang sama",
        part3: "<br>dari transversal.",
      },
      labels: {
        transversal: "Transversal",
        straightLine: "Garis Lurus",
        correspondingDefinition:
          "Sudut yang berada di sudut yang sama pada setiap perpotongan",
      },
    },
  },
};

const APP_DATA = DATA[current_language].app;
const decimalSymbol = decimal[current_language];
