const questions = [
  {
    ctKey: "q1_ct",
    nKey: "q1_n",
    ans: "No",
    feedbackCorrectKey: "q1_feedbackCorrect",
    feedbackWrongKey: "q1_feedbackWrong",
    navCorrectKey: "q1_navCorrect",
    image: "q1.svg",
    imageCorrect: "q1correct.svg",
    imageWrong: "q1wrong.svg",
    visualCharacter: "rizky.png",
    vtKey: "q1_vt",
    vtCorrectKey: "q1_vtCorrect",
    vtWrongKey: null,
  },
  {
    ctKey: "q2_ct",
    nKey: "q1_n",
    ans: "No",
    feedbackCorrectKey: "q2_feedbackCorrect",
    feedbackWrongKey: "q2_feedbackWrong",
    navCorrectKey: "q2_navCorrect",
    image: "q2.svg",
    imageCorrect: "q2correct.svg",
    imageWrong: "q2wrong.svg",
    visualCharacter: "farhan.png",
    vtKey: "q2_vt",
    vtCorrectKey: "q2_vtCorrect",
    vtWrongKey: null,
  },
  {
    ctKey: "q3_ct",
    nKey: "q1_n",
    ans: "No",
    feedbackCorrectKey: "q3_feedbackCorrect",
    feedbackWrongKey: "q3_feedbackWrong",
    navCorrectKey: "q3_navCorrect",
    image: "q3.svg",
    imageCorrect: "q3correct.svg",
    imageWrong: "q3wrong.svg",
    visualCharacter: "rizky.png",
    vtKey: "q3_vt",
    vtCorrectKey: "q3_vtCorrect",
    vtWrongKey: null,
  },
  {
    ctKey: "q4_ct",
    nKey: "q1_n",
    ans: "Yes",
    feedbackCorrectKey: "q4_feedbackCorrect",
    feedbackWrongKey: "q4_feedbackWrong",
    navCorrectKey: "q4_navCorrect",
    image: "q4.svg",
    imageCorrect: null,
    imageWrong: null,
    visualCharacter: "farhan.png",
    vtKey: "q4_vt",
    vtCorrectKey: null,
    vtWrongKey: null,
  },
  {
    ctKey: "q5_ct",
    nKey: "q1_n",
    ans: "No",
    feedbackCorrectKey: "q5_feedbackCorrect",
    feedbackWrongKey: "q5_feedbackWrong",
    navCorrectKey: "q5_navCorrect",
    image: "q5.svg",
    imageCorrect: "q5correct.svg",
    imageWrong: "q5wrong.svg",
    visualCharacter: "rizky.png",
    vtKey: "q5_vt",
    vtCorrectKey: "q5_vtCorrect",
    vtWrongKey: null,
  },
  {
    ctKey: "q6_ct",
    nKey: "q1_n",
    ans: "No",
    feedbackCorrectKey: "q6_feedbackCorrect",
    feedbackWrongKey: "q6_feedbackWrong",
    navCorrectKey: "q6_navCorrect",
    image: "q6.svg",
    imageCorrect: "q6correct.svg",
    imageWrong: "q6wrong.svg",
    visualCharacter: "farhan.png",
    vtKey: "q6_vt",
    vtCorrectKey: "q6_vtCorrect",
    vtWrongKey: "q6_vtWrong",
  },
  {
    ctKey: "q7_ct",
    nKey: "q1_n",
    ans: "Yes",
    feedbackCorrectKey: "q7_feedbackCorrect",
    feedbackWrongKey: "q7_feedbackWrong",
    navCorrectKey: "q7_navCorrect",
    image: "q7.svg",
    imageCorrect: null,
    imageWrong: "q7wrong.svg",
    visualCharacter: "rizky.png",
    vtKey: "q7_vt",
    vtCorrectKey: null,
    vtWrongKey: "q7_vtWrong",
  },
];

const DATA = {
  en: {
    app: {
      options: ["Yes", "No"],
      start: {
        heading: "Measuring Objects",
        text: "Farhan and Rizky are finding the length and height of an object.<br> Let's see if they are doing it right.",
        buttonText: "Start",
      },
      steps: {
        1: {
          nKey: "nav_default",
          questions: questions,
          texts: {
            nav_default: "Tap the correct option.",
            q1_ct: "Is Rizky measuring the length correctly?",
            q1_feedbackCorrect: "That's correct! When we measure length, we place objects from the left end.",
            q1_feedbackWrong: "Oops! Clips are not placed from the left end of the object. Check again.",
            q1_navCorrect: "Tap » to see another scenario.",
            q1_vt: "Length of the pencil is 3 clips.",
            q1_vtCorrect: "Length of the pencil is <green>4</green> clips.",
            q2_ct: "Is Farhan measuring the length correctly?",
            q2_feedbackCorrect: "That's correct! When we measure length, we place objects till the other end.",
            q2_feedbackWrong: "Oops! Clips are not placed till the other end. Check again.",
            q2_navCorrect: "Tap » to see another scenario.",
            q2_vt: "Length of the box is 4 clips.",
            q2_vtCorrect: "Length of the box is <green>5</green> clips.",
            q3_ct: "Is Rizky measuring the length correctly?",
            q3_feedbackCorrect: "That's correct! When we measure length, there should not be any gaps.",
            q3_feedbackWrong: "Oops! There are gaps between the clips. Check again.",
            q3_navCorrect: "Tap » to see the next scenario.",
            q3_vt: "Length of the book is 3 clips.",
            q3_vtCorrect: "Length of the book is <green>4</green> clips.",
            q4_ct: "Is Farhan measuring the length correctly?",
            q4_feedbackCorrect: "Yes, Farhan measured the length correctly",
            q4_feedbackWrong: "Oops! Check again. He placed the clips correctly.",
            q4_navCorrect: "Tap » to see a few more scenarios.",
            q4_vt: "Length of the duster is 3 clips.",
            q5_ct: "Is Rizky measuring the height correctly?",
            q5_feedbackCorrect: "That's correct! When we measure, we place objects along the book.",
            q5_feedbackWrong: "Oops! The clips needs to be placed along the book. Check again.",
            q5_navCorrect: "Tap » to see two more scenarios",
            q5_vt: "Height of the book is 5 clips.",
            q5_vtCorrect: "Height of the book is <green>4</green> clips.",
            q6_ct: "Is Farhan measuring the height correctly?",
            q6_feedbackCorrect: "That's correct! He made a mistake when counting.",
            q6_feedbackWrong: "Oops! There are 5 clips placed, but he said height as 4 clips. Check again",
            q6_navCorrect: "Tap » to see one more scenario.",
            q6_vt: "Height of the bottle is 4 clips.",
            q6_vtCorrect: "Height of the bottle is <green>5</green> clips.",
            q6_vtWrong: "Height of the bottle is <red>4</red> clips.",
            q7_ct: "Is Rizky measuring the height correctly?",
            q7_feedbackCorrect: "Yes, Rizky measured the height correctly.",
            q7_feedbackWrong: "Oops! Check again. He placed and counted the clips correctly.",
            q7_navCorrect: "Tap » to start over.",
            q7_vt: "Height of the glass is 4 clips.",
            q7_vtWrong: "Height of the glass is <red>4</red> clips.",
          },
        },
      },
      final: {
        heading: "Measuring Objects",
        text: "Awesome! You helped Farhan and Rizky measure correctly!",
        buttonText: "Start Over",
      },
    },
  },
  id: {
    app: {
      options: ["Ya", "Tidak"],
      start: {
        heading: "Mengukur Benda",
        text: "Farhan dan Rizky sedang mencari panjang dan tinggi suatu benda.<br> Mari kita lihat apakah mereka melakukannya dengan benar.",
        buttonText: "Mulai",
      },
      steps: {
        1: {
          nKey: "nav_default",
          questions: questions,
          texts: {
            nav_default: "Ketuk opsi yang benar.",
            q1_ct: "Apakah Rizky mengukur panjangnya dengan benar?",
            q1_feedbackCorrect: "Benar! Saat kita mengukur panjang, kita menempatkan benda dari ujung kiri.",
            q1_feedbackWrong: "Ups! Klip tidak ditempatkan dari ujung kiri benda. Coba lagi.",
            q1_navCorrect: "Ketuk » untuk melihat skenario lain.",
            q1_vt: "Panjang pensil adalah 3 klip.",
            q1_vtCorrect: "Panjang pensil adalah <green>4</green> klip.",
            q2_ct: "Apakah Farhan mengukur panjangnya dengan benar?",
            q2_feedbackCorrect: "Benar! Saat kita mengukur panjang, kita menempatkan benda sampai ujung lainnya.",
            q2_feedbackWrong: "Ups! Klip tidak ditempatkan sampai ujung lainnya. Coba lagi.",
            q2_navCorrect: "Ketuk » untuk melihat skenario lain.",
            q2_vt: "Panjang kotak adalah 4 klip.",
            q2_vtCorrect: "Panjang kotak adalah <green>5</green> klip.",
            q3_ct: "Apakah Rizky mengukur panjangnya dengan benar?",
            q3_feedbackCorrect: "Benar! Saat kita mengukur panjang, tidak boleh ada celah.",
            q3_feedbackWrong: "Ups! Ada celah di antara klip. Coba lagi.",
            q3_navCorrect: "Ketuk » untuk melihat skenario berikutnya.",
            q3_vt: "Panjang buku adalah 3 klip.",
            q3_vtCorrect: "Panjang buku adalah <green>4</green> klip.",
            q4_ct: "Apakah Farhan mengukur panjangnya dengan benar?",
            q4_feedbackCorrect: "Ya, Farhan mengukur panjangnya dengan benar.",
            q4_feedbackWrong: "Ups! Coba lagi. Dia menempatkan klip dengan benar.",
            q4_navCorrect: "Ketuk » untuk melihat beberapa skenario lagi.",
            q4_vt: "Panjang penghapus adalah 3 klip.",
            q5_ct: "Apakah Rizky mengukur tingginya dengan benar?",
            q5_feedbackCorrect: "Benar! Saat kita mengukur, kita menempatkan benda sepanjang papan.",
            q5_feedbackWrong: "Ups! Klip harus ditempatkan sepanjang papan. Coba lagi.",
            q5_navCorrect: "Ketuk » untuk melihat dua skenario lagi.",
            q5_vt: "Tinggi buku adalah 5 klip.",
            q5_vtCorrect: "Tinggi buku adalah <green>4</green> klip.",
            q6_ct: "Apakah Farhan mengukur tingginya dengan benar?",
            q6_feedbackCorrect: "Benar! Dia salah saat menghitung.",
            q6_feedbackWrong: "Ups! Ada 5 klip yang ditempatkan, tapi dia bilang tingginya 4 klip. Coba lagi.",
            q6_navCorrect: "Ketuk » untuk melihat satu skenario lagi.",
            q6_vt: "Tinggi botol adalah 4 klip.",
            q6_vtCorrect: "Tinggi botol adalah <green>5</green> klip.",
            q6_vtWrong: "Tinggi botol adalah <red>4</red> klip.",
            q7_ct: "Apakah Rizky mengukur tingginya dengan benar?",
            q7_feedbackCorrect: "Ya, Rizky mengukur tingginya dengan benar.",
            q7_feedbackWrong: "Ups! Coba lagi. Dia menempatkan dan menghitung klip dengan benar.",
            q7_navCorrect: "Ketuk » untuk memulai ulang.",
            q7_vt: "Tinggi gelas adalah 4 klip.",
            q7_vtWrong: "Tinggi gelas adalah <red>4</red> klip.",
          },
        },
      },
      final: {
        heading: "Mengukur Benda",
        text: "Luar biasa! Kamu membantu Farhan dan Rizky mengukur dengan benar!",
        buttonText: "Mulai Lagi",
      },
    },
  },
};

const APP_DATA = DATA[current_language].app;
