const DATA = {
  en: {
    app: {
      start: {
        heading: "Similar Objects",
        text: "Look closely at each pair of objects.<br>Identify whether they are similar or not.",
        buttonText: "START",
      },
      final: {
        heading: "Similar Objects",
        text: "Great job! We can now tell<br>whether two objects are similar or not.",
        buttonText: "START OVER",
      },
      labels: {
        similarHeading: "Similar Objects",
        nonSimilarHeading: "Non Similar Objects",
      },
      steps: {
        1: {
          questionText: "Are these objects similar or not similar?",
          navText: "Tap the correct box.",
          navTextDone: "Tap next button to continue.",
          questions: [
            {
              img1: "assets/clock1.png",
              img2: "assets/clock2.png",
              placement: "row",
              width1: "20vw",
              width2: "20vw",
              finalWidth1: "20vw",
              finalWidth2: "20vw",
              rowWidth1: "10vw",
              rowWidth2: "10vw",
              ans: "non-similar",
              matchHeight: true,
            },
            {
              img1: "assets/kite1.png",
              img2: "assets/kite2.png",
              placement: "column",
              width1: "35vw",
              width2: "20vw",
              finalWidth1: "30vw",
              finalWidth2: "30vw",
              rowWidth1: "10vw",
              rowWidth2: "10vw",
              ans: "similar",
            },
            {
              img1: "assets/plane1.png",
              img2: "assets/plane2.png",
              placement: "column",
              width1: "40vw",
              width2: "33vw",
              finalWidth1: "40vw",
              finalWidth2: "40vw",
              rowWidth1: "10vw",
              rowWidth2: "10vw",
              ans: "non-similar",
            },
            {
              img1: "assets/cake1.png",
              img2: "assets/cake2.png",
              placement: "row",
              width1: "15vw",
              width2: "28vw",
              finalWidth1: "25vw",
              finalWidth2: "25vw",
              rowWidth1: "10vw",
              rowWidth2: "10vw",
              ans: "similar",
            },
            {
              img1: "assets/choco1.png",
              img2: "assets/choco2.png",
              placement: "row",
              width1: "20vw",
              width2: "20vw",
              finalWidth1: "20vw",
              finalWidth2: "20vw",
              rowWidth1: "10vw",
              rowWidth2: "10vw",
              ans: "non-similar",
              matchHeight: true,
            },
            {
              img1: "assets/book1.png",
              img2: "assets/book2.png",
              placement: "row",
              width1: "21vw",
              width2: "15vw",
              finalWidth1: "21vw",
              finalWidth2: "21vw",
              rowWidth1: "10vw",
              rowWidth2: "10vw",
              ans: "non-similar",
              // matchHeight: true,
            },
            {
              img1: "assets/racket.png",
              img2: "assets/racket.png",
              placement: "column",
              width1: "30vw",
              width2: "15vw",
              finalWidth1: "30vw",
              finalWidth2: "30vw",
              rowWidth1: "10vw",
              rowWidth2: "10vw",
              ans: "similar",
            },
            {
              img1: "assets/plate1.png",
              img2: "assets/plate2.png",
              placement: "row",
              width1: "15vw",
              width2: "28vw",
              finalWidth1: "25vw",
              finalWidth2: "25vw",
              rowWidth1: "10vw",
              rowWidth2: "10vw",
              ans: "similar",
            },
            {
              img1: "assets/gift1.png",
              img2: "assets/gift2.png",
              placement: "row",
              width1: "25vw",
              width2: "15vw",
              finalWidth1: "25vw",
              finalWidth2: "25vw",
              rowWidth1: "10vw",
              rowWidth2: "10vw",
              ans: "similar",
            },

            {
              img1: "assets/ball1.png",
              img2: "assets/ball2.png",
              placement: "column",
              width1: "20vw",
              width2: "30vw",
              finalWidth1: "30vw",
              finalWidth2: "30vw",
              rowWidth1: "10vw",
              rowWidth2: "10vw",
              ans: "non-similar",
            },
            
            
            
          ],
        },
      },
    },
  },
  id: {
    app: {
      start: {
        heading: "Objek Serupa",
        text: "Perhatikan dengan saksama setiap pasang objek.<br>Tentukan apakah objek tersebut serupa atau tidak serupa.",
        buttonText: "MULAI",
      },
      final: {
        heading: "Objek Serupa",
        text: "Kerja bagus! Kita sekarang bisa menentukan<br>apakah dua objek serupa atau tidak.",
        buttonText: "ULANGI",
      },
      labels: {
        similarHeading: "Objek Serupa",
        nonSimilarHeading: "Objek Tidak Serupa",
      },
      steps: {
        1: {
          questionText: "Apakah objek-objek ini serupa atau tidak serupa?",
          navText: "Ketuk kotak yang benar.",
          navTextDone: "Ketuk tombol berikutnya untuk melanjutkan.",
          questions: [
            {
              img1: "assets/clock1.png",
              img2: "assets/clock2.png",
              placement: "row",
              width1: "20vw",
              width2: "20vw",
              finalWidth1: "20vw",
              finalWidth2: "20vw",
              rowWidth1: "10vw",
              rowWidth2: "10vw",
              ans: "non-similar",
              matchHeight: true,
            },
            {
              img1: "assets/kite1.png",
              img2: "assets/kite2.png",
              placement: "column",
              width1: "35vw",
              width2: "20vw",
              finalWidth1: "30vw",
              finalWidth2: "30vw",
              rowWidth1: "10vw",
              rowWidth2: "10vw",
              ans: "similar",
            },
            {
              img1: "assets/plane1.png",
              img2: "assets/plane2.png",
              placement: "column",
              width1: "40vw",
              width2: "33vw",
              finalWidth1: "40vw",
              finalWidth2: "40vw",
              rowWidth1: "10vw",
              rowWidth2: "10vw",
              ans: "non-similar",
            },
            {
              img1: "assets/cake1.png",
              img2: "assets/cake2.png",
              placement: "row",
              width1: "15vw",
              width2: "28vw",
              finalWidth1: "25vw",
              finalWidth2: "25vw",
              rowWidth1: "10vw",
              rowWidth2: "10vw",
              ans: "similar",
            },
            {
              img1: "assets/choco1.png",
              img2: "assets/choco2.png",
              placement: "row",
              width1: "20vw",
              width2: "20vw",
              finalWidth1: "20vw",
              finalWidth2: "20vw",
              rowWidth1: "10vw",
              rowWidth2: "10vw",
              ans: "non-similar",
              matchHeight: true,
            },
            {
              img1: "assets/book1.png",
              img2: "assets/book2.png",
              placement: "row",
              width1: "21vw",
              width2: "15vw",
              finalWidth1: "21vw",
              finalWidth2: "21vw",
              rowWidth1: "10vw",
              rowWidth2: "10vw",
              ans: "non-similar",
              // matchHeight: true,
            },
            {
              img1: "assets/racket.png",
              img2: "assets/racket.png",
              placement: "column",
              width1: "30vw",
              width2: "15vw",
              finalWidth1: "30vw",
              finalWidth2: "30vw",
              rowWidth1: "10vw",
              rowWidth2: "10vw",
              ans: "similar",
            },
            {
              img1: "assets/plate1.png",
              img2: "assets/plate2.png",
              placement: "row",
              width1: "15vw",
              width2: "28vw",
              finalWidth1: "25vw",
              finalWidth2: "25vw",
              rowWidth1: "10vw",
              rowWidth2: "10vw",
              ans: "similar",
            },
            {
              img1: "assets/gift1.png",
              img2: "assets/gift2.png",
              placement: "row",
              width1: "25vw",
              width2: "15vw",
              finalWidth1: "25vw",
              finalWidth2: "25vw",
              rowWidth1: "10vw",
              rowWidth2: "10vw",
              ans: "similar",
            },
            {
              img1: "assets/ball1.png",
              img2: "assets/ball2.png",
              placement: "column",
              width1: "20vw",
              width2: "30vw",
              finalWidth1: "30vw",
              finalWidth2: "30vw",
              rowWidth1: "10vw",
              rowWidth2: "10vw",
              ans: "non-similar",
            },
          ],
        },
      },
    },
  },
};

const APP_DATA = DATA[current_language].app;
