const DATA = {
  en: {
    app: {
      dataset: [3, 6, 4, 4, 8, 7, 8, 9, 4, 5, 6, 6],
      sortedDataset: [3, 4, 4, 4, 5, 6, 6, 6, 7, 8, 8, 9],
      modeValues: [4, 6],
      start: {
        heading: "Let's solve!",
        stats: ["Mode = ?", "Median = ?", "Mean = ?"],
        introLines: [
          "Here is a data set given.",
          "Your task is to find:",
          "a) Mode,",
          "b) Median, and",
          "c) Mean",
          "of this data set.",
          "Tap 'Start' to start solving.",
        ],
        buttonText: "Start",
      },
      steps: {
        1: {
          questionText: "Let's first determine the mode.<br>How many modes are there?",
          navText: "Tap and choose the correct number of modes.",
          countPrompt: "How many modes?",
          identifyPrompt: "What are the modes?",
          modePromptSingular: "What is the mode?",
          countCorrectQuestion: "There are 2 modes. Identify these 2 modes.",
          countCorrectNav: "Tap and choose the correct modes.",
          oneModeQuestion: "You found one mode. Find the other mode as well.",
          completeQuestion: "So, the modes of this data set are: <y>4</y> and <yl>6</yl>.",
          completeNav: "Tap &raquo; to find the median of the data set.",
        },
        2: {
          questionText: "What are the steps of finding the median of a data set having 9 values.",
          navText: "Drag the correct option near the correct step number.",
          completeQuestion: "That's right. The steps are in order. Let's now find the mean step wise.",
          completeNav: "Tap step 1 to sort the data set.",
          stepLabels: ["Step 1", "Step 2", "Step 3"],
          options: {
            find: "Find the median",
            sort: "Sort the data from smallest to largest",
            eliminate: "Eliminate values in pairs to find middle",
          },
          initialOrder: ["find", "sort", "eliminate"],
          correctOrder: ["sort", "eliminate", "find"],
        },
        3: {
          questionText: "Let's order the data set in order from smallest to largest.",
          navText: "Tap each data value in order - starting with the smallest.",
          smallest: "Smallest",
          largest: "Largest",
        },
        4: {
          questionText: "Step 1 is done. Let's move ahead with the next step.",
          navText: "Tap on step 2.",
        },
        5: {
          questionText: "Let us now eliminate values to reach the middle value(s).",
          navText: "Tap the smallest or largest - both will be removed together.",
          ongoingNav: "Tap the next smallest or largest value.",
          completeQuestion: "Step 2 is also done. Let us now move ahead with the last step.",
          completeNav: "Tap on step 3.",
        },
        6: {
          questionText: "There are two middle values.<br>How do we find the median of the data set in this case?",
          navText: "Tap the correct option.",
          completeNav: "Tap &raquo; to find the median.",
          options: [
            "Sum of the two middle values",
            "Mean of the two middle values",
            "Any one of the middle values",
          ],
          correctIndex: 1,
          wrongFeedback: "When there are two middle values, averaging them out gives us the median.",
          correctFeedback: "That's right! When there are two middle values, we average them out.",
        },
        7: {
          questionText: "Find the mean of the two middle values.",
          completeQuestion: "The median of the data set is 6.",
          navText: "Fill in the answer using the numpad and tap ✓ to submit.",
          completeNav: "Tap &raquo; to now find the mean of this data set.",
          denominator: 2,
          correctAnswer: 6,
        },
        8: {
          questionText: "First, formula mean.",
          completeQuestion: "Let us now find the mean of the data set",
          navText: "Drag the correct option at correct place.",
          completeNav: "Tap &raquo; to continue with the calculation of mean.",
          dropPlaceholder: "Drop here",
        },
        9: {
          questionText: "Let us now find the mean of the data set.",
          navText: "Tap on the numerator or denominator.",
          sumQuestion: "What is the sum of all values: 3+6+4+4+8+7+8+9+4+5+6+6",
          sumNav: "Enter the correct total using numpad.",
          sumCompleteQuestion: "Sum of all values: 3+6+4+4+8+7+8+9+4+5+6+6 = 70",
          sumCompleteNav: "Tap on denominator now.",
          countCompleteNav: "Tap on numerator now.",
          countQuestion: "What is the total number of data values?",
          countNav: "Enter the correct number using numpad.",
          countCompleteQuestion: "The total number of data values is 12.",
          meanQuestion: "Divide the total with the number of data points now. And find the mean.",
          meanNav: "Enter the correct mean using numpad.",
          completeQuestion: "The mean of the numbers is 5.8",
          completeNav: "Tap &raquo;.",
          sumAnswer: 70,
          countAnswer: 12,
          meanAnswer: "5.8",
        },
      },
      meanDragDrop: {
        draggables: [
          { id: "sum", text: "Sum of all\ndata values" },
          { id: "count", text: "Number of\ndata values" },
          { id: "mean", text: "Mean" },
        ],
        zoneMap: { left: "mean", num: "sum", denom: "count" },
        labels: {
          mean: "Mean",
          sum: "Sum of all data values",
          count: "Number of data values",
        },
      },
      completion: {
        heading: "Well Done!",
        stats: ["Mode = 4 & 6", "Median = 6", "Mean = 5.8"],
        text: "You successfully found the mode, mean, and median of this data set.<br><br> Tap 'Start over' to repeat this activity.",
        buttonText: "Start Over",
      },
    },
  },
  id: {
    app: {
      dataset: [3, 6, 4, 4, 8, 7, 8, 9, 4, 5, 6, 6],
      sortedDataset: [3, 4, 4, 4, 5, 6, 6, 6, 7, 8, 8, 9],
      modeValues: [4, 6],
      start: {
        heading: "Ayo selesaikan!",
        stats: ["Modus = ?", "Median = ?", "Mean = ?"],
        introLines: [
          "Berikut adalah kumpulan data.",
          "Tugasmu adalah menemukan:",
          "a) Modus,",
          "b) Median, dan",
          "c) Mean",
          "dari kumpulan data ini.",
          "Ketuk 'Mulai' untuk mulai menyelesaikan.",
        ],
        buttonText: "Mulai",
      },
      steps: {
        1: {
          questionText: "Mari tentukan modus terlebih dahulu.<br>Ada berapa modus?",
          navText: "Ketuk dan pilih jumlah modus yang benar.",
          countPrompt: "Ada berapa modus?",
          identifyPrompt: "Apa saja modusnya?",
          modePromptSingular: "Apa modusnya?",
          countCorrectQuestion: "Ada 2 modus. Temukan 2 modus tersebut.",
          countCorrectNav: "Ketuk dan pilih modus yang benar.",
          oneModeQuestion: "Kamu menemukan satu modus. Temukan modus yang lainnya juga.",
          completeQuestion: "Jadi, modus dari kumpulan data ini adalah: 4 dan 6.",
          completeNav: "Ketuk &raquo; untuk menemukan median dari kumpulan data.",
        },
        2: {
          questionText: "Apa langkah-langkah mencari median dari kumpulan data yang memiliki 9 nilai.",
          navText: "Seret pilihan yang benar ke dekat nomor langkah yang tepat.",
          completeQuestion: "Benar. Langkah-langkahnya sudah berurutan. Sekarang mari cari mean secara bertahap.",
          completeNav: "Ketuk langkah 1 untuk mengurutkan kumpulan data.",
          stepLabels: ["Langkah 1", "Langkah 2", "Langkah 3"],
          options: {
            find: "Temukan median",
            sort: "Urutkan data dari yang terkecil ke terbesar",
            eliminate: "Hilangkan nilai secara berpasangan untuk menemukan bagian tengah",
          },
          initialOrder: ["find", "sort", "eliminate"],
          correctOrder: ["sort", "eliminate", "find"],
        },
        3: {
          questionText: "Mari urutkan kumpulan data dari yang terkecil ke terbesar.",
          navText: "Ketuk setiap nilai data secara berurutan - mulai dari yang terkecil.",
          smallest: "Terkecil",
          largest: "Terbesar",
        },
        4: {
          questionText: "Langkah 1 selesai. Mari lanjut ke langkah berikutnya.",
          navText: "Ketuk langkah 2.",
        },
        5: {
          questionText: "Sekarang mari hilangkan nilai untuk mencapai nilai tengah.",
          navText: "Ketuk nilai terkecil atau terbesar - keduanya akan dihapus bersama.",
          ongoingNav: "Ketuk nilai terkecil atau terbesar berikutnya.",
          completeQuestion: "Langkah 2 juga selesai. Mari lanjut ke langkah terakhir.",
          completeNav: "Ketuk langkah 3.",
        },
        6: {
          questionText: "Ada dua nilai tengah.<br>Bagaimana cara menemukan median kumpulan data dalam kasus ini?",
          navText: "Ketuk pilihan yang benar.",
          completeNav: "Ketuk &raquo; untuk menemukan median.",
          options: [
            "Jumlah dari dua nilai tengah",
            "Mean dari dua nilai tengah",
            "Salah satu nilai tengah",
          ],
          correctIndex: 1,
          wrongFeedback: "Jika ada dua nilai tengah, merata-ratakannya memberi kita median.",
          correctFeedback: "Benar! Jika ada dua nilai tengah, kita merata-ratakannya.",
        },
        7: {
          questionText: "Temukan mean dari dua nilai tengah.",
          completeQuestion: "Median dari kumpulan data ini adalah 6.",
          navText: "Isi jawaban menggunakan numpad dan ketuk ✓ untuk mengirim.",
          completeNav: "Ketuk &raquo; untuk sekarang menemukan mean dari kumpulan data ini.",
          denominator: 2,
          correctAnswer: 6,
        },
        8: {
          questionText: "Pertama, rumus mean.",
          completeQuestion: "Mari sekarang temukan mean dari kumpulan data",
          navText: "Seret pilihan yang benar ke tempat yang tepat.",
          completeNav: "Ketuk &raquo; untuk melanjutkan perhitungan mean.",
          dropPlaceholder: "Letakkan di sini",
        },
        9: {
          questionText: "Mari sekarang temukan mean dari kumpulan data.",
          navText: "Ketuk pembilang atau penyebut.",
          sumQuestion: "Berapa jumlah semua nilai: 3+6+4+4+8+7+8+9+4+5+6+6",
          sumNav: "Masukkan total yang benar menggunakan numpad.",
          sumCompleteQuestion: "Jumlah semua nilai: 3+6+4+4+8+7+8+9+4+5+6+6 = 70",
          sumCompleteNav: "Ketuk penyebut sekarang.",
          countCompleteNav: "Ketuk pembilang sekarang.",
          countQuestion: "Berapa jumlah total nilai data?",
          countNav: "Masukkan angka yang benar menggunakan numpad.",
          countCompleteQuestion: "Jumlah total nilai data adalah 12.",
          meanQuestion: "Bagi total dengan banyak titik data sekarang. Dan temukan mean.",
          meanNav: "Masukkan mean yang benar menggunakan numpad.",
          completeQuestion: "Mean dari angka-angka tersebut adalah 5.8",
          completeNav: "Ketuk &raquo;.",
          sumAnswer: 70,
          countAnswer: 12,
          meanAnswer: "5.8",
        },
      },
      meanDragDrop: {
        draggables: [
          { id: "sum", text: "Jumlah semua\nnilai data" },
          { id: "count", text: "Banyaknya\nnilai data" },
          { id: "mean", text: "Mean" },
        ],
        zoneMap: { left: "mean", num: "sum", denom: "count" },
        labels: {
          mean: "Mean",
          sum: "Jumlah semua nilai data",
          count: "Banyaknya nilai data",
        },
      },
      completion: {
        heading: "Kerja Bagus!",
        stats: ["Modus = 4 & 6", "Median = 6", "Mean = 5.8"],
        text: "Kamu berhasil menemukan modus, mean, dan median dari kumpulan data ini.<br><br> Ketuk 'Mulai Lagi' untuk mengulangi aktivitas ini.",
        buttonText: "Mulai Lagi",
      },
    },
  },
};

const APP_DATA = DATA[current_language].app;
