
const decimal = {
  en: ".",
  id: ",",
};

const DATA = {
  en: {
    app: {
      common: {
        tapNextToContinue: "Tap » to continue.",
        tapNumpadToFill: "Tap using numpad to fill in the highlighted box and Check.",
        tapNextToAddWeights: "Tap » to add the weights.",
        tapNextToAddKg: "Tap » to add weight in kg.",
        tapNextForAnother: "Tap » for another challenge.",
        tapNextToSummarise: "Tap » to summarise.",
        tapNextToSubtract: "Tap » to subtract the weights.",
        tapNextToSubtractKg: "Tap » to subtract weight in kg.",
      },
      start: {
        heading: "Word problems on weights",
        text: "Let's explore solving word problems on weights.<br><br>Tap \"Start\" to begin!",
        buttonText: "Start",
      },
      summary: {
        heading: "Adding Weights",
        text: "Awesome! Now you know how to solve word problems on weight.",
        buttonText: "Start Over",
      },
      steps: {
        1: {
          characterText: "Hi!\nI am Jammal.\nLet's explore solving some word problems related to weights.",
          characterImage: "normal.png",
        },
        2: {
          characterText: "Let's read the word problem.",
        },
        3: {
          characterText: "Step 1: Write the weights given in the word problem.",
        },
        4: {
          characterText: "Step 2: Choose the math action needed to solve the word problem.",
        },
      },
      mcqOptions: {
        add: "ADD",
        subtract: "SUBTRACT",
      },
      operatorQuestion: "Should we <y>add</y> or <y>subtract</y> the weights?\nCheck for words in the word problem that indicate addition or subtraction.",
      oops: "Oops!",
      tryAgain: "Try again.",
      wellDone: "Well done!",
      questions: [
        {
          statement: "A grocery store sold 600 g of flour in the morning and 250 g in the evening. How much flour was sold in total?",
          itemName1: "Flour sold in the morning",
          itemName2: "Flour sold in the evening",
          kgLabel: "kg",
          gmLabel: "gram",
          kgAns1: 0,
          gmAns1: 600,
          kgAns2: 0,
          gmAns2: 250,
          kgResult: 0,
          gmResult: 850,
          operation: "add",
          hintWord: "total",
          step3WrongFeedbackRow1: "Oops!\nTry again.\n600 g flour was sold in the morning.",
          step3WrongFeedbackRow2: "Oops!\nTry again.\n250 g flour was sold in the evening.",
          step3CorrectFeedback: "Well done!\nYou have correctly identified weights given in the question.",
          step4WrongFeedback: "Oops!\nRead the question again. Check for words that indicate the math action.",
          step4CorrectFeedback: "Well done!\nWord 'total' in the word problem indicated that weights should be added.",
          step5CharacterText: "Step 3: Add the weights.\n\nLet's add the gram first.",
          step5WrongFeedback: "Oops!\nTry again.\n\nAdd 600 and 250 to get the total weight in gram.",
          step5CorrectFeedback: "Well done!\n600 g + 250 g\n= 850 g.",
          step5CtAfterGm: "Step 3: Add the weights.\n600 g + 250 g\n= 850 g.\n\nLet's add the weight in kg.",
          step6WrongFeedback: "Oops!\nTry again.\n\nAdd 0 kg and 0 kg to get the total weight in kg.",
          step6CorrectFeedback: "Well done!\nTotal weight of the flour sold is\n0 kg 850 g.",
          step6FinalCt: "Well Done!\nThe total weight of the flour sold is 850 g.\n\nLet's try another question.",
          step6FinalCtLast: "Well Done!\nThe total weight of the flour sold is 850 g.",
          resultLabel: "Total",
        },
        {
          statement: "A shopkeeper has 4 kg 250 g of sugar in one sack and 3 kg 700 g in another sack. How much sugar does he have in total?",
          itemName1: "Sugar in one sack",
          itemName2: "Sugar in another sack",
          kgLabel: "kg",
          gmLabel: "gram",
          kgAns1: 4,
          gmAns1: 250,
          kgAns2: 3,
          gmAns2: 700,
          kgResult: 7,
          gmResult: 950,
          operation: "add",
          hintWord: "total",
          step3WrongFeedbackRow1: "Oops!\nTry again.\n4 kg 250 g of sugar is in one sack.",
          step3WrongFeedbackRow2: "Oops!\nTry again.\n3 kg 700 g of sugar is in the other sack.",
          step3CorrectFeedback: "Well done!\nYou have correctly identified weights given in the question.",
          step4WrongFeedback: "Oops!\nRead the question again. Check for words that indicate the math action.",
          step4CorrectFeedback: "Well done!\nWord 'total' in the word problem indicated that weights should be added.",
          step5CharacterText: "Step 3: Add the weights.\n\nLet's add the gram first.",
          step5WrongFeedback: "Oops!\nTry again.\n\nAdd 250 and 700 to get the total weight in gram.",
          step5CorrectFeedback: "Well done!\n250 g + 700 g\n= 950 g.",
          step5CtAfterGm: "Step 3: Add the weights.\n250 g + 700 g\n= 950 g.\n\nLet's add the weight in kg.",
          step6WrongFeedback: "Oops!\nTry again.\n\nAdd 4 kg and 3 kg to get the total weight in kg.",
          step6CorrectFeedback: "Well done!\nTotal weight of sugar is\n7 kg 950 g.",
          step6FinalCt: "Well Done!\nThe total weight of sugar is 7 kg 950 g.\n\nLet's try another question.",
          step6FinalCtLast: "Well Done!\nThe total weight of sugar is 7 kg 950 g.",
          resultLabel: "Total",
        },
        {
          statement: "A baker bought 5 kg 700 g of flour. She used 3 kg 150 g. How much flour is left?",
          itemName1: "Flour bought",
          itemName2: "Flour used",
          kgLabel: "kg",
          gmLabel: "gram",
          kgAns1: 5,
          gmAns1: 700,
          kgAns2: 3,
          gmAns2: 150,
          kgResult: 2,
          gmResult: 550,
          operation: "subtract",
          hintWord: "left",
          step3WrongFeedbackRow1: "Oops!\nTry again.\n5 kg 700 g of flour was bought.",
          step3WrongFeedbackRow2: "Oops!\nTry again.\n3 kg 150 g of flour was used.",
          step3CorrectFeedback: "Well done!\nYou have correctly identified weights given in the question.",
          step4WrongFeedback: "Oops!\nRead the question again. Check for words that indicate the math action.",
          step4CorrectFeedback: "Well done!\nWord 'left' in the word problem indicated that weights should be subtracted.",
          step5CharacterText: "Step 3: Subtract the weights.\n\nLet's subtract the gram first.",
          step5WrongFeedback: "Oops!\nTry again.\n\nSubtract 150 from 700 to get the remaining weight in gram.",
          step5CorrectFeedback: "Well done!\n700 g - 150 g\n= 550 g.",
          step5CtAfterGm: "Step 3: Subtract the weights.\n700 g - 150 g\n= 550 g.\n\nLet's subtract the weight in kg.",
          step6WrongFeedback: "Oops!\nTry again.\n\nSubtract 3 kg from 5 kg to get the remaining weight in kg.",
          step6CorrectFeedback: "Well done!\nRemaining flour is\n2 kg 550 g.",
          step6FinalCt: "Well Done!\nThe remaining flour is 2 kg 550 g.\n\nLet's try another question.",
          step6FinalCtLast: "Well Done!\nThe remaining flour is 2 kg 550 g.",
          resultLabel: "Remaining",
        },
        {
          statement: "A warehouse has 12 kg of rice in one bag and 5 kg in another bag. What is the total weight of rice?",
          itemName1: "Rice in one bag",
          itemName2: "Rice in another bag",
          kgLabel: "kg",
          gmLabel: "gram",
          kgAns1: 12,
          gmAns1: 0,
          kgAns2: 5,
          gmAns2: 0,
          kgResult: 17,
          gmResult: 0,
          operation: "add",
          hintWord: "total",
          step3WrongFeedbackRow1: "Oops!\nTry again.\n12 kg of rice is in one bag.",
          step3WrongFeedbackRow2: "Oops!\nTry again.\n5 kg of rice is in the other bag.",
          step3CorrectFeedback: "Well done!\nYou have correctly identified weights given in the question.",
          step4WrongFeedback: "Oops!\nRead the question again. Check for words that indicate the math action.",
          step4CorrectFeedback: "Well done!\nWord 'total' in the word problem indicated that weights should be added.",
          step5CharacterText: "Step 3: Add the weights.\n\nLet's add the gram first.",
          step5WrongFeedback: "Oops!\nTry again.\n\nAdd 0 and 0 to get the total weight in gram.",
          step5CorrectFeedback: "Well done!\n0 g + 0 g\n= 0 g.",
          step5CtAfterGm: "Step 3: Add the weights.\n0 g + 0 g\n= 0 g.\n\nLet's add the weight in kg.",
          step6WrongFeedback: "Oops!\nTry again.\n\nAdd 12 kg and 5 kg to get the total weight in kg.",
          step6CorrectFeedback: "Well done!\nTotal weight of rice is\n17 kg 0 g.",
          step6FinalCt: "Well Done!\nThe total weight of rice is 17 kg.\n\nLet's try another question.",
          step6FinalCtLast: "Well Done!\nThe total weight of rice is 17 kg.",
          resultLabel: "Total",
        },
        {
          statement: "Two boxes contain 14 kg 125 g and 9 kg 75 g of apples. What is the total weight of apples?",
          itemName1: "Weight of apples in one box",
          itemName2: "Weight of apples in another box",
          kgLabel: "kg",
          gmLabel: "gram",
          kgAns1: 14,
          gmAns1: 125,
          kgAns2: 9,
          gmAns2: 75,
          kgResult: 23,
          gmResult: 200,
          operation: "add",
          hintWord: "total",
          step3WrongFeedbackRow1: "Oops!\nTry again.\n14 kg 125 g of apples is in one box.",
          step3WrongFeedbackRow2: "Oops!\nTry again.\n9 kg 75 g of apples is in the other box.",
          step3CorrectFeedback: "Well done!\nYou have correctly identified weights given in the question.",
          step4WrongFeedback: "Oops!\nRead the question again. Check for words that indicate the math action.",
          step4CorrectFeedback: "Well done!\nWord 'total' in the word problem indicated that weights should be added.",
          step5CharacterText: "Step 3: Add the weights.\n\nLet's add the gram first.",
          step5WrongFeedback: "Oops!\nTry again.\n\nAdd 125 and 75 to get the total weight in gram.",
          step5CorrectFeedback: "Well done!\n125 g + 75 g\n= 200 g.",
          step5CtAfterGm: "Step 3: Add the weights.\n125 g + 75 g\n= 200 g.\n\nLet's add the weight in kg.",
          step6WrongFeedback: "Oops!\nTry again.\n\nAdd 14 kg and 9 kg to get the total weight in kg.",
          step6CorrectFeedback: "Well done!\nTotal weight of apples is\n23 kg 200 g.",
          step6FinalCt: "Well Done!\nThe total weight of apples is 23 kg 200 g.\n\nLet's try another question.",
          step6FinalCtLast: "Well Done!\nThe total weight of apples is 23 kg 200 g.",
          resultLabel: "Total",
        },
        {
          statement: "A truck carries 21 kg of potatoes in one trip and 17 kg 350 g in another trip. What is the total weight of potatoes carried?",
          itemName1: "Potatoes in one trip",
          itemName2: "Potatoes in another trip",
          kgLabel: "kg",
          gmLabel: "gram",
          kgAns1: 21,
          gmAns1: 0,
          kgAns2: 17,
          gmAns2: 350,
          kgResult: 38,
          gmResult: 350,
          operation: "add",
          hintWord: "total",
          step3WrongFeedbackRow1: "Oops!\nTry again.\n21 kg of potatoes is carried in one trip.",
          step3WrongFeedbackRow2: "Oops!\nTry again.\n17 kg 350 g of potatoes is in the other trip.",
          step3CorrectFeedback: "Well done!\nYou have correctly identified weights given in the question.",
          step4WrongFeedback: "Oops!\nRead the question again. Check for words that indicate the math action.",
          step4CorrectFeedback: "Well done!\nWord 'total' in the word problem indicated that weights should be added.",
          step5CharacterText: "Step 3: Add the weights.\n\nLet's add the gram first.",
          step5WrongFeedback: "Oops!\nTry again.\n\nAdd 0 and 350 to get the total weight in gram.",
          step5CorrectFeedback: "Well done!\n0 g + 350 g\n= 350 g.",
          step5CtAfterGm: "Step 3: Add the weights.\n0 g + 350 g\n= 350 g.\n\nLet's add the weight in kg.",
          step6WrongFeedback: "Oops!\nTry again.\n\nAdd 21 kg and 17 kg to get the total weight in kg.",
          step6CorrectFeedback: "Well done!\nTotal weight of potatoes carried is\n38 kg 350 g.",
          step6FinalCt: "Well Done!\nThe total weight of potatoes carried is 38 kg 350 g.\n\nLet's try another question.",
          step6FinalCtLast: "Well Done!\nThe total weight of potatoes carried is 38 kg 350 g.",
          resultLabel: "Total",
        },
        {
          statement: "A shop had 7 kg 600 g of rice. It sold 2 kg 450 g. How much rice is left?",
          itemName1: "Rice in the shop",
          itemName2: "Rice sold",
          kgLabel: "kg",
          gmLabel: "gram",
          kgAns1: 7,
          gmAns1: 600,
          kgAns2: 2,
          gmAns2: 450,
          kgResult: 5,
          gmResult: 150,
          operation: "subtract",
          hintWord: "left",
          step3WrongFeedbackRow1: "Oops!\nTry again.\n7 kg 600 g of rice was in the shop.",
          step3WrongFeedbackRow2: "Oops!\nTry again.\n2 kg 450 g of rice was sold.",
          step3CorrectFeedback: "Well done!\nYou have correctly identified weights given in the question.",
          step4WrongFeedback: "Oops!\nRead the question again. Check for words that indicate the math action.",
          step4CorrectFeedback: "Well done!\nWord 'left' in the word problem indicated that weights should be subtracted.",
          step5CharacterText: "Step 3: Subtract the weights.\n\nLet's subtract the gram first.",
          step5WrongFeedback: "Oops!\nTry again.\n\nSubtract 450 from 600 to get the remaining weight in gram.",
          step5CorrectFeedback: "Well done!\n600 g - 450 g\n= 150 g.",
          step5CtAfterGm: "Step 3: Subtract the weights.\n600 g - 450 g\n= 150 g.\n\nLet's subtract the weight in kg.",
          step6WrongFeedback: "Oops!\nTry again.\n\nSubtract 2 kg from 7 kg to get the remaining weight in kg.",
          step6CorrectFeedback: "Well done!\nRice left in the shop is\n5 kg 150 g.",
          step6FinalCt: "Well Done!\nThe rice left in the shop is 5 kg 150 g.\n\nLet's try another question.",
          step6FinalCtLast: "Well Done!\nThe rice left in the shop is 5 kg 150 g.",
          resultLabel: "Remaining",
        },
        {
          statement: "A truck carried 30 kg of potatoes. It delivered 12 kg. How much weight is still in the truck?",
          itemName1: "Weight of potatoes in truck",
          itemName2: "Weight delivered",
          kgLabel: "kg",
          gmLabel: "gram",
          kgAns1: 30,
          gmAns1: 0,
          kgAns2: 12,
          gmAns2: 0,
          kgResult: 18,
          gmResult: 0,
          operation: "subtract",
          hintWord: "still",
          step3WrongFeedbackRow1: "Oops!\nTry again.\n30 kg of potatoes is in the truck.",
          step3WrongFeedbackRow2: "Oops!\nTry again.\n12 kg of potatoes was delivered.",
          step3CorrectFeedback: "Well done!\nYou have correctly identified weights given in the question.",
          step4WrongFeedback: "Oops!\nRead the question again. Check for words that indicate the math action.",
          step4CorrectFeedback: "Well done!\nWords like 'still in the truck' in the word problem indicated that weights should be subtracted.",
          step5CharacterText: "Step 3: Subtract the weights.\n\nLet's subtract the gram first.",
          step5WrongFeedback: "Oops!\nTry again.\n\nSubtract 0 from 0 to get the remaining weight in gram.",
          step5CorrectFeedback: "Well done!\n0 g - 0 g\n= 0 g.",
          step5CtAfterGm: "Step 3: Subtract the weights.\n0 g - 0 g\n= 0 g.\n\nLet's subtract the weight in kg.",
          step6WrongFeedback: "Oops!\nTry again.\n\nSubtract 12 kg from 30 kg to get the remaining weight in kg.",
          step6CorrectFeedback: "Well done!\nWeight still in the truck is\n18 kg 0 g.",
          step6FinalCt: "Well Done!\nThe weight still in the truck is 18 kg.\n\nLet's try another question.",
          step6FinalCtLast: "Well Done!\nThe weight still in the truck is 18 kg.",
          resultLabel: "Remaining",
        },
      ],
    },
  },
  id: {
    app: {
      common: {
        tapNextToContinue: "Ketuk » untuk melanjutkan.",
        tapNumpadToFill: "Ketuk numpad untuk mengisi kotak yang disorot dan Periksa.",
        tapNextToAddWeights: "Ketuk » untuk menambahkan berat.",
        tapNextToAddKg: "Ketuk » untuk menambahkan berat dalam kg.",
        tapNextForAnother: "Ketuk » untuk tantangan lain.",
        tapNextToSummarise: "Ketuk » untuk merangkum.",
        tapNextToSubtract: "Ketuk » untuk mengurangi berat.",
        tapNextToSubtractKg: "Ketuk » untuk mengurangi berat dalam kg.",
      },
      start: {
        heading: "Soal cerita tentang berat",
        text: "Mari kita jelajahi cara menyelesaikan soal cerita tentang berat.<br><br>Ketuk \"Mulai\" untuk memulai!",
        buttonText: "Mulai",
      },
      summary: {
        heading: "Menambahkan Berat",
        text: "Luar biasa! Sekarang kamu tahu cara menyelesaikan soal cerita tentang berat.",
        buttonText: "Ulangi",
      },
      steps: {
        1: {
          characterText: "Hai!\nSaya Jammal.\nMari kita jelajahi cara menyelesaikan beberapa soal cerita tentang berat.",
          characterImage: "normal.png",
        },
        2: {
          characterText: "Mari kita baca soal ceritanya.",
        },
        3: {
          characterText: "Langkah 1: Tuliskan berat yang diberikan dalam soal cerita.",
        },
        4: {
          characterText: "Langkah 2: Pilih operasi matematika yang diperlukan untuk menyelesaikan soal cerita.",
        },
      },
      mcqOptions: {
        add: "TAMBAH",
        subtract: "KURANG",
      },
      operatorQuestion: "Haruskah kita <y>menambah</y> atau <y>mengurangi</y> berat?\nPeriksa kata-kata dalam soal cerita yang menunjukkan penjumlahan atau pengurangan.",
      oops: "Ups!",
      tryAgain: "Coba lagi.",
      wellDone: "Bagus!",
      questions: [
        {
          statement: "Sebuah toko kelontong menjual 600 g tepung di pagi hari dan 250 g di sore hari. Berapa total tepung yang terjual?",
          itemName1: "Tepung terjual di pagi hari",
          itemName2: "Tepung terjual di sore hari",
          kgLabel: "kg",
          gmLabel: "gram",
          kgAns1: 0,
          gmAns1: 600,
          kgAns2: 0,
          gmAns2: 250,
          kgResult: 0,
          gmResult: 850,
          operation: "add",
          hintWord: "total",
          step3WrongFeedbackRow1: "Ups!\nCoba lagi.\n600 g tepung terjual di pagi hari.",
          step3WrongFeedbackRow2: "Ups!\nCoba lagi.\n250 g tepung terjual di sore hari.",
          step3CorrectFeedback: "Bagus!\nKamu telah mengidentifikasi berat yang diberikan dalam soal dengan benar.",
          step4WrongFeedback: "Ups!\nBaca soalnya lagi. Periksa kata-kata yang menunjukkan operasi matematika.",
          step4CorrectFeedback: "Bagus!\nKata 'total' dalam soal cerita menunjukkan bahwa berat harus ditambahkan.",
          step5CharacterText: "Langkah 3: Tambahkan berat.\n\nMari tambahkan gram terlebih dahulu.",
          step5WrongFeedback: "Ups!\nCoba lagi.\n\nTambahkan 600 dan 250 untuk mendapatkan total berat dalam gram.",
          step5CorrectFeedback: "Bagus!\n600 g + 250 g\n= 850 g.",
          step5CtAfterGm: "Langkah 3: Tambahkan berat.\n600 g + 250 g\n= 850 g.\n\nMari tambahkan berat dalam kg.",
          step6WrongFeedback: "Ups!\nCoba lagi.\n\nTambahkan 0 kg dan 0 kg untuk mendapatkan total berat dalam kg.",
          step6CorrectFeedback: "Bagus!\nTotal berat tepung yang terjual adalah\n0 kg 850 g.",
          step6FinalCt: "Bagus Sekali!\nTotal berat tepung yang terjual adalah 850 g.\n\nMari coba soal lain.",
          step6FinalCtLast: "Bagus Sekali!\nTotal berat tepung yang terjual adalah 850 g.",
          resultLabel: "Total",
        },
        {
          statement: "Seorang penjaga toko memiliki 4 kg 250 g gula di satu karung dan 3 kg 700 g di karung lainnya. Berapa total gula yang dimilikinya?",
          itemName1: "Gula di satu karung",
          itemName2: "Gula di karung lain",
          kgLabel: "kg",
          gmLabel: "gram",
          kgAns1: 4,
          gmAns1: 250,
          kgAns2: 3,
          gmAns2: 700,
          kgResult: 7,
          gmResult: 950,
          operation: "add",
          hintWord: "total",
          step3WrongFeedbackRow1: "Ups!\nCoba lagi.\n4 kg 250 g gula ada di satu karung.",
          step3WrongFeedbackRow2: "Ups!\nCoba lagi.\n3 kg 700 g gula di karung lainnya.",
          step3CorrectFeedback: "Bagus!\nKamu telah mengidentifikasi berat yang diberikan dalam soal dengan benar.",
          step4WrongFeedback: "Ups!\nBaca soalnya lagi. Periksa kata-kata yang menunjukkan operasi matematika.",
          step4CorrectFeedback: "Bagus!\nKata 'total' dalam soal cerita menunjukkan bahwa berat harus ditambahkan.",
          step5CharacterText: "Langkah 3: Tambahkan berat.\n\nMari tambahkan gram terlebih dahulu.",
          step5WrongFeedback: "Ups!\nCoba lagi.\n\nTambahkan 250 dan 700 untuk mendapatkan total berat dalam gram.",
          step5CorrectFeedback: "Bagus!\n250 g + 700 g\n= 950 g.",
          step5CtAfterGm: "Langkah 3: Tambahkan berat.\n250 g + 700 g\n= 950 g.\n\nMari tambahkan berat dalam kg.",
          step6WrongFeedback: "Ups!\nCoba lagi.\n\nTambahkan 4 kg dan 3 kg untuk mendapatkan total berat dalam kg.",
          step6CorrectFeedback: "Bagus!\nTotal berat gula adalah\n7 kg 950 g.",
          step6FinalCt: "Bagus Sekali!\nTotal berat gula adalah 7 kg 950 g.\n\nMari coba soal lain.",
          step6FinalCtLast: "Bagus Sekali!\nTotal berat gula adalah 7 kg 950 g.",
          resultLabel: "Total",
        },
        {
          statement: "Seorang tukang roti membeli 5 kg 700 g tepung. Dia menggunakan 3 kg 150 g. Berapa sisa tepung?",
          itemName1: "Tepung dibeli",
          itemName2: "Tepung digunakan",
          kgLabel: "kg",
          gmLabel: "gram",
          kgAns1: 5,
          gmAns1: 700,
          kgAns2: 3,
          gmAns2: 150,
          kgResult: 2,
          gmResult: 550,
          operation: "subtract",
          hintWord: "sisa",
          step3WrongFeedbackRow1: "Ups!\nCoba lagi.\n5 kg 700 g tepung dibeli.",
          step3WrongFeedbackRow2: "Ups!\nCoba lagi.\n3 kg 150 g tepung digunakan.",
          step3CorrectFeedback: "Bagus!\nKamu telah mengidentifikasi berat yang diberikan dalam soal dengan benar.",
          step4WrongFeedback: "Ups!\nBaca soalnya lagi. Periksa kata-kata yang menunjukkan operasi matematika.",
          step4CorrectFeedback: "Bagus!\nKata 'sisa' dalam soal cerita menunjukkan bahwa berat harus dikurangkan.",
          step5CharacterText: "Langkah 3: Kurangi berat.\n\nMari kurangi gram terlebih dahulu.",
          step5WrongFeedback: "Ups!\nCoba lagi.\n\nKurangi 150 dari 700 untuk mendapatkan sisa berat dalam gram.",
          step5CorrectFeedback: "Bagus!\n700 g - 150 g\n= 550 g.",
          step5CtAfterGm: "Langkah 3: Kurangi berat.\n700 g - 150 g\n= 550 g.\n\nMari kurangi berat dalam kg.",
          step6WrongFeedback: "Ups!\nCoba lagi.\n\nKurangi 3 kg dari 5 kg untuk mendapatkan sisa berat dalam kg.",
          step6CorrectFeedback: "Bagus!\nSisa tepung adalah\n2 kg 550 g.",
          step6FinalCt: "Bagus Sekali!\nSisa tepung adalah 2 kg 550 g.\n\nMari coba soal lain.",
          step6FinalCtLast: "Bagus Sekali!\nSisa tepung adalah 2 kg 550 g.",
          resultLabel: "Sisa",
        },
        {
          statement: "Sebuah gudang memiliki 12 kg beras di satu karung dan 5 kg di karung lainnya. Berapa total berat beras?",
          itemName1: "Beras di satu karung",
          itemName2: "Beras di karung lain",
          kgLabel: "kg",
          gmLabel: "gram",
          kgAns1: 12,
          gmAns1: 0,
          kgAns2: 5,
          gmAns2: 0,
          kgResult: 17,
          gmResult: 0,
          operation: "add",
          hintWord: "total",
          step3WrongFeedbackRow1: "Ups!\nCoba lagi.\n12 kg beras ada di satu karung.",
          step3WrongFeedbackRow2: "Ups!\nCoba lagi.\n5 kg beras ada di karung lainnya.",
          step3CorrectFeedback: "Bagus!\nKamu telah mengidentifikasi berat yang diberikan dalam soal dengan benar.",
          step4WrongFeedback: "Ups!\nBaca soalnya lagi. Periksa kata-kata yang menunjukkan operasi matematika.",
          step4CorrectFeedback: "Bagus!\nKata 'total' dalam soal cerita menunjukkan bahwa berat harus ditambahkan.",
          step5CharacterText: "Langkah 3: Tambahkan berat.\n\nMari tambahkan gram terlebih dahulu.",
          step5WrongFeedback: "Ups!\nCoba lagi.\n\nTambahkan 0 dan 0 untuk mendapatkan total berat dalam gram.",
          step5CorrectFeedback: "Bagus!\n0 g + 0 g\n= 0 g.",
          step5CtAfterGm: "Langkah 3: Tambahkan berat.\n0 g + 0 g\n= 0 g.\n\nMari tambahkan berat dalam kg.",
          step6WrongFeedback: "Ups!\nCoba lagi.\n\nTambahkan 12 kg dan 5 kg untuk mendapatkan total berat dalam kg.",
          step6CorrectFeedback: "Bagus!\nTotal berat beras adalah\n17 kg 0 g.",
          step6FinalCt: "Bagus Sekali!\nTotal berat beras adalah 17 kg.\n\nMari coba soal lain.",
          step6FinalCtLast: "Bagus Sekali!\nTotal berat beras adalah 17 kg.",
          resultLabel: "Total",
        },
        {
          statement: "Dua kotak berisi 14 kg 125 g dan 9 kg 75 g apel. Berapa total berat apel?",
          itemName1: "Berat apel di satu kotak",
          itemName2: "Berat apel di kotak lain",
          kgLabel: "kg",
          gmLabel: "gram",
          kgAns1: 14,
          gmAns1: 125,
          kgAns2: 9,
          gmAns2: 75,
          kgResult: 23,
          gmResult: 200,
          operation: "add",
          hintWord: "total",
          step3WrongFeedbackRow1: "Ups!\nCoba lagi.\n14 kg 125 g apel ada di satu kotak.",
          step3WrongFeedbackRow2: "Ups!\nCoba lagi.\n9 kg 75 g apel ada di kotak lainnya.",
          step3CorrectFeedback: "Bagus!\nKamu telah mengidentifikasi berat yang diberikan dalam soal dengan benar.",
          step4WrongFeedback: "Ups!\nBaca soalnya lagi. Periksa kata-kata yang menunjukkan operasi matematika.",
          step4CorrectFeedback: "Bagus!\nKata 'total' dalam soal cerita menunjukkan bahwa berat harus ditambahkan.",
          step5CharacterText: "Langkah 3: Tambahkan berat.\n\nMari tambahkan gram terlebih dahulu.",
          step5WrongFeedback: "Ups!\nCoba lagi.\n\nTambahkan 125 dan 75 untuk mendapatkan total berat dalam gram.",
          step5CorrectFeedback: "Bagus!\n125 g + 75 g\n= 200 g.",
          step5CtAfterGm: "Langkah 3: Tambahkan berat.\n125 g + 75 g\n= 200 g.\n\nMari tambahkan berat dalam kg.",
          step6WrongFeedback: "Ups!\nCoba lagi.\n\nTambahkan 14 kg dan 9 kg untuk mendapatkan total berat dalam kg.",
          step6CorrectFeedback: "Bagus!\nTotal berat apel adalah\n23 kg 200 g.",
          step6FinalCt: "Bagus Sekali!\nTotal berat apel adalah 23 kg 200 g.\n\nMari coba soal lain.",
          step6FinalCtLast: "Bagus Sekali!\nTotal berat apel adalah 23 kg 200 g.",
          resultLabel: "Total",
        },
        {
          statement: "Sebuah truk mengangkut 21 kg kentang dalam satu perjalanan dan 17 kg 350 g dalam perjalanan lainnya. Berapa total berat kentang yang diangkut?",
          itemName1: "Kentang di satu perjalanan",
          itemName2: "Kentang di perjalanan lain",
          kgLabel: "kg",
          gmLabel: "gram",
          kgAns1: 21,
          gmAns1: 0,
          kgAns2: 17,
          gmAns2: 350,
          kgResult: 38,
          gmResult: 350,
          operation: "add",
          hintWord: "total",
          step3WrongFeedbackRow1: "Ups!\nCoba lagi.\n21 kg kentang diangkut dalam satu perjalanan.",
          step3WrongFeedbackRow2: "Ups!\nCoba lagi.\n17 kg 350 g kentang ada di perjalanan lainnya.",
          step3CorrectFeedback: "Bagus!\nKamu telah mengidentifikasi berat yang diberikan dalam soal dengan benar.",
          step4WrongFeedback: "Ups!\nBaca soalnya lagi. Periksa kata-kata yang menunjukkan operasi matematika.",
          step4CorrectFeedback: "Bagus!\nKata 'total' dalam soal cerita menunjukkan bahwa berat harus ditambahkan.",
          step5CharacterText: "Langkah 3: Tambahkan berat.\n\nMari tambahkan gram terlebih dahulu.",
          step5WrongFeedback: "Ups!\nCoba lagi.\n\nTambahkan 0 dan 350 untuk mendapatkan total berat dalam gram.",
          step5CorrectFeedback: "Bagus!\n0 g + 350 g\n= 350 g.",
          step5CtAfterGm: "Langkah 3: Tambahkan berat.\n0 g + 350 g\n= 350 g.\n\nMari tambahkan berat dalam kg.",
          step6WrongFeedback: "Ups!\nCoba lagi.\n\nTambahkan 21 kg dan 17 kg untuk mendapatkan total berat dalam kg.",
          step6CorrectFeedback: "Bagus!\nTotal berat kentang yang diangkut adalah\n38 kg 350 g.",
          step6FinalCt: "Bagus Sekali!\nTotal berat kentang yang diangkut adalah 38 kg 350 g.\n\nMari coba soal lain.",
          step6FinalCtLast: "Bagus Sekali!\nTotal berat kentang yang diangkut adalah 38 kg 350 g.",
          resultLabel: "Total",
        },
        {
          statement: "Sebuah toko memiliki 7 kg 600 g beras. Toko tersebut menjual 2 kg 450 g. Berapa sisa beras?",
          itemName1: "Beras di toko",
          itemName2: "Beras terjual",
          kgLabel: "kg",
          gmLabel: "gram",
          kgAns1: 7,
          gmAns1: 600,
          kgAns2: 2,
          gmAns2: 450,
          kgResult: 5,
          gmResult: 150,
          operation: "subtract",
          hintWord: "sisa",
          step3WrongFeedbackRow1: "Ups!\nCoba lagi.\n7 kg 600 g beras ada di toko.",
          step3WrongFeedbackRow2: "Ups!\nCoba lagi.\n2 kg 450 g beras telah terjual.",
          step3CorrectFeedback: "Bagus!\nKamu telah mengidentifikasi berat yang diberikan dalam soal dengan benar.",
          step4WrongFeedback: "Ups!\nBaca soalnya lagi. Periksa kata-kata yang menunjukkan operasi matematika.",
          step4CorrectFeedback: "Bagus!\nKata 'sisa' dalam soal cerita menunjukkan bahwa berat harus dikurangkan.",
          step5CharacterText: "Langkah 3: Kurangi berat.\n\nMari kurangi gram terlebih dahulu.",
          step5WrongFeedback: "Ups!\nCoba lagi.\n\nKurangi 450 dari 600 untuk mendapatkan sisa berat dalam gram.",
          step5CorrectFeedback: "Bagus!\n600 g - 450 g\n= 150 g.",
          step5CtAfterGm: "Langkah 3: Kurangi berat.\n600 g - 450 g\n= 150 g.\n\nMari kurangi berat dalam kg.",
          step6WrongFeedback: "Ups!\nCoba lagi.\n\nKurangi 2 kg dari 7 kg untuk mendapatkan sisa berat dalam kg.",
          step6CorrectFeedback: "Bagus!\nSisa beras di toko adalah\n5 kg 150 g.",
          step6FinalCt: "Bagus Sekali!\nSisa beras di toko adalah 5 kg 150 g.\n\nMari coba soal lain.",
          step6FinalCtLast: "Bagus Sekali!\nSisa beras di toko adalah 5 kg 150 g.",
          resultLabel: "Sisa",
        },
        {
          statement: "Sebuah truk mengangkut 30 kg kentang. Truk tersebut mengirimkan 12 kg. Berapa berat yang masih ada di truk?",
          itemName1: "Berat kentang di truk",
          itemName2: "Berat yang dikirim",
          kgLabel: "kg",
          gmLabel: "gram",
          kgAns1: 30,
          gmAns1: 0,
          kgAns2: 12,
          gmAns2: 0,
          kgResult: 18,
          gmResult: 0,
          operation: "subtract",
          hintWord: "masih",
          step3WrongFeedbackRow1: "Ups!\nCoba lagi.\n30 kg kentang ada di truk.",
          step3WrongFeedbackRow2: "Ups!\nCoba lagi.\n12 kg kentang telah dikirim.",
          step3CorrectFeedback: "Bagus!\nKamu telah mengidentifikasi berat yang diberikan dalam soal dengan benar.",
          step4WrongFeedback: "Ups!\nBaca soalnya lagi. Periksa kata-kata yang menunjukkan operasi matematika.",
          step4CorrectFeedback: "Bagus!\nKata-kata seperti 'masih di truk' dalam soal cerita menunjukkan bahwa berat harus dikurangkan.",
          step5CharacterText: "Langkah 3: Kurangi berat.\n\nMari kurangi gram terlebih dahulu.",
          step5WrongFeedback: "Ups!\nCoba lagi.\n\nKurangi 0 dari 0 untuk mendapatkan sisa berat dalam gram.",
          step5CorrectFeedback: "Bagus!\n0 g - 0 g\n= 0 g.",
          step5CtAfterGm: "Langkah 3: Kurangi berat.\n0 g - 0 g\n= 0 g.\n\nMari kurangi berat dalam kg.",
          step6WrongFeedback: "Ups!\nCoba lagi.\n\nKurangi 12 kg dari 30 kg untuk mendapatkan sisa berat dalam kg.",
          step6CorrectFeedback: "Bagus!\nBerat yang masih ada di truk adalah\n18 kg 0 g.",
          step6FinalCt: "Bagus Sekali!\nBerat yang masih ada di truk adalah 18 kg.\n\nMari coba soal lain.",
          step6FinalCtLast: "Bagus Sekali!\nBerat yang masih ada di truk adalah 18 kg.",
          resultLabel: "Sisa",
        },
      ],
    },
  },
};

const APP_DATA = DATA[current_language].app;
const decimalSymbol = decimal[current_language];
