const MainCanvas = (props) => {
  const {
    step,
    sliderK,
    visualK,
    kMin,
    kMax,
    kCenter,
    sliderMode,
    sliderLocked,
    sliderHidden,
    showThumbValue,
    smallThumb,
    showCenterMarker,
    showGhostTriangle,
    showZoomLabels,
    zoomOutDimmed,
    zoomInDimmed,
    scaleFactorLabel,
    showClickPoints,
    pointStates,
    rightPanelVisible,
    rightPanelText,
    mcq,
    mcqWrongIndices,
    mcqCorrectIndex,
    mcqAnswered,
    pointFeedback,
    showDragNudge,
    dragNudgeFromPct,
    dragNudgeToPct,
    onKChange,
    onKRelease,
    onKDragStart,
    onMcqSelect,
    onPointClick,
  } = props;

  return React.createElement(
    "div",
    { className: "main-canvas-container dilation-layout" },
    React.createElement(
      "div",
      { className: "dilation-left-col" },
      React.createElement(DilationGraph, {
        center: DILATION_GEOMETRY.center,
        triangle: DILATION_GEOMETRY.triangle,
        sliderK: sliderK,
        visualK: visualK,
        kMin: kMin,
        kMax: kMax,
        kCenter: kCenter,
        sliderMode: sliderMode,
        sliderLocked: sliderLocked,
        sliderHidden: sliderHidden,
        showThumbValue: showThumbValue,
        smallThumb: smallThumb,
        showCenterMarker: showCenterMarker,
        showGhostTriangle: showGhostTriangle,
        showZoomLabels: showZoomLabels,
        zoomOutDimmed: zoomOutDimmed,
        zoomInDimmed: zoomInDimmed,
        scaleFactorLabel: scaleFactorLabel,
        showClickPoints: showClickPoints,
        pointStates: pointStates,
        showDragNudge: showDragNudge,
        dragNudgeFromPct: dragNudgeFromPct,
        dragNudgeToPct: dragNudgeToPct,
        onPointClick: onPointClick,
        onKChange: onKChange,
        onKRelease: onKRelease,
        onKDragStart: onKDragStart,
      }),
    ),
    React.createElement(RightPanel, {
      visible: rightPanelVisible,
      textHtml: rightPanelText,
      mcq: mcq,
      mcqWrongIndices: mcqWrongIndices,
      mcqCorrectIndex: mcqCorrectIndex,
      mcqAnswered: mcqAnswered,
      onMcqSelect: onMcqSelect,
    }),
    pointFeedback
      ? React.createElement("div", {
          className:
            "point-feedback-box" +
            (pointFeedback.type === "wrong" ? " is-wrong" : " is-correct"),
          dangerouslySetInnerHTML: { __html: pointFeedback.html },
        })
      : null,
  );
};
